In [1]:
!pip install mp-api pymatgen matminer pandas numpy python-dotenv scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mp-api in c:\users\admin\appdata\roaming\python\python313\site-packages (0.46.5)
Requirement already satisfied: pymatgen in c:\users\admin\appdata\roaming\python\python313\site-packages (2026.9.24)
Requirement already satisfied: matminer in c:\users\admin\appdata\roaming\python\python313\site-packages (0.10.1)
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (2.3.5)
Requirement already satisfied: python-dotenv in c:\programdata\anaconda3\lib\site-packages (1.1.0)
Requirement already satisfied: scikit-learn in c:\programdata\anaconda3\lib\site-packages (1.7.2)
Requirement already satisfied: typing-extensions>=3.7.4.1 in c:\programdata\anaconda3\lib\site-packages (from mp-api) (4.15.0)
Requirement already satisfied: requests>=2.23.0 in c:\programdata\anaconda3\lib\site-packages (from mp-api) (2.32.5)
Requirement already satisfied: monty>=2024.12.10 in c:\users\admin\appdata\roaming\python\python313\site-packages (from mp-api) (2026.7.16)
Requirement already satisfied: emmet-core>=0.87.1 in c:\users\admin\appdata\roaming\python\python313\site-packages (from mp-api) (0.87.2)
Requirement already satisfied: boto3 in c:\users\admin\appdata\roaming\python\python313\site-packages (from mp-api) (1.43.100)
Requirement already satisfied: orjson<4,>=3.10 in c:\users\admin\appdata\roaming\python\python313\site-packages (from mp-api) (3.12.0)
Requirement already satisfied: pyarrow>=20.0.0 in c:\programdata\anaconda3\lib\site-packages (from mp-api) (21.0.0)
Requirement already satisfied: deltalake<1.6.0,>=1.4.0 in c:\users\admin\appdata\roaming\python\python313\site-packages (from mp-api) (1.5.1)
Requirement already satisfied: arro3-core>=0.5.0 in c:\users\admin\appdata\roaming\python\python313\site-packages (from deltalake<1.6.0,>=1.4.0->mp-api) (0.8.3)
Requirement already satisfied: deprecated>=1.2.18 in c:\users\admin\appdata\roaming\python\python313\site-packages (from deltalake<1.6.0,>=1.4.0->mp-api) (1.3.1)
Requirement already satisfied: pymatgen-core>=2026.9.23 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymatgen) (2026.9.23)
Requirement already satisfied: tqdm~=4.66 in c:\users\admin\appdata\roaming\python\python313\site-packages (from matminer) (4.70.1)
Requirement already satisfied: pymongo~=4.5 in c:\users\admin\appdata\roaming\python\python313\site-packages (from matminer) (4.18.2)
Requirement already satisfied: sympy~=1.11 in c:\programdata\anaconda3\lib\site-packages (from matminer) (1.14.0)
Requirement already satisfied: scipy>=1.17.0 in c:\users\admin\appdata\roaming\python\python313\site-packages (from matminer) (1.18.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: joblib>=1.2.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: dnspython<3.0.0,>=2.7.0 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymongo~=4.5->matminer) (2.8.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.23.0->mp-api) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.23.0->mp-api) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.23.0->mp-api) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.23.0->mp-api) (2025.11.12)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\programdata\anaconda3\lib\site-packages (from sympy~=1.11->matminer) (1.3.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from tqdm~=4.66->matminer) (0.4.6)
Requirement already satisfied: wrapt<3,>=1.10 in c:\programdata\anaconda3\lib\site-packages (from deprecated>=1.2.18->deltalake<1.6.0,>=1.4.0->mp-api) (1.17.0)
Requirement already satisfied: pydantic>=2.12 in c:\programdata\anaconda3\lib\site-packages (from emmet-core>=0.87.1->mp-api) (2.12.4)
Requirement already satisfied: pydantic-settings>=2.0 in c:\programdata\anaconda3\lib\site-packages (from emmet-core>=0.87.1->mp-api) (2.12.0)
Requirement already satisfied: pymatgen-io-validation>=0.1.1 in c:\users\admin\appdata\roaming\python\python313\site-packages (from emmet-core>=0.87.1->mp-api) (0.1.4)
Requirement already satisfied: pybtex~=0.24 in c:\users\admin\appdata\roaming\python\python313\site-packages (from emmet-core>=0.87.1->mp-api) (0.26.1)
Requirement already satisfied: blake3 in c:\users\admin\appdata\roaming\python\python313\site-packages (from emmet-core>=0.87.1->mp-api) (1.0.9)
Requirement already satisfied: inflect in c:\users\admin\appdata\roaming\python\python313\site-packages (from emmet-core>=0.87.1->mp-api) (7.5.0)
Requirement already satisfied: pubchempy in c:\users\admin\appdata\roaming\python\python313\site-packages (from emmet-core>=0.87.1->mp-api) (1.0.5)
Requirement already satisfied: latexcodec>=1.0.4 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pybtex~=0.24->emmet-core>=0.87.1->mp-api) (3.0.1)
Requirement already satisfied: pyyaml>=3.01 in c:\programdata\anaconda3\lib\site-packages (from pybtex~=0.24->emmet-core>=0.87.1->mp-api) (6.0.3)
Requirement already satisfied: ruamel.yaml in c:\programdata\anaconda3\lib\site-packages (from monty>=2024.12.10->mp-api) (0.18.16)
Requirement already satisfied: annotated-types>=0.6.0 in c:\programdata\anaconda3\lib\site-packages (from pydantic>=2.12->emmet-core>=0.87.1->mp-api) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\programdata\anaconda3\lib\site-packages (from pydantic>=2.12->emmet-core>=0.87.1->mp-api) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\programdata\anaconda3\lib\site-packages (from pydantic>=2.12->emmet-core>=0.87.1->mp-api) (0.4.2)
Requirement already satisfied: bibtexparser<2,>=1 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (1.4.4)
Requirement already satisfied: lxml>=6.1.0 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (6.1.3)
Requirement already satisfied: matplotlib>=3.8 in c:\programdata\anaconda3\lib\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (3.10.6)
Requirement already satisfied: networkx>=2.7 in c:\programdata\anaconda3\lib\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (3.5)
Requirement already satisfied: palettable>=3.3.3 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (3.3.3)
Requirement already satisfied: plotly>=5.0 in c:\programdata\anaconda3\lib\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (6.3.0)
Requirement already satisfied: spglib>=2.5 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (2.7.0)
Requirement already satisfied: tabulate>=0.9.0 in c:\programdata\anaconda3\lib\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (0.9.0)
Requirement already satisfied: uncertainties>=3.1 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (3.2.3)
Requirement already satisfied: pyparsing>=2.0.3 in c:\programdata\anaconda3\lib\site-packages (from bibtexparser<2,>=1->pymatgen-core>=2026.9.23->pymatgen) (3.2.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.8->pymatgen-core>=2026.9.23->pymatgen) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.8->pymatgen-core>=2026.9.23->pymatgen) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.8->pymatgen-core>=2026.9.23->pymatgen) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.8->pymatgen-core>=2026.9.23->pymatgen) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.8->pymatgen-core>=2026.9.23->pymatgen) (25.0)
Requirement already satisfied: pillow>=8 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.8->pymatgen-core>=2026.9.23->pymatgen) (12.0.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\programdata\anaconda3\lib\site-packages (from plotly>=5.0->pymatgen-core>=2026.9.23->pymatgen) (2.7.0)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: botocore<1.44.0,>=1.43.100 in c:\users\admin\appdata\roaming\python\python313\site-packages (from boto3->mp-api) (1.43.100)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\programdata\anaconda3\lib\site-packages (from boto3->mp-api) (1.0.1)
Requirement already satisfied: s3transfer<0.20.0,>=0.19.0 in c:\users\admin\appdata\roaming\python\python313\site-packages (from boto3->mp-api) (0.19.2)
Requirement already satisfied: more_itertools>=8.5.0 in c:\programdata\anaconda3\lib\site-packages (from inflect->emmet-core>=0.87.1->mp-api) (10.8.0)
Requirement already satisfied: typeguard>=4.0.1 in c:\users\admin\appdata\roaming\python\python313\site-packages (from inflect->emmet-core>=0.87.1->mp-api) (4.6.0)
Requirement already satisfied: ruamel.yaml.clib>=0.2.7 in c:\programdata\anaconda3\lib\site-packages (from ruamel.yaml->monty>=2024.12.10->mp-api) (0.2.14)

In [ ]:
from mp_api.client import MPRester

API_KEY = "6tdXwnFyRXHQH4fa8mlEpalFYd7QGZ4E"

with MPRester(API_KEY) as mpr:
    docs = mpr.materials.summary.search(
        material_ids=["mp-22526"],
        fields=["material_id", "formula_pretty"]
    )

for doc in docs:
    print(doc.material_id)
    print(doc.formula_pretty)

In [ ]:
from matminer.utils.data import MagpieData

magpie = MagpieData()

properties = magpie.get_elemental_properties()

print("Number of available Magpie properties:", len(properties))

for p in properties:
    print(p)

In [ ]:
import pandas as pd
import numpy as np

from mp_api.client import MPRester
from matminer.utils.data import MagpieData

print("Libraries imported successfully!")

In [ ]:
with MPRester(API_KEY) as mpr:
    docs = mpr.materials.summary.search(
        material_ids=["mp-22526"],
        fields=["material_id", "formula_pretty"]
    )

for doc in docs:
    print("Material ID:", doc.material_id)
    print("Formula:", doc.formula_pretty)

In [ ]:
from matminer.utils.data import MagpieData

magpie = MagpieData()

print(type(magpie))

In [ ]:
print(dir(magpie))

In [ ]:
print(magpie.__dict__.keys())

In [ ]:
help(magpie.get_elemental_properties)

In [ ]:
magpie_properties = magpie.all_elemental_props

print("Number of Magpie properties:", len(magpie_properties))

for i, prop in enumerate(magpie_properties, start=1):
    print(i, prop)

In [ ]:
# Print the Magpie properties in a clean numbered list

for i, prop in enumerate(magpie_properties, start=1):
    print(f"{i:3}. {prop}")

In [ ]:
# Search Magpie properties for anything related to BCC, lattice, or Fermi

keywords = ["BCC", "bcc", "lattice", "Fermi", "fermi"]

for prop in magpie_properties:
    if any(keyword in prop for keyword in keywords):
        print(prop)

In [ ]:
missing_features = [
    "BCC energy difference",
    "BCC effective lattice constant",
    "BCC Fermi",
    "BCC magnetic moment",
    "BCC volume per atom difference",
    "BCC volume per atom",
    "GS effective lattice constant"
]

print("Features not found in current Magpie:")
for feature in missing_features:
    print("❌", feature)

In [ ]:
# Test extracting all 37 available Magpie properties for one element

element = "Li"

available_properties = [
    "AtomicVolume",
    "Number",
    "AtomicWeight",
    "CovalentRadius",
    "OxidationStates",
    "BoilingT",
    "Column",
    "Row",
    "FirstIonizationEnergy",
    "SpaceGroupNumber",
    "Density",
    "MendeleevNumber",
    "ICSDVolume",
    "Polarizability",
    "HeatCapacityMass",
    "HeatCapacityMolar",
    "GSbandgap",
    "GSestBCClatcnt",
    "GSestFCClatcnt",
    "GSmagmom",
    "GSvolume_pa",
    "IsMetal",
    "IsNonmetal",
    "IsMetalloid",
    "IsAlkali",
    "IsDBlock",
    "IsFBlock",
    "NValence",
    "NUnfilled",
    "NsValence",
    "NdUnfilled",
    "NdValence",
    "NfUnfilled",
    "NfValence",
    "NpValence",
    "NsUnfilled",
    "NpUnfilled"
]

for prop in available_properties:
    try:
        value = magpie.get_elemental_properties(["Li"], prop)[0]
        print(f"{prop:30} = {value}")
    except Exception as e:
        print(f"{prop:30} = ERROR: {e}")

In [ ]:
from pymatgen.core import Element
element = Element("Li")

value = magpie.get_elemental_properties(
    [element],
    "AtomicVolume"
)

print(value)

In [ ]:
element = Element("Li")

for prop in available_properties:
    try:
        value = magpie.get_elemental_properties(
            [element],
            prop
        )[0]
        print(f"{prop:30} = {value}")
    except Exception as e:
        print(f"{prop:30} = ERROR: {e}")

In [ ]:
from pymatgen.core import Element

test_elements = ["Li", "Na", "Co", "O", "C"]

for symbol in test_elements:
    element = Element(symbol)

    print(f"\n===== {symbol} =====")

    for prop in available_properties:
        try:
            value = magpie.get_elemental_properties(
                [element],
                prop
            )[0]

            print(f"{prop:30} = {value}")

        except Exception as e:
            print(f"{prop:30} = ERROR: {e}")

In [2]:
import requests

url = "https://api.github.com/repos/nissy-dev/machine-learning-the-voltage-of-electrode-materials/contents/dataset"

response = requests.get(url)

print("Status:", response.status_code)

for item in response.json():
    print(item["name"], "→", item["type"])

Status: 200
README.md → file
element_data → dir
mp_data → dir

In [3]:
import requests

url = "https://api.github.com/repos/nissy-dev/machine-learning-the-voltage-of-electrode-materials/contents/dataset/mp_data"

response = requests.get(url)

print("Status:", response.status_code)

for item in response.json():
    print(item["name"], "→", item["type"])

Status: 200
data_2019_12_03.csv → file
data_2019_12_03.h5 → file

In [4]:
import pandas as pd
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/nissy-dev/machine-learning-the-voltage-of-electrode-materials/master/dataset/mp_data/data_2019_12_03.csv"

response = requests.get(url)

print("Status:", response.status_code)

mp_df = pd.read_csv(StringIO(response.text))

print("Shape:", mp_df.shape)
print("\nColumns:")
for i, col in enumerate(mp_df.columns, start=1):
    print(i, "→", col)

Status: 200
Shape: (5133, 15)

Columns:
1 → Unnamed: 0
2 → battery_id
3 → formula_charge
4 → id_charge
5 → stability_charge
6 → formula_discharge
7 → id_discharge
8 → stability_discharge
9 → average_voltage
10 → capacity_grav
11 → capacity_vol
12 → energy_grav
13 → energy_vol
14 → max_delta_volume
15 → working_ion

In [5]:
print(mp_df.head(10).to_string())

print("\nMissing values:")
print(mp_df.isna().sum())

print("\nWorking ions:")
print(mp_df["working_ion"].value_counts(dropna=False))

print("\nUnique battery IDs:", mp_df["battery_id"].nunique())

print("\nUnique charge materials:", mp_df["id_charge"].nunique())
print("Unique discharge materials:", mp_df["id_discharge"].nunique())

   Unnamed: 0     battery_id formula_charge   id_charge  stability_charge formula_discharge id_discharge  stability_discharge  average_voltage  capacity_grav  capacity_vol  energy_grav   energy_vol  max_delta_volume working_ion
0           0   mp-504791_Li        P(WO4)2    mp-28000          0.000000         LiP(WO4)2    mp-757610             0.037837         2.325185      50.228609    269.262771   116.790816   626.085802          0.028564          Li
1           1   mp-763480_Li        P3W2O13   mp-757302          0.000097         LiP3W2O13    mp-758455             0.039966         3.291748      39.674483    154.215698   130.598387   507.639167          0.017562          Li
2           2  mp-1176966_Li        P8W3O29   mp-776468          0.061321        Li2P8W3O29    mp-776995             0.025051         5.062579      41.969954    142.111725   212.476221   719.451888          0.061034          Li
3           3  mp-1176966_Li     Li2P8W3O29   mp-776995          0.025051        Li6P8W3O29   mp-1176966             0.029375         3.595344      82.153994    291.921377   295.371876  1049.557797          0.027084          Li
4           4  mp-1176966_Li     Li6P8W3O29  mp-1176966          0.029375        Li9P8W3O29    mp-776590             0.025606         2.660169      60.647735    217.236232   161.333195   577.884983          0.007848          Li
5           5    mvc-5592_Li          P2WO7    mvc-5592          0.111249           LiP2WO7    mp-753180             0.049028         3.201169      73.484217    329.726946   235.235410  1055.511733          0.021096          Li
6           6   mp-763566_Li          P2WO7   mp-755995          0.000000           LiP2WO7    mp-752528             0.017244         2.438309      73.484217    306.081406   179.177232   746.321063          0.025349          Li
7           7   mp-761353_Li         P4WO13   mp-752714          0.052661          LiP4WO13    mp-757168             0.004088         5.232440      51.278189    154.954196   268.310040   810.788504          0.020360          Li
8           8   mp-761353_Li       LiP4WO13   mp-757168          0.004088         Li2P4WO13    mp-757625             0.049896         3.414315      50.606143    162.046049   172.785323   553.276289          0.045767          Li
9           9   mp-763403_Li         P4WO13   mp-766131          0.047858          LiP4WO13    mp-758454             0.000706         5.210250      51.278189    174.707261   267.172208   910.268584          0.015962          Li

Missing values:
Unnamed: 0             0
battery_id             0
formula_charge         0
id_charge              0
stability_charge       0
formula_discharge      0
id_discharge           0
stability_discharge    0
average_voltage        0
capacity_grav          0
capacity_vol           0
energy_grav            0
energy_vol             0
max_delta_volume       0
working_ion            0
dtype: int64

Working ions:
working_ion
Li    2847
Ca     525
Mg     410
Zn     396
Na     388
Y      167
Al     163
K      144
Rb      53
Cs      40
Name: count, dtype: int64

Unique battery IDs: 4379

Unique charge materials: 3968
Unique discharge materials: 5127

In [6]:
import requests

url = "https://api.github.com/repos/nissy-dev/machine-learning-the-voltage-of-electrode-materials/contents/preprocess"

response = requests.get(url)

print("Status:", response.status_code)

for item in response.json():
    print(item["name"], "→", item["type"])

Status: 200
README.md → file
create_features.py → file
utils.py → file

In [7]:
import requests

url = "https://raw.githubusercontent.com/nissy-dev/machine-learning-the-voltage-of-electrode-materials/master/preprocess/create_features.py"

response = requests.get(url)

print("Status:", response.status_code)
print(response.text)

Status: 200
import h5py
import json
import argparse
import numpy as np
import pandas as pd
from tqdm import tqdm
from datetime import datetime
from os import path, makedirs, getcwd
from pymatgen.core import Composition, Element, Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

from utils import NUM_OF_FEATURE, ElementDataSingleton, create_feature_from_formula, \
    create_feature_from_wokring_ion, create_feature_from_crystal_system


def parse_arguments():
    # Set up the argument parser.
    parser = argparse.ArgumentParser(description='Create features')

    parser.add_argument('--element-data', '-ed', type=str, default='../dataset/element_data',
                        help='path of element data directory')
    parser.add_argument('--battery-data', '-bd', type=str, default='../dataset/mp_data/data_2019_12_03.csv',
                        help='path of battery csv data')
    parser.add_argument('--cif-data', type=str, default='../dataset/mp_data/data_2019_12_03.h5',
                        help='path to cif data (relative path)')
    parser.add_argument('--out', '-o', type=str, default='../dataset/feature',
                        help='directory path to save feature data')
    return parser.parse_args()


if __name__ == '__main__':
    # Parse the arguments.
    args = parse_arguments()

    # create save path
    target_dir = args.out
    out_dir_path = path.normpath(path.join(getcwd(), target_dir))
    makedirs(out_dir_path, exist_ok=True)
    time = datetime.now().strftime("%Y_%m_%d")
    out_csv_path = path.join(out_dir_path, "repro_features_" + time + ".csv")
    # save the parameter
    with open(path.join(out_dir_path, 'params.json'), mode="w") as f:
        json.dump(args.__dict__, f, indent=4)

    # load data
    cif_path = path.normpath(path.join(getcwd(), args.cif_data))
    cif_data = h5py.File(cif_path, "r")
    battery_table = pd.read_csv(args.battery_data, index_col=False)
    element_data = ElementDataSingleton.get_instance(element_data_path=args.element_data)

    # create features
    features = np.zeros((len(battery_table), NUM_OF_FEATURE))
    for i, (id_charge, id_discharge, ion) in tqdm(enumerate(zip(battery_table['id_charge'],
                                                                battery_table['id_discharge'],
                                                                battery_table['working_ion']))):

        # load crystal object from cif
        charge_crystal = Structure.from_str(cif_data[id_charge].value, 'cif')
        discharge_crystal = Structure.from_str(cif_data[id_discharge].value, 'cif')

        # specific features
        finder = SpacegroupAnalyzer(charge_crystal)
        space_group_feat = np.array([finder.get_space_group_number()])
        crystal_system_feat = create_feature_from_crystal_system(finder.get_crystal_system())
        ion_feat = create_feature_from_wokring_ion(ion)
        dischr_comp = Composition(discharge_crystal.formula)
        ion_concentrate = np.array([dischr_comp.get_atomic_fraction(Element(ion))])

        # calculate features from element property
        charge_formula = charge_crystal.formula
        discharge_formula = discharge_crystal.formula
        feature_from_chr_formula = create_feature_from_formula(charge_formula, element_data)
        feature_from_dischr_formula = create_feature_from_formula(discharge_formula, element_data)
        feature_from_ion = create_feature_from_formula(ion, element_data)

        # if charge_formula is a single element
        if feature_from_chr_formula.shape[0] == 44:
            feature_from_chr_formula = np.concatenate([feature_from_chr_formula, np.zeros(44)])

        # concate all features
        features[i] = np.concatenate([space_group_feat, crystal_system_feat, ion_feat, ion_concentrate,
                                      feature_from_chr_formula, feature_from_dischr_formula, feature_from_ion])

    df = pd.DataFrame(data=features,
                      columns=['feat_{}'.format(i+1) for i in range(239)])
    df.to_csv(out_csv_path)

In [8]:
url = "https://raw.githubusercontent.com/nissy-dev/machine-learning-the-voltage-of-electrode-materials/master/preprocess/utils.py"

response = requests.get(url)

print("Status:", response.status_code)
print(response.text)

Status: 200
import numpy as np
from os import path, linesep
from pymatgen.core import Composition, Element


NUM_OF_FEATURE = 239

COLUMNS = [
    'AtimicNumber',
    'AtomicVolume',
    'AtomicWeight',
    'BCCefflatcnt',
    'BCCenergydiff',
    'BCCfermi',
    'BCCmagmom',
    'BCCvolume_pa',
    'BCCvolume_padiff',
    'BoilingT',
    'ColumnNumber',
    'CovalentRadius',
    'Density',
    'FirstIonizationEnergy',
    'GSbandgap',
    'GSefflatcnt',
    'GSestBCClatcnt',
    'GSestFCClatcnt',
    'GSmagmom',
    'GSvolume_pa',
    'HeatCapacityMass',
    'HeatCapacityMolar',
    'ICSDVolume',
    'IsAlkali',
    'IsDBlock',
    'IsFBlock',
    'IsMetal',
    'IsMetalloid',
    'IsNonmetal',
    'MendeleevNumber',
    'NUnfilled',
    'NValance',
    'NdUnfilled',
    'NdValence',
    'NfUnfilled',
    'NfValence',
    'NpUnfilled',
    'NpValence',
    'NsUnfilled',
    'NsValence',
    'OxidationStates',
    'Polarizability',
    'RowNumber',
    'SpaceGroupNumber',
]


class ElementDataSingleton:

    _element_data_instance = None

    @classmethod
    def get_instance(self, element_data_path, columns=COLUMNS):
        if not self._element_data_instance:
            self._element_data_instance = {}
            # store element_data
            for col in columns:
                element_data = None
                with open(path.join(element_data_path, col + '.table'), 'r') as f:
                    if col != 'OxidationStates':
                        element_data = [0 if line.rstrip(linesep) == 'Missing' or line.rstrip(linesep) == ''
                                        else float(line) for line in f.readlines()]

                self._element_data_instance[col] = element_data

        return self._element_data_instance


def create_feature_from_formula(formula, element_data, columns=COLUMNS):
    comp = Composition(formula)
    num_of_base_feat = 44

    if len(comp) == 1:
        features = np.zeros(num_of_base_feat)
        ele = comp.elements[0]
        for i, col in enumerate(columns):
            if col != 'OxidationStates':
                features[i] = element_data[col][ele.number - 1]
            else:
                # FIXME: I don't understand how to treat `OxidationStates` data
                features[i] = 0
    else:
        weighted_mean_feat = np.zeros(num_of_base_feat)
        mean_deviation_feat = np.zeros(num_of_base_feat)
        element_dict = comp.to_reduced_dict

        tot_ratio = sum(element_dict.values())
        for i, col in enumerate(columns):
            if col != 'OxidationStates':
                tmp_mean_feat = 0.0
                for element_str, comp_ratio in element_dict.items():
                    ele = Element(element_str)
                    tmp_mean_feat += element_data[col][ele.number - 1] * comp_ratio

                mean_feat = tmp_mean_feat / tot_ratio
                weighted_mean_feat[i] = mean_feat

                tmp_deviation_feat = 0.0
                for element_str, comp_ratio in element_dict.items():
                    ele = Element(element_str)
                    tmp_deviation_feat += abs(element_data[col][ele.number - 1] - mean_feat) * comp_ratio

                deviation_feat = tmp_deviation_feat / tot_ratio
                mean_deviation_feat[i] = deviation_feat
            else:
                # FIXME: I don't understand how to treat `OxidationStates` data
                mean_feat = 0.0
                deviation_feat = 0.0
                weighted_mean_feat[i] = mean_feat
                mean_deviation_feat[i] = deviation_feat

        features = np.concatenate([weighted_mean_feat, mean_deviation_feat])

    return features


def create_feature_from_wokring_ion(ion):
    feature = np.zeros(10)
    if ion == 'Li':
        feature[0] = 1.0
    elif ion == 'Ca':
        feature[1] = 1.0
    elif ion == 'Cs':
        feature[2] = 1.0
    elif ion == 'Rb':
        feature[3] = 1.0
    elif ion == 'K':
        feature[4] = 1.0
    elif ion == 'Y':
        feature[5] = 1.0
    elif ion == 'Na':
        feature[6] = 1.0
    elif ion == 'Al':
        feature[7] = 1.0
    elif ion == 'Zn':
        feature[8] = 1.0
    elif ion == 'Mg':
        feature[9] = 1.0

    return feature


def create_feature_from_crystal_system(crystal_system):
    feature = np.zeros(7)
    if crystal_system == 'triclinic':
        feature[0] = 1.0
    elif crystal_system == 'monoclinic':
        feature[1] = 1.0
    elif crystal_system == 'orthorhombic':
        feature[2] = 1.0
    elif crystal_system == 'tetragonal':
        feature[3] = 1.0
    elif crystal_system == 'trigonal':
        feature[4] = 1.0
    elif crystal_system == 'hexagonal':
        feature[5] = 1.0
    elif crystal_system == 'cubic':
        feature[6] = 1.0

    return feature

In [9]:
import requests

url = "https://api.github.com/repos/nissy-dev/machine-learning-the-voltage-of-electrode-materials/contents/dataset/element_data"

response = requests.get(url)

print("Status:", response.status_code)

for item in response.json():
    print(item["name"])

Status: 200
AtimicNumber.table
AtomicVolume.table
AtomicWeight.table
BCCefflatcnt.table
BCCenergydiff.table
BCCfermi.table
BCCmagmom.table
BCCvolume_pa.table
BCCvolume_padiff.table
BoilingT.table
ColumnNumber.table
CovalentRadius.table
Density.table
FirstIonizationEnergy.table
GSbandgap.table
GSefflatcnt.table
GSestBCClatcnt.table
GSestFCClatcnt.table
GSmagmom.table
GSvolume_pa.table
HeatCapacityMass.table
HeatCapacityMolar.table
ICSDVolume.table
IsAlkali.table
IsDBlock.table
IsFBlock.table
IsMetal.table
IsMetalloid.table
IsNonmetal.table
MendeleevNumber.table
NUnfilled.table
NValance.table
NdUnfilled.table
NdValence.table
NfUnfilled.table
NfValence.table
NpUnfilled.table
NpValence.table
NsUnfilled.table
NsValence.table
OxidationStates.table
Polarizability.table
RowNumber.table
SpaceGroupNumber.table

In [ ]:
import os
import requests

base_url = "https://raw.githubusercontent.com/nissy-dev/machine-learning-the-voltage-of-electrode-materials/master/dataset/element_data/"

element_files = [
    "AtimicNumber.table",
    "AtomicVolume.table",
    "AtomicWeight.table",
    "BCCefflatcnt.table",
    "BCCenergydiff.table",
    "BCCfermi.table",
    "BCCmagmom.table",
    "BCCvolume_pa.table",
    "BCCvolume_padiff.table",
    "BoilingT.table",
    "ColumnNumber.table",
    "CovalentRadius.table",
    "Density.table",
    "FirstIonizationEnergy.table",
    "GSbandgap.table",
    "GSefflatcnt.table",
    "GSestBCClatcnt.table",
    "GSestFCClatcnt.table",
    "GSmagmom.table",
    "GSvolume_pa.table",
    "HeatCapacityMass.table",
    "HeatCapacityMolar.table",
    "ICSDVolume.table",
    "IsAlkali.table",
    "IsDBlock.table",
    "IsFBlock.table",
    "IsMetal.table",
    "IsMetalloid.table",
    "IsNonmetal.table",
    "MendeleevNumber.table",
    "NUnfilled.table",
    "NValance.table",
    "NdUnfilled.table",
    "NdValence.table",
    "NfUnfilled.table",
    "NfValence.table",
    "NpUnfilled.table",
    "NpValence.table",
    "NsUnfilled.table",
    "NsValence.table",
    "OxidationStates.table",
    "Polarizability.table",
    "RowNumber.table",
    "SpaceGroupNumber.table"
]

os.makedirs("element_data", exist_ok=True)

for filename in element_files:
    url = base_url + filename
    response = requests.get(url)

    if response.status_code == 200:
        with open(os.path.join("element_data", filename), "wb") as f:
            f.write(response.content)
        print("Downloaded:", filename)
    else:
        print("FAILED:", filename, response.status_code)

print("\nFinished.")

In [ ]:
import requests

url = "https://raw.githubusercontent.com/nissy-dev/machine-learning-the-voltage-of-electrode-materials/master/dataset/mp_data/data_2019_12_03.h5"

response = requests.get(url)

print("Status:", response.status_code)
print("File size:", len(response.content) / (1024**2), "MB")

with open("data_2019_12_03.h5", "wb") as f:
    f.write(response.content)

print("Downloaded successfully.")

In [ ]:
import h5py

h5_path = "data_2019_12_03.h5"

with h5py.File(h5_path, "r") as f:
    h5_ids = set(f.keys())

charge_ids = set(mp_df["id_charge"])
discharge_ids = set(mp_df["id_discharge"])

missing_charge = charge_ids - h5_ids
missing_discharge = discharge_ids - h5_ids

print("Charge IDs:", len(charge_ids))
print("Discharge IDs:", len(discharge_ids))

print("Missing charge structures:", len(missing_charge))
print("Missing discharge structures:", len(missing_discharge))

if missing_charge:
    print("Example missing charge IDs:", list(missing_charge)[:10])

if missing_discharge:
    print("Example missing discharge IDs:", list(missing_discharge)[:10])

In [10]:
!pip install pymatgen h5py pandas numpy tqdm

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymatgen in c:\users\admin\appdata\roaming\python\python313\site-packages (2026.9.24)
Requirement already satisfied: h5py in c:\programdata\anaconda3\lib\site-packages (3.15.1)
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (2.3.5)
Requirement already satisfied: tqdm in c:\users\admin\appdata\roaming\python\python313\site-packages (4.70.1)
Requirement already satisfied: pymatgen-core>=2026.9.23 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymatgen) (2026.9.23)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from tqdm) (0.4.6)
Requirement already satisfied: bibtexparser<2,>=1 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (1.4.4)
Requirement already satisfied: joblib>=1.3.2 in c:\programdata\anaconda3\lib\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (1.5.2)
Requirement already satisfied: lxml>=6.1.0 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (6.1.3)
Requirement already satisfied: matplotlib>=3.8 in c:\programdata\anaconda3\lib\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (3.10.6)
Requirement already satisfied: monty>=2026.7.16 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (2026.7.16)
Requirement already satisfied: networkx>=2.7 in c:\programdata\anaconda3\lib\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (3.5)
Requirement already satisfied: orjson<4,>=3.10 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (3.12.0)
Requirement already satisfied: palettable>=3.3.3 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (3.3.3)
Requirement already satisfied: plotly>=5.0 in c:\programdata\anaconda3\lib\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (6.3.0)
Requirement already satisfied: requests>=2.32.5 in c:\programdata\anaconda3\lib\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (2.32.5)
Requirement already satisfied: scipy>=1.13.0 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (1.18.1)
Requirement already satisfied: spglib>=2.5 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (2.7.0)
Requirement already satisfied: sympy>=1.3 in c:\programdata\anaconda3\lib\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (1.14.0)
Requirement already satisfied: tabulate>=0.9.0 in c:\programdata\anaconda3\lib\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (0.9.0)
Requirement already satisfied: uncertainties>=3.1 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (3.2.3)
Requirement already satisfied: pyparsing>=2.0.3 in c:\programdata\anaconda3\lib\site-packages (from bibtexparser<2,>=1->pymatgen-core>=2026.9.23->pymatgen) (3.2.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.8->pymatgen-core>=2026.9.23->pymatgen) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.8->pymatgen-core>=2026.9.23->pymatgen) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.8->pymatgen-core>=2026.9.23->pymatgen) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.8->pymatgen-core>=2026.9.23->pymatgen) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.8->pymatgen-core>=2026.9.23->pymatgen) (25.0)
Requirement already satisfied: pillow>=8 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.8->pymatgen-core>=2026.9.23->pymatgen) (12.0.0)
Requirement already satisfied: ruamel.yaml in c:\programdata\anaconda3\lib\site-packages (from monty>=2026.7.16->pymatgen-core>=2026.9.23->pymatgen) (0.18.16)
Requirement already satisfied: narwhals>=1.15.1 in c:\programdata\anaconda3\lib\site-packages (from plotly>=5.0->pymatgen-core>=2026.9.23->pymatgen) (2.7.0)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.32.5->pymatgen-core>=2026.9.23->pymatgen) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.32.5->pymatgen-core>=2026.9.23->pymatgen) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.32.5->pymatgen-core>=2026.9.23->pymatgen) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.32.5->pymatgen-core>=2026.9.23->pymatgen) (2025.11.12)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\programdata\anaconda3\lib\site-packages (from sympy>=1.3->pymatgen-core>=2026.9.23->pymatgen) (1.3.0)
Requirement already satisfied: ruamel.yaml.clib>=0.2.7 in c:\programdata\anaconda3\lib\site-packages (from ruamel.yaml->monty>=2026.7.16->pymatgen-core>=2026.9.23->pymatgen) (0.2.14)

In [11]:
%cd preprocess

!python create_features.py \
    --element-data ../element_data \
    --battery-data ../dataset/mp_data/data_2019_12_03.csv \
    --cif-data ../dataset/mp_data/data_2019_12_03.h5 \
    --out ../dataset/feature

C:\Users\ADMIN\Desktop\PS PROJECT\PS 2-1 CRYSTAL DOMAIN\PROJECT\PROGRAM\preprocess

Traceback (most recent call last):
  File "C:\Users\ADMIN\Desktop\PS PROJECT\PS 2-1 CRYSTAL DOMAIN\PROJECT\PROGRAM\preprocess\create_features.py", line 47, in <module>
    cif_data = h5py.File(cif_path, "r")
  File "C:\ProgramData\anaconda3\Lib\site-packages\h5py\_hl\files.py", line 566, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "C:\ProgramData\anaconda3\Lib\site-packages\h5py\_hl\files.py", line 241, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 104, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'C:\Users\ADMIN\Desktop\PS PROJECT\PS 2-1 CRYSTAL DOMAIN\PROJECT\PROGRAM\dataset\mp_data\data_2019_12_03.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

In [12]:
import os
import requests

os.makedirs("preprocess", exist_ok=True)

files = {
    "create_features.py":
        "https://raw.githubusercontent.com/nissy-dev/machine-learning-the-voltage-of-electrode-materials/master/preprocess/create_features.py",

    "utils.py":
        "https://raw.githubusercontent.com/nissy-dev/machine-learning-the-voltage-of-electrode-materials/master/preprocess/utils.py"
}

for filename, url in files.items():
    response = requests.get(url)
    response.raise_for_status()

    with open(os.path.join("preprocess", filename), "wb") as f:
        f.write(response.content)

    print("Downloaded:", filename)

print("\nPreprocess folder created successfully.")

Downloaded: create_features.py
Downloaded: utils.py

Preprocess folder created successfully.

In [13]:
import os

for root, dirs, files in os.walk("."):
    level = root.count(os.sep)
    if level <= 2:
        print("  " * level + root)
        for file in files:
            print("  " * (level + 1) + file)

.
  create_features.py
  utils.py
  .\.ipynb_checkpoints
    create_features-checkpoint.py
  .\preprocess
    create_features.py
    utils.py
  .\__pycache__
    utils.cpython-313.pyc

In [ ]:
!python preprocess/create_features.py ^--element-data element_data ^--battery-data dataset/mp_data/data_2019_12_03.csv ^--cif-data dataset/mp_data/data_2019_12_03.h5 ^--out dataset/feature

In [ ]:
!python create_features.py --element-data ../element_data --battery-data ../dataset/mp_data/data_2019_12_03.csv --cif-data ../dataset/mp_data/data_2019_12_03.h5 --out ../dataset/feature

In [ ]:
!python create_features.py --element-data ../element_data --battery-data ../dataset/mp_data/data_2019_12_03.csv --cif-data ../data_2019_12_03.h5 --out ../dataset/feature

In [14]:
import os

for root, dirs, files in os.walk(".."):
    for file in files:
        if file.lower().endswith(".h5"):
            print(os.path.abspath(os.path.join(root, file)))

C:\Users\ADMIN\Desktop\PS PROJECT\PS 2-1 CRYSTAL DOMAIN\PROJECT\PROGRAM\data_2019_12_03.h5

In [ ]:
!python create_features.py --element-data ../element_data --battery-data ../dataset/mp_data/data_2019_12_03.csv --cif-data ../data_2019_12_03.h5 --out ../dataset/feature

In [15]:
import os

for root, dirs, files in os.walk(".."):
    for file in files:
        if file.lower().endswith(".csv"):
            print(os.path.abspath(os.path.join(root, file)))

C:\Users\ADMIN\Desktop\PS PROJECT\PS 2-1 CRYSTAL DOMAIN\PROJECT\PROGRAM\dataset\feature\repro_features_2026_09_30.csv
C:\Users\ADMIN\Desktop\PS PROJECT\PS 2-1 CRYSTAL DOMAIN\PROJECT\PROGRAM\dataset\feature\.ipynb_checkpoints\repro_features_2026_09_30-checkpoint.csv
C:\Users\ADMIN\Desktop\PS PROJECT\PS 2-1 CRYSTAL DOMAIN\PROJECT\PROGRAM\dataset\mp_data\data_2019_12_03.csv
C:\Users\ADMIN\Desktop\PS PROJECT\PS 2-1 CRYSTAL DOMAIN\PROJECT\PROGRAM\dataset\mp_data\.ipynb_checkpoints\data_2019_12_03-checkpoint.csv

In [16]:
print(os.path.abspath("../data_2019_12_03.h5"))
print(os.path.exists("../data_2019_12_03.h5"))

C:\Users\ADMIN\Desktop\PS PROJECT\PS 2-1 CRYSTAL DOMAIN\PROJECT\PROGRAM\data_2019_12_03.h5
True

In [18]:
import os
import requests

os.makedirs("../dataset/mp_data", exist_ok=True)

url = "https://raw.githubusercontent.com/nissy-dev/machine-learning-the-voltage-of-electrode-materials/master/dataset/mp_data/data_2019_12_03.csv"

response = requests.get(url)
response.raise_for_status()

csv_path = "../dataset/mp_data/data_2019_12_03.csv"

with open(csv_path, "wb") as f:
    f.write(response.content)

print("CSV downloaded successfully!")
print("Location:", os.path.abspath(csv_path))
print("Size:", os.path.getsize(csv_path), "bytes")

CSV downloaded successfully!
Location: C:\Users\ADMIN\Desktop\PS PROJECT\PS 2-1 CRYSTAL DOMAIN\PROJECT\PROGRAM\dataset\mp_data\data_2019_12_03.csv
Size: 1082752 bytes

In [19]:
import pandas as pd

df = pd.read_csv("../dataset/mp_data/data_2019_12_03.csv")

print("Shape:", df.shape)
print(df.head())

Shape: (5133, 15)
   Unnamed: 0     battery_id formula_charge   id_charge  stability_charge  \
0           0   mp-504791_Li        P(WO4)2    mp-28000          0.000000
1           1   mp-763480_Li        P3W2O13   mp-757302          0.000097
2           2  mp-1176966_Li        P8W3O29   mp-776468          0.061321
3           3  mp-1176966_Li     Li2P8W3O29   mp-776995          0.025051
4           4  mp-1176966_Li     Li6P8W3O29  mp-1176966          0.029375

  formula_discharge id_discharge  stability_discharge  average_voltage  \
0         LiP(WO4)2    mp-757610             0.037837         2.325185
1         LiP3W2O13    mp-758455             0.039966         3.291748
2        Li2P8W3O29    mp-776995             0.025051         5.062579
3        Li6P8W3O29   mp-1176966             0.029375         3.595344
4        Li9P8W3O29    mp-776590             0.025606         2.660169

   capacity_grav  capacity_vol  energy_grav   energy_vol  max_delta_volume  \
0      50.228609    269.262771   116.790816   626.085802          0.028564
1      39.674483    154.215698   130.598387   507.639167          0.017562
2      41.969954    142.111725   212.476221   719.451888          0.061034
3      82.153994    291.921377   295.371876  1049.557797          0.027084
4      60.647735    217.236232   161.333195   577.884983          0.007848

  working_ion
0          Li
1          Li
2          Li
3          Li
4          Li

In [23]:
!python create_features.py --element-data ../element_data --battery-data ../dataset/mp_data/data_2019_12_03.csv --cif-data ../data_2019_12_03.h5 --out ../dataset/feature

0it [00:00, ?it/s]C:\Users\ADMIN\Desktop\PS PROJECT\PS 2-1 CRYSTAL DOMAIN\PROJECT\PROGRAM\preprocess\utils.py:93: FutureWarning: to_reduced_dict is deprecated, and will be removed on 2026-04-04
Use as_reduced_dict in pymatgen.core.composition instead.
  element_dict = comp.to_reduced_dict

1it [00:00,  2.60it/s]
2it [00:00,  4.10it/s]C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 8 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]

3it [00:00,  4.83it/s]
4it [00:00,  5.83it/s]C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 22 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]

5it [00:00,  6.45it/s]C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 1 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]

8it [00:01, 11.50it/s]
10it [00:01,  9.54it/s]
12it [00:01,  9.72it/s]
14it [00:01, 10.62it/s]
16it [00:01, 12.10it/s]
18it [00:01, 12.81it/s]
20it [00:02, 14.10it/s]C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 17 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 20 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]

23it [00:02, 17.39it/s]
26it [00:02, 20.08it/s]
29it [00:02, 13.23it/s]
31it [00:02, 12.21it/s]C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 24 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]

33it [00:03, 11.17it/s]
35it [00:03,  8.47it/s]
37it [00:03,  8.30it/s]
38it [00:03,  7.85it/s]
40it [00:04,  9.21it/s]
42it [00:04, 10.08it/s]
44it [00:04, 10.74it/s]
47it [00:04, 12.37it/s]
50it [00:04, 13.84it/s]
52it [00:04, 13.10it/s]
54it [00:04, 14.37it/s]C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 2 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]

57it [00:05, 16.12it/s]
59it [00:05, 15.17it/s]
61it [00:05, 14.44it/s]
63it [00:05, 13.31it/s]
65it [00:05, 14.20it/s]
67it [00:05, 13.73it/s]
70it [00:06, 16.27it/s]
73it [00:06, 18.49it/s]
76it [00:06, 20.07it/s]
79it [00:06, 16.20it/s]C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 15 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]

82it [00:06, 18.04it/s]
84it [00:06, 17.29it/s]
88it [00:06, 21.33it/s]
91it [00:07, 22.77it/s]
94it [00:07, 20.74it/s]
97it [00:07, 21.89it/s]
101it [00:07, 24.45it/s]
104it [00:07, 21.08it/s]C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 7 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]

107it [00:07, 21.92it/s]
111it [00:07, 25.25it/s]C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 9 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 13 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]

115it [00:08, 25.33it/s]
118it [00:08, 22.77it/s]
121it [00:08, 22.50it/s]C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 3 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]

124it [00:08, 21.55it/s]
128it [00:08, 19.51it/s]
131it [00:09, 15.75it/s]
134it [00:09, 16.77it/s]
136it [00:09, 17.32it/s]
139it [00:09, 19.63it/s]
142it [00:09, 20.49it/s]
145it [00:09, 15.49it/s]
147it [00:10, 11.83it/s]
149it [00:10, 11.08it/s]
152it [00:10, 13.31it/s]
155it [00:10, 15.69it/s]
157it [00:10, 15.94it/s]
159it [00:10, 15.59it/s]
161it [00:11, 14.16it/s]
163it [00:11, 12.55it/s]
165it [00:11, 10.37it/s]
167it [00:11,  9.45it/s]
169it [00:11, 10.53it/s]
171it [00:12, 11.76it/s]C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 4 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 6 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]

174it [00:12, 14.00it/s]
176it [00:12, 13.70it/s]
178it [00:12, 13.03it/s]
180it [00:12, 13.81it/s]
182it [00:12, 15.12it/s]
185it [00:12, 18.15it/s]
187it [00:13, 14.35it/s]
189it [00:13, 13.15it/s]
191it [00:13,  9.95it/s]
193it [00:13,  9.58it/s]
195it [00:13, 10.64it/s]
197it [00:14, 11.91it/s]
199it [00:14, 12.80it/s]C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 12 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]

202it [00:14, 15.39it/s]
205it [00:14, 16.74it/s]
208it [00:14, 17.75it/s]
210it [00:14, 17.69it/s]
212it [00:14, 17.98it/s]
216it [00:14, 19.96it/s]
218it [00:15, 18.43it/s]
220it [00:15, 16.34it/s]
223it [00:15, 17.47it/s]
225it [00:15, 17.98it/s]
227it [00:15, 14.52it/s]
229it [00:16, 10.74it/s]
231it [00:16, 10.42it/s]
233it [00:16, 10.64it/s]
235it [00:16,  8.82it/s]
237it [00:16,  9.24it/s]
239it [00:17, 10.75it/s]
242it [00:17, 14.09it/s]
244it [00:17, 13.87it/s]
246it [00:17, 13.91it/s]
248it [00:17, 12.31it/s]
250it [00:17, 10.13it/s]
252it [00:18,  7.88it/s]
254it [00:18,  9.52it/s]
256it [00:18, 10.59it/s]
258it [00:18, 10.82it/s]
260it [00:19,  8.80it/s]
262it [00:19,  8.61it/s]
263it [00:19,  8.38it/s]
265it [00:19,  9.79it/s]
267it [00:19, 11.69it/s]
269it [00:19, 10.41it/s]
271it [00:20, 10.19it/s]
273it [00:20,  7.90it/s]
275it [00:20,  9.24it/s]
278it [00:20, 11.69it/s]
281it [00:20, 14.58it/s]
284it [00:21, 16.08it/s]
286it [00:21, 13.67it/s]
288it [00:21, 13.44it/s]
290it [00:21, 11.33it/s]
292it [00:22,  9.66it/s]
294it [00:22,  9.38it/s]
296it [00:22,  9.94it/s]
298it [00:22, 10.36it/s]
300it [00:22, 11.94it/s]
302it [00:22, 11.39it/s]
305it [00:22, 14.78it/s]
308it [00:23, 16.72it/s]
313it [00:23, 22.21it/s]
316it [00:23, 23.40it/s]
319it [00:23, 23.08it/s]
322it [00:23, 17.00it/s]
324it [00:24, 13.38it/s]
326it [00:24, 13.14it/s]
328it [00:24, 14.21it/s]
330it [00:24, 15.03it/s]
332it [00:24, 14.95it/s]
335it [00:24, 15.37it/s]
337it [00:24, 13.02it/s]
339it [00:25, 13.57it/s]
341it [00:25, 12.58it/s]
343it [00:25, 10.54it/s]
345it [00:25, 11.24it/s]
347it [00:25, 10.86it/s]
350it [00:26, 14.29it/s]
352it [00:26, 13.37it/s]
355it [00:26, 14.80it/s]
357it [00:26, 12.97it/s]
359it [00:26, 11.20it/s]
361it [00:26, 12.36it/s]
364it [00:27, 15.17it/s]
368it [00:27, 19.32it/s]
371it [00:27, 20.58it/s]C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 5 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]

374it [00:27, 21.55it/s]
377it [00:27, 23.35it/s]
380it [00:27, 23.50it/s]
383it [00:27, 20.15it/s]
386it [00:28, 19.57it/s]
389it [00:28, 16.74it/s]
394it [00:28, 22.14it/s]
397it [00:28, 21.13it/s]
400it [00:28, 20.81it/s]
404it [00:28, 22.88it/s]
407it [00:29, 17.80it/s]
410it [00:29, 19.78it/s]
413it [00:29, 19.62it/s]
416it [00:29, 16.64it/s]
418it [00:29, 16.82it/s]
420it [00:29, 15.05it/s]
422it [00:30, 14.72it/s]
425it [00:30, 16.96it/s]
427it [00:30, 16.76it/s]
429it [00:30, 16.11it/s]
431it [00:30, 14.63it/s]
434it [00:30, 17.00it/s]
437it [00:30, 17.27it/s]
439it [00:31, 16.67it/s]
442it [00:31, 18.82it/s]
444it [00:31, 18.10it/s]
447it [00:31, 17.55it/s]
449it [00:31, 15.30it/s]
451it [00:31, 15.43it/s]
453it [00:31, 13.18it/s]
455it [00:32, 13.97it/s]
457it [00:32, 13.74it/s]
459it [00:32, 13.06it/s]
461it [00:32, 13.64it/s]
465it [00:32, 17.29it/s]
467it [00:32, 15.72it/s]
469it [00:33, 16.07it/s]
472it [00:33, 17.28it/s]
475it [00:33, 18.52it/s]
478it [00:33, 18.64it/s]
482it [00:33, 20.77it/s]
485it [00:33, 18.07it/s]
488it [00:33, 18.30it/s]
490it [00:34, 17.37it/s]
492it [00:34, 14.74it/s]
494it [00:34, 15.01it/s]
496it [00:34, 13.80it/s]
498it [00:34, 12.70it/s]
500it [00:34, 13.75it/s]
502it [00:35, 14.68it/s]
504it [00:35, 14.58it/s]
507it [00:35, 17.23it/s]
509it [00:35, 13.44it/s]
511it [00:35, 10.94it/s]
514it [00:35, 14.20it/s]
517it [00:36, 16.85it/s]
520it [00:36, 17.52it/s]
522it [00:36, 17.24it/s]
525it [00:36, 19.05it/s]
528it [00:36, 18.61it/s]
532it [00:36, 17.60it/s]
534it [00:37, 16.14it/s]
536it [00:37, 15.24it/s]
538it [00:37, 15.32it/s]
541it [00:37, 17.74it/s]
544it [00:37, 20.43it/s]
547it [00:37, 18.83it/s]
550it [00:37, 18.71it/s]
552it [00:38, 17.05it/s]
555it [00:38, 17.95it/s]
558it [00:38, 19.03it/s]C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 16 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]

560it [00:38, 18.75it/s]
563it [00:38, 19.11it/s]
565it [00:38, 16.69it/s]
567it [00:38, 15.69it/s]
570it [00:39, 17.18it/s]
573it [00:39, 19.63it/s]
576it [00:39, 18.02it/s]
578it [00:39, 16.99it/s]
580it [00:39, 16.25it/s]
583it [00:39, 17.87it/s]
585it [00:39, 18.34it/s]
588it [00:39, 20.55it/s]
591it [00:40, 12.25it/s]
593it [00:40, 12.90it/s]
596it [00:40, 14.66it/s]
598it [00:40, 14.60it/s]
600it [00:41, 13.31it/s]
602it [00:41, 13.49it/s]
604it [00:41, 14.62it/s]
607it [00:41, 15.27it/s]
609it [00:41, 13.48it/s]
611it [00:41, 10.68it/s]
613it [00:42,  9.50it/s]
615it [00:42, 10.66it/s]
617it [00:42, 11.68it/s]
620it [00:42, 13.31it/s]
622it [00:42, 13.69it/s]
625it [00:42, 16.72it/s]
629it [00:43, 20.33it/s]
632it [00:43, 18.07it/s]
634it [00:43, 18.30it/s]
636it [00:43, 16.58it/s]
638it [00:43, 12.07it/s]
641it [00:43, 14.17it/s]
644it [00:44, 13.74it/s]
646it [00:44, 13.76it/s]
649it [00:44, 16.54it/s]
651it [00:44, 14.67it/s]
653it [00:44, 14.64it/s]
655it [00:44, 14.33it/s]
657it [00:45, 15.39it/s]
660it [00:45, 17.98it/s]
663it [00:45, 20.07it/s]
666it [00:45, 18.54it/s]
668it [00:45, 17.57it/s]
671it [00:45, 19.14it/s]
674it [00:45, 20.47it/s]
677it [00:45, 22.49it/s]
680it [00:46, 18.72it/s]
683it [00:46, 18.81it/s]
687it [00:46, 22.43it/s]
690it [00:46, 20.85it/s]
693it [00:46, 18.32it/s]
695it [00:47, 15.14it/s]
697it [00:47, 13.54it/s]
699it [00:47, 12.64it/s]
701it [00:47, 11.97it/s]
703it [00:47, 12.11it/s]
705it [00:48,  9.54it/s]
707it [00:48,  9.67it/s]
711it [00:48, 13.75it/s]
715it [00:48, 16.37it/s]
717it [00:48, 16.37it/s]
719it [00:48, 12.52it/s]
722it [00:49, 13.54it/s]
725it [00:49, 14.64it/s]
727it [00:49, 13.34it/s]
729it [00:49, 14.54it/s]
733it [00:49, 19.03it/s]
736it [00:49, 17.75it/s]
739it [00:50, 19.05it/s]
742it [00:50, 20.82it/s]
745it [00:50, 22.86it/s]
748it [00:50, 23.74it/s]
752it [00:50, 23.36it/s]
755it [00:50, 24.30it/s]
758it [00:50, 19.58it/s]
761it [00:51, 17.09it/s]
763it [00:51, 15.19it/s]
766it [00:51, 16.21it/s]
768it [00:51, 15.45it/s]
770it [00:51, 16.36it/s]
774it [00:51, 20.37it/s]
778it [00:52, 23.05it/s]
781it [00:52, 19.58it/s]
784it [00:52, 16.38it/s]
786it [00:52, 16.86it/s]
788it [00:52, 17.01it/s]
791it [00:52, 16.59it/s]
793it [00:53, 13.86it/s]
795it [00:53, 12.05it/s]
797it [00:53, 10.92it/s]
799it [00:53, 10.30it/s]
801it [00:53, 10.31it/s]
803it [00:54,  9.94it/s]
805it [00:54, 10.46it/s]
807it [00:54, 10.07it/s]
809it [00:54,  9.42it/s]
811it [00:54, 10.57it/s]
813it [00:55, 12.12it/s]
815it [00:55, 13.44it/s]
817it [00:55, 11.69it/s]
819it [00:55, 10.28it/s]
821it [00:55, 11.16it/s]
823it [00:55, 12.20it/s]
825it [00:56, 11.43it/s]
827it [00:56,  9.93it/s]
829it [00:56, 11.48it/s]
831it [00:56, 12.56it/s]
834it [00:56, 14.56it/s]
836it [00:56, 14.98it/s]
838it [00:57, 14.83it/s]
840it [00:57, 13.29it/s]
842it [00:57, 13.61it/s]C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 11 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]

844it [00:57, 12.76it/s]
846it [00:58,  7.56it/s]
848it [00:58,  7.23it/s]
850it [00:58,  6.07it/s]
852it [00:58,  7.31it/s]
855it [00:59,  9.82it/s]
858it [00:59, 12.10it/s]
861it [00:59, 14.64it/s]
864it [00:59, 17.35it/s]
867it [00:59, 19.57it/s]
870it [00:59, 21.29it/s]
873it [00:59, 18.82it/s]
876it [01:00, 16.65it/s]
878it [01:00, 16.54it/s]
882it [01:00, 20.10it/s]
886it [01:00, 23.57it/s]
889it [01:00, 24.73it/s]
892it [01:00, 26.02it/s]
896it [01:00, 28.19it/s]
899it [01:00, 27.91it/s]
902it [01:01, 27.85it/s]
905it [01:01, 21.88it/s]
908it [01:01, 15.84it/s]
911it [01:01, 16.85it/s]
913it [01:02, 11.75it/s]
915it [01:02, 11.20it/s]
917it [01:02, 12.40it/s]
919it [01:02, 11.80it/s]
921it [01:02,  9.70it/s]
923it [01:03, 11.34it/s]
926it [01:03, 14.03it/s]
929it [01:03, 15.16it/s]
931it [01:03, 16.09it/s]
933it [01:03, 16.49it/s]
936it [01:03, 19.16it/s]
939it [01:03, 16.83it/s]
941it [01:03, 17.09it/s]
943it [01:04, 15.05it/s]
947it [01:04, 18.69it/s]
950it [01:04, 19.11it/s]
953it [01:04, 16.94it/s]
957it [01:04, 18.26it/s]
960it [01:04, 19.68it/s]
963it [01:05, 16.36it/s]
965it [01:05, 14.44it/s]
969it [01:05, 18.11it/s]
972it [01:05, 15.34it/s]
975it [01:05, 17.27it/s]
977it [01:06, 16.44it/s]
979it [01:06, 15.60it/s]
981it [01:06, 12.20it/s]
983it [01:06, 12.03it/s]
985it [01:06, 12.81it/s]
987it [01:06, 12.39it/s]
989it [01:07, 10.91it/s]
991it [01:07, 12.36it/s]
993it [01:07, 12.50it/s]
995it [01:07, 12.93it/s]
997it [01:07, 14.38it/s]
999it [01:07, 14.46it/s]
1003it [01:07, 19.65it/s]
1006it [01:08, 20.10it/s]
1009it [01:08, 16.45it/s]
1012it [01:08, 17.29it/s]
1014it [01:08, 16.35it/s]
1017it [01:08, 18.50it/s]
1020it [01:08, 20.58it/s]
1023it [01:09, 21.76it/s]
1026it [01:09, 18.91it/s]
1029it [01:09, 14.90it/s]
1031it [01:09, 14.92it/s]
1033it [01:09, 14.82it/s]
1035it [01:10, 11.61it/s]
1037it [01:10, 10.34it/s]
1039it [01:10, 11.66it/s]
1041it [01:10,  9.44it/s]
1043it [01:10,  9.98it/s]
1045it [01:11, 10.18it/s]
1047it [01:11,  8.65it/s]
1048it [01:11,  7.30it/s]
1050it [01:11,  7.75it/s]
1051it [01:12,  6.51it/s]
1052it [01:12,  6.00it/s]
1053it [01:12,  6.50it/s]
1055it [01:12,  8.25it/s]
1057it [01:12, 10.00it/s]
1059it [01:12, 10.09it/s]
1061it [01:13, 11.85it/s]
1064it [01:13, 14.54it/s]
1068it [01:13, 19.74it/s]
1071it [01:13, 22.01it/s]
1076it [01:13, 26.31it/s]
1079it [01:13, 19.41it/s]
1082it [01:14, 17.50it/s]
1084it [01:14, 15.65it/s]
1086it [01:14, 12.79it/s]
1088it [01:14, 12.23it/s]
1090it [01:14, 11.80it/s]
1092it [01:15, 10.93it/s]
1094it [01:15, 10.90it/s]
1096it [01:15,  6.84it/s]
1097it [01:16,  6.10it/s]
1098it [01:16,  6.17it/s]
1100it [01:16,  7.92it/s]
1101it [01:16,  7.78it/s]
1103it [01:16,  8.48it/s]
1104it [01:16,  8.25it/s]
1105it [01:16,  8.17it/s]
1108it [01:17, 11.40it/s]
1110it [01:17, 13.12it/s]
1112it [01:17, 12.43it/s]
1114it [01:17,  8.78it/s]
1116it [01:17,  9.27it/s]
1118it [01:18,  9.97it/s]
1120it [01:18, 10.82it/s]
1122it [01:18, 11.74it/s]
1124it [01:18,  9.07it/s]
1126it [01:18, 10.32it/s]
1128it [01:18, 11.44it/s]
1130it [01:19, 12.99it/s]
1132it [01:19, 13.25it/s]
1135it [01:19, 15.70it/s]
1138it [01:19, 18.50it/s]
1140it [01:19, 18.43it/s]
1142it [01:19, 16.80it/s]
1145it [01:19, 19.73it/s]
1148it [01:20, 12.16it/s]
1150it [01:20, 10.70it/s]
1153it [01:20, 12.43it/s]
1155it [01:20, 12.31it/s]
1157it [01:21, 12.68it/s]
1159it [01:21, 14.06it/s]
1162it [01:21, 16.72it/s]
1164it [01:21, 16.67it/s]
1166it [01:21, 17.01it/s]
1170it [01:21, 21.88it/s]
1174it [01:21, 24.41it/s]
1177it [01:21, 21.90it/s]
1180it [01:22, 16.53it/s]
1182it [01:22, 16.35it/s]
1184it [01:22, 16.66it/s]
1187it [01:22, 17.15it/s]
1190it [01:22, 17.79it/s]
1192it [01:22, 17.22it/s]
1194it [01:23, 16.60it/s]
1198it [01:23, 21.09it/s]
1201it [01:23, 18.32it/s]
1203it [01:23, 18.31it/s]
1205it [01:23, 16.53it/s]
1207it [01:23, 16.69it/s]
1209it [01:23, 16.15it/s]
1212it [01:23, 19.31it/s]
1215it [01:24, 16.89it/s]
1217it [01:24, 15.95it/s]
1220it [01:24, 18.13it/s]
1222it [01:24, 14.57it/s]
1224it [01:24, 13.11it/s]
1226it [01:25, 12.69it/s]
1228it [01:25, 12.52it/s]
1230it [01:25, 13.94it/s]
1233it [01:25, 16.26it/s]
1235it [01:25, 16.89it/s]
1237it [01:25, 16.47it/s]C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 10 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]

1239it [01:25, 14.66it/s]C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 27 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]

1241it [01:26, 12.72it/s]
1243it [01:26, 12.60it/s]C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 18 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 26 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]

1245it [01:26, 12.04it/s]
1248it [01:26, 13.22it/s]
1250it [01:26, 12.67it/s]
1253it [01:26, 14.46it/s]
1256it [01:27, 17.45it/s]
1259it [01:27, 18.05it/s]
1261it [01:27, 17.68it/s]
1263it [01:27, 18.02it/s]
1266it [01:27, 20.53it/s]
1269it [01:27, 16.18it/s]
1271it [01:27, 14.45it/s]
1273it [01:28, 13.74it/s]
1275it [01:28, 12.58it/s]
1277it [01:28, 12.34it/s]
1279it [01:28, 12.67it/s]
1281it [01:28, 12.01it/s]
1283it [01:28, 12.13it/s]
1285it [01:29, 13.51it/s]
1287it [01:29, 14.09it/s]
1290it [01:29, 14.23it/s]
1292it [01:29, 14.00it/s]
1294it [01:29, 14.75it/s]
1296it [01:29, 14.50it/s]
1298it [01:29, 15.36it/s]
1300it [01:30, 15.91it/s]
1302it [01:30, 16.73it/s]
1304it [01:30, 16.41it/s]

In [24]:
import requests
import os

# GitHub raw CSV URL
url = "https://raw.githubusercontent.com/nissy-dev/machine-learning-the-voltage-of-electrode-materials/master/dataset/mp_data/data_2019_12_03.csv"

# Folder where the CSV will be saved
folder = "../dataset/mp_data"
os.makedirs(folder, exist_ok=True)

# Output file
output_path = os.path.join(folder, "data_2019_12_03.csv")

print("Downloading ML-MiB dataset...")

response = requests.get(url, stream=True)
response.raise_for_status()

total_size = int(response.headers.get("content-length", 0))
downloaded = 0

with open(output_path, "wb") as f:
    for chunk in response.iter_content(chunk_size=8192):
        if chunk:
            f.write(chunk)
            downloaded += len(chunk)

            if total_size:
                percent = downloaded / total_size * 100
                print(f"\rDownloading: {percent:.2f}%", end="")

print("\n\n✅ Download completed!")
print("Saved at:", os.path.abspath(output_path))

Downloading ML-MiB dataset...
Downloading: 229.57%

✅ Download completed!
Saved at: C:\Users\ADMIN\Desktop\PS PROJECT\PS 2-1 CRYSTAL DOMAIN\PROJECT\PROGRAM\dataset\mp_data\data_2019_12_03.csv

In [25]:
import pandas as pd

df = pd.read_csv("../dataset/mp_data/data_2019_12_03.csv")

print("Rows:", len(df))
print("Columns:", len(df.columns))

print("\nColumn names:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

Rows: 5133
Columns: 15

Column names:
['Unnamed: 0', 'battery_id', 'formula_charge', 'id_charge', 'stability_charge', 'formula_discharge', 'id_discharge', 'stability_discharge', 'average_voltage', 'capacity_grav', 'capacity_vol', 'energy_grav', 'energy_vol', 'max_delta_volume', 'working_ion']

First 5 rows:

,Unnamed: 0,battery_id,formula_charge,id_charge,stability_charge,formula_discharge,id_discharge,stability_discharge,average_voltage,capacity_grav,capacity_vol,energy_grav,energy_vol,max_delta_volume,working_ion
0,0,mp-504791_Li,P(WO4)2,mp-28000,0.000000,LiP(WO4)2,mp-757610,0.037837,2.325185,50.228609,269.262771,116.790816,626.085802,0.028564,Li
1,1,mp-763480_Li,P3W2O13,mp-757302,0.000097,LiP3W2O13,mp-758455,0.039966,3.291748,39.674483,154.215698,130.598387,507.639167,0.017562,Li
2,2,mp-1176966_Li,P8W3O29,mp-776468,0.061321,Li2P8W3O29,mp-776995,0.025051,5.062579,41.969954,142.111725,212.476221,719.451888,0.061034,Li
3,3,mp-1176966_Li,Li2P8W3O29,mp-776995,0.025051,Li6P8W3O29,mp-1176966,0.029375,3.595344,82.153994,291.921377,295.371876,1049.557797,0.027084,Li
4,4,mp-1176966_Li,Li6P8W3O29,mp-1176966,0.029375,Li9P8W3O29,mp-776590,0.025606,2.660169,60.647735,217.236232,161.333195,577.884983,0.007848,Li

In [27]:
import os
import sys
import h5py
import numpy as np
import pandas as pd

from tqdm.auto import tqdm

from pymatgen.core import Composition, Element, Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

# ---------------------------------------------------------
# 1. PATHS
# ---------------------------------------------------------

PROGRAM = r"C:\Users\ADMIN\Desktop\PS PROJECT\PS 2-1 CRYSTAL DOMAIN\PROJECT\PROGRAM"

# Raw battery CSV
BATTERY_CSV = os.path.join(
    PROGRAM,
    "dataset",
    "mp_data",
    "data_2019_12_03.csv"
)

# Your H5 file
H5_FILE = os.path.join(
    PROGRAM,
    "data_2019_12_03.h5"
)

# 44 elemental-property tables
ELEMENT_DATA = os.path.join(
    PROGRAM,
    "element_data"
)

# Output CSV
OUTPUT_CSV = os.path.join(
    PROGRAM,
    "dataset",
    "mp_data",
    "ML_MiB_239_features.csv"
)

# ---------------------------------------------------------
# 2. IMPORT REPOSITORY UTILS.PY
# ---------------------------------------------------------

PREPROCESS_FOLDER = os.path.join(PROGRAM, "preprocess")

if PREPROCESS_FOLDER not in sys.path:
    sys.path.insert(0, PREPROCESS_FOLDER)

from utils import (
    NUM_OF_FEATURE,
    ElementDataSingleton,
    create_feature_from_formula,
    create_feature_from_wokring_ion,
    create_feature_from_crystal_system
)

print("Repository utilities loaded.")
print("NUM_OF_FEATURE =", NUM_OF_FEATURE)

# ---------------------------------------------------------
# 3. CHECK FILES
# ---------------------------------------------------------

print("\nChecking files...")

required_files = {
    "Battery CSV": BATTERY_CSV,
    "H5 file": H5_FILE,
    "Element data folder": ELEMENT_DATA
}

for name, file_path in required_files.items():

    if os.path.exists(file_path):
        print(f"✅ {name}: FOUND")
    else:
        print(f"❌ {name}: NOT FOUND")
        print(file_path)

# ---------------------------------------------------------
# 4. LOAD BATTERY DATA
# ---------------------------------------------------------

print("\nLoading battery CSV...")

battery_table = pd.read_csv(
    BATTERY_CSV,
    index_col=False
)

print("Rows:", len(battery_table))
print("Columns:", len(battery_table.columns))

print("\nColumns:")
print(battery_table.columns.tolist())

# ---------------------------------------------------------
# 5. LOAD ELEMENT DATA
# ---------------------------------------------------------

print("\nLoading elemental-property tables...")

element_data = ElementDataSingleton.get_instance(
    element_data_path=ELEMENT_DATA
)

print("✅ Element data loaded.")

# ---------------------------------------------------------
# 6. OPEN H5
# ---------------------------------------------------------

print("\nOpening H5 file...")

cif_data = h5py.File(
    H5_FILE,
    "r"
)

print("Number of structures in H5:", len(cif_data))

# ---------------------------------------------------------
# 7. PREPARE FEATURE ARRAY
# ---------------------------------------------------------

n_rows = len(battery_table)

features = np.zeros(
    (n_rows, NUM_OF_FEATURE),
    dtype=float
)

print("\nFeature array created:")
print(features.shape)

# ---------------------------------------------------------
# 8. CACHE
# ---------------------------------------------------------

# Cache crystal information because the same material ID
# can appear multiple times.

spacegroup_cache = {}
crystal_system_cache = {}

# Cache composition features
formula_cache = {}

# ---------------------------------------------------------
# 9. HELPER FUNCTION
# ---------------------------------------------------------

def get_cif_structure(material_id):

    cif = cif_data[material_id][()]

    if isinstance(cif, bytes):
        cif = cif.decode("utf-8")

    return Structure.from_str(
        cif,
        fmt="cif"
    )


def get_formula_features(formula):

    if formula not in formula_cache:

        formula_cache[formula] = create_feature_from_formula(
            formula,
            element_data
        )

    return formula_cache[formula].copy()


# ---------------------------------------------------------
# 10. GENERATE FEATURES
# ---------------------------------------------------------

print("\n==============================================")
print("STARTING ML-MiB FEATURE GENERATION")
print("==============================================")

progress = tqdm(
    total=n_rows,
    desc="Generating features",
    unit="row",
    dynamic_ncols=True
)

start_time = __import__("time").time()

try:

    for i in range(n_rows):

        # -------------------------------------------------
        # Current row
        # -------------------------------------------------

        row = battery_table.iloc[i]

        id_charge = row["id_charge"]
        id_discharge = row["id_discharge"]
        ion = row["working_ion"]

        progress.set_description(
            f"Processing {i + 1}/{n_rows}"
        )

        # -------------------------------------------------
        # CHARGE STRUCTURE
        # -------------------------------------------------

        if id_charge in spacegroup_cache:

            space_group_number = spacegroup_cache[id_charge]
            crystal_system = crystal_system_cache[id_charge]

        else:

            charge_crystal = get_cif_structure(
                id_charge
            )

            # symprec=0.1 helps make the calculation
            # considerably more practical on modern pymatgen

            finder = SpacegroupAnalyzer(
                charge_crystal,
                symprec=0.1
            )

            space_group_number = (
                finder.get_space_group_number()
            )

            crystal_system = (
                finder.get_crystal_system()
            )

            spacegroup_cache[id_charge] = (
                space_group_number
            )

            crystal_system_cache[id_charge] = (
                crystal_system
            )

        # -------------------------------------------------
        # SPACE GROUP FEATURE
        # -------------------------------------------------

        space_group_feat = np.array([
            space_group_number
        ])

        # -------------------------------------------------
        # CRYSTAL SYSTEM FEATURE
        # -------------------------------------------------

        crystal_system_feat = (
            create_feature_from_crystal_system(
                crystal_system
            )
        )

        # -------------------------------------------------
        # WORKING ION FEATURE
        # -------------------------------------------------

        ion_feat = (
            create_feature_from_wokring_ion(
                ion
            )
        )

        # -------------------------------------------------
        # DISCHARGE STRUCTURE
        # -------------------------------------------------

        discharge_crystal = get_cif_structure(
            id_discharge
        )

        discharge_composition = Composition(
            discharge_crystal.formula
        )

        ion_concentrate = np.array([
            discharge_composition.get_atomic_fraction(
                Element(ion)
            )
        ])

        # -------------------------------------------------
        # FORMULAS
        # -------------------------------------------------

        charge_formula = charge_crystal.formula \
            if "charge_crystal" in locals() else \
            get_cif_structure(id_charge).formula

        discharge_formula = discharge_crystal.formula

        # -------------------------------------------------
        # CHARGE COMPOSITION FEATURES
        # -------------------------------------------------

        feature_charge = get_formula_features(
            charge_formula
        )

        # If only one element -> pad 44 zeros
        if feature_charge.shape[0] == 44:

            feature_charge = np.concatenate([
                feature_charge,
                np.zeros(44)
            ])

        # -------------------------------------------------
        # DISCHARGE COMPOSITION FEATURES
        # -------------------------------------------------

        feature_discharge = get_formula_features(
            discharge_formula
        )

        # Make sure it has 88 features
        if feature_discharge.shape[0] == 44:

            feature_discharge = np.concatenate([
                feature_discharge,
                np.zeros(44)
            ])

        # -------------------------------------------------
        # WORKING ION ELEMENT FEATURES
        # -------------------------------------------------

        feature_ion = get_formula_features(
            ion
        )

        # -------------------------------------------------
        # COMBINE ALL FEATURES
        # -------------------------------------------------

        complete_feature = np.concatenate([
            space_group_feat,
            crystal_system_feat,
            ion_feat,
            ion_concentrate,
            feature_charge,
            feature_discharge,
            feature_ion
        ])

        # -------------------------------------------------
        # CHECK FEATURE COUNT
        # -------------------------------------------------

        if len(complete_feature) != NUM_OF_FEATURE:

            raise ValueError(
                f"Feature count error at row {i}. "
                f"Expected {NUM_OF_FEATURE}, "
                f"got {len(complete_feature)}"
            )

        # -------------------------------------------------
        # SAVE INTO ARRAY
        # -------------------------------------------------

        features[i] = complete_feature

        # -------------------------------------------------
        # UPDATE PROGRESS
        # -------------------------------------------------

        progress.update(1)

finally:

    progress.close()

# ---------------------------------------------------------
# 11. CREATE FEATURE DATAFRAME
# ---------------------------------------------------------

print("\nCreating DataFrame...")

feature_columns = [
    f"feat_{i + 1}"
    for i in range(NUM_OF_FEATURE)
]

feature_df = pd.DataFrame(
    features,
    columns=feature_columns
)

# ---------------------------------------------------------
# 12. ADD TARGET VOLTAGE
# ---------------------------------------------------------

feature_df["average_voltage"] = (
    battery_table["average_voltage"].values
)

# ---------------------------------------------------------
# 13. SAVE CSV
# ---------------------------------------------------------

print("\nSaving CSV...")

feature_df.to_csv(
    OUTPUT_CSV,
    index=False
)

# ---------------------------------------------------------
# 14. FINAL INFORMATION
# ---------------------------------------------------------

elapsed = __import__("time").time() - start_time

print("\n==============================================")
print("✅ ML-MiB DATASET CREATED")
print("==============================================")

print("Rows:", feature_df.shape[0])
print("Columns:", feature_df.shape[1])

print("Feature columns:", NUM_OF_FEATURE)
print("Target column: average_voltage")

print(
    f"Time taken: {elapsed / 60:.2f} minutes"
)

print("\nSaved file:")
print(OUTPUT_CSV)

print("\nFirst 5 rows:")
display(feature_df.head())

Repository utilities loaded.
NUM_OF_FEATURE = 239

Checking files...
✅ Battery CSV: FOUND
✅ H5 file: FOUND
✅ Element data folder: FOUND

Loading battery CSV...
Rows: 5133
Columns: 15

Columns:
['Unnamed: 0', 'battery_id', 'formula_charge', 'id_charge', 'stability_charge', 'formula_discharge', 'id_discharge', 'stability_discharge', 'average_voltage', 'capacity_grav', 'capacity_vol', 'energy_grav', 'energy_vol', 'max_delta_volume', 'working_ion']

Loading elemental-property tables...
✅ Element data loaded.

Opening H5 file...
Number of structures in H5: 8338

Feature array created:
(5133, 239)

==============================================
STARTING ML-MiB FEATURE GENERATION
==============================================

Generating features:   0%|          | 0/5133 [00:00<?, ?row/s]

C:\Users\ADMIN\Desktop\PS PROJECT\PS 2-1 CRYSTAL DOMAIN\PROJECT\PROGRAM\preprocess\utils.py:93: FutureWarning: to_reduced_dict is deprecated, and will be removed on 2026-04-04
Use as_reduced_dict in pymatgen.core.composition instead.
  element_dict = comp.to_reduced_dict
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 8 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 22 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 1 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 17 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 20 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 24 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 2 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 15 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 7 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 9 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 13 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 3 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 4 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 6 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 12 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 5 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 16 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 11 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 10 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 27 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 18 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 26 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 23 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 21 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\pymatgen\io\cif.py:1817: UserWarning: Issues encountered while parsing CIF: 14 fractional coordinates rounded to ideal values to avoid issues with finite precision.
  return parser.parse_structures(primitive=primitive)[0]

Creating DataFrame...

Saving CSV...

==============================================
✅ ML-MiB DATASET CREATED
==============================================
Rows: 5133
Columns: 240
Feature columns: 239
Target column: average_voltage
Time taken: 5.08 minutes

Saved file:
C:\Users\ADMIN\Desktop\PS PROJECT\PS 2-1 CRYSTAL DOMAIN\PROJECT\PROGRAM\dataset\mp_data\ML_MiB_239_features.csv

First 5 rows:

,feat_1,feat_2,feat_3,feat_4,feat_5,feat_6,feat_7,feat_8,feat_9,feat_10,...,feat_231,feat_232,feat_233,feat_234,feat_235,feat_236,feat_237,feat_238,feat_239,average_voltage
0,19.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,24.335,2.0,229.0,2.325185
1,14.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,24.335,2.0,229.0,3.291748
2,165.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,24.335,2.0,229.0,5.062579
3,9.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,24.335,2.0,229.0,3.595344
4,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,24.335,2.0,229.0,2.660169

In [28]:
import os
import pandas as pd
from tqdm.auto import tqdm

# ============================================================
# 1. PROGRAM PATH
# ============================================================

PROGRAM = r"C:\Users\ADMIN\Desktop\PS PROJECT\PS 2-1 CRYSTAL DOMAIN\PROJECT\PROGRAM"

# Your folder containing the 44 .table files
ELEMENT_DATA = os.path.join(
    PROGRAM,
    "element_data"
)

# Output CSV
OUTPUT_CSV = os.path.join(
    PROGRAM,
    "element_properties_44.csv"
)

# ============================================================
# 2. EXACT 44 FEATURE NAMES
# ============================================================

FEATURE_NAMES = [
    "AtimicNumber",
    "AtomicVolume",
    "AtomicWeight",
    "BCCefflatcnt",
    "BCCenergydiff",
    "BCCfermi",
    "BCCmagmom",
    "BCCvolume_pa",
    "BCCvolume_padiff",
    "BoilingT",
    "ColumnNumber",
    "CovalentRadius",
    "Density",
    "FirstIonizationEnergy",
    "GSbandgap",
    "GSefflatcnt",
    "GSestBCClatcnt",
    "GSestFCClatcnt",
    "GSmagmom",
    "GSvolume_pa",
    "HeatCapacityMass",
    "HeatCapacityMolar",
    "ICSDVolume",
    "IsAlkali",
    "IsDBlock",
    "IsFBlock",
    "IsMetal",
    "IsMetalloid",
    "IsNonmetal",
    "MendeleevNumber",
    "NUnfilled",
    "NValance",
    "NdUnfilled",
    "NdValence",
    "NfUnfilled",
    "NfValence",
    "NpUnfilled",
    "NpValence",
    "NsUnfilled",
    "NsValence",
    "OxidationStates",
    "Polarizability",
    "RowNumber",
    "SpaceGroupNumber"
]

# ============================================================
# 3. CHECK ELEMENT DATA FOLDER
# ============================================================

print("Checking element_data folder...\n")

if not os.path.exists(ELEMENT_DATA):
    raise FileNotFoundError(
        f"❌ element_data folder not found:\n{ELEMENT_DATA}"
    )

print("✅ element_data folder found:")
print(ELEMENT_DATA)

# ============================================================
# 4. CHECK ALL 44 FILES
# ============================================================

print("\nChecking 44 feature files...\n")

missing_files = []

for feature in FEATURE_NAMES:

    file_path = os.path.join(
        ELEMENT_DATA,
        feature + ".table"
    )

    if not os.path.exists(file_path):
        missing_files.append(feature + ".table")

if missing_files:

    print("❌ Missing files:\n")

    for file in missing_files:
        print("   ", file)

    raise FileNotFoundError(
        "\nSome required .table files are missing."
    )

print("✅ All 44 feature files found!")

# ============================================================
# 5. FUNCTION TO READ A .TABLE FILE
# ============================================================

def read_table_file(file_path):

    values = {}

    with open(
        file_path,
        "r",
        encoding="utf-8",
        errors="ignore"
    ) as file:

        for line in file:

            line = line.strip()

            # Skip empty lines
            if not line:
                continue

            # Skip comments
            if line.startswith("#"):
                continue

            parts = line.split()

            # Need at least element + value
            if len(parts) < 2:
                continue

            element = parts[0]

            # Everything after element
            raw_value = " ".join(parts[1:])

            # --------------------------------------------
            # Try converting to number
            # --------------------------------------------

            try:

                value = float(raw_value)

            except ValueError:

                # Some tables may contain non-numeric/
                # missing values.
                #
                # For ML numerical processing,
                # convert those to 0.

                value = 0.0

            values[element] = value

    return values

# ============================================================
# 6. LOAD ALL 44 FEATURES
# ============================================================

all_data = {}

print("\nLoading 44 elemental properties...\n")

for feature in tqdm(
    FEATURE_NAMES,
    desc="Loading features",
    unit="feature"
):

    file_path = os.path.join(
        ELEMENT_DATA,
        feature + ".table"
    )

    all_data[feature] = read_table_file(
        file_path
    )

print("\n✅ All 44 feature tables loaded!")

# ============================================================
# 7. FIND ALL ELEMENTS
# ============================================================

print("\nFinding elements...")

all_elements = set()

for feature in FEATURE_NAMES:

    all_elements.update(
        all_data[feature].keys()
    )

# Sort alphabetically
all_elements = sorted(all_elements)

print(
    f"✅ Found {len(all_elements)} elements."
)

# ============================================================
# 8. CREATE DATAFRAME
# ============================================================

print("\nCreating DataFrame...")

data = {}

# Element identifier
data["Element"] = all_elements

# Add the 44 actual feature names
for feature in FEATURE_NAMES:

    data[feature] = [
        all_data[feature].get(
            element,
            0.0
        )
        for element in all_elements
    ]

df = pd.DataFrame(data)

# ============================================================
# 9. CHECK COLUMN NAMES
# ============================================================

print("\n==========================================")
print("COLUMN CHECK")
print("==========================================")

print(
    "Number of elemental features:",
    len(FEATURE_NAMES)
)

print(
    "Total CSV columns including Element:",
    len(df.columns)
)

print("\nColumn names:\n")

for i, column in enumerate(df.columns, start=1):

    print(
        f"{i:02d}. {column}"
    )

# ============================================================
# 10. SAVE CSV
# ============================================================

df.to_csv(
    OUTPUT_CSV,
    index=False
)

# ============================================================
# 11. FINAL RESULT
# ============================================================

print("\n==========================================")
print("✅ CSV CREATED SUCCESSFULLY")
print("==========================================")

print(
    "Rows:",
    len(df)
)

print(
    "44 feature columns:",
    len(FEATURE_NAMES)
)

print(
    "Total columns including Element:",
    len(df.columns)
)

print("\nSaved at:")

print(OUTPUT_CSV)

# ============================================================
# 12. DISPLAY FIRST 10 ROWS
# ============================================================

print("\nFirst 10 rows:")

display(df.head(10))

Checking element_data folder...

✅ element_data folder found:
C:\Users\ADMIN\Desktop\PS PROJECT\PS 2-1 CRYSTAL DOMAIN\PROJECT\PROGRAM\element_data

Checking 44 feature files...

✅ All 44 feature files found!

Loading 44 elemental properties...

Loading features:   0%|          | 0/44 [00:00<?, ?feature/s]

✅ All 44 feature tables loaded!

Finding elements...
✅ Found 8 elements.

Creating DataFrame...

==========================================
COLUMN CHECK
==========================================
Number of elemental features: 44
Total CSV columns including Element: 45

Column names:

01. Element
02. AtimicNumber
03. AtomicVolume
04. AtomicWeight
05. BCCefflatcnt
06. BCCenergydiff
07. BCCfermi
08. BCCmagmom
09. BCCvolume_pa
10. BCCvolume_padiff
11. BoilingT
12. ColumnNumber
13. CovalentRadius
14. Density
15. FirstIonizationEnergy
16. GSbandgap
17. GSefflatcnt
18. GSestBCClatcnt
19. GSestFCClatcnt
20. GSmagmom
21. GSvolume_pa
22. HeatCapacityMass
23. HeatCapacityMolar
24. ICSDVolume
25. IsAlkali
26. IsDBlock
27. IsFBlock
28. IsMetal
29. IsMetalloid
30. IsNonmetal
31. MendeleevNumber
32. NUnfilled
33. NValance
34. NdUnfilled
35. NdValence
36. NfUnfilled
37. NfValence
38. NpUnfilled
39. NpValence
40. NsUnfilled
41. NsValence
42. OxidationStates
43. Polarizability
44. RowNumber
45. SpaceGroupNumber

==========================================
✅ CSV CREATED SUCCESSFULLY
==========================================
Rows: 8
44 feature columns: 44
Total columns including Element: 45

Saved at:
C:\Users\ADMIN\Desktop\PS PROJECT\PS 2-1 CRYSTAL DOMAIN\PROJECT\PROGRAM\element_properties_44.csv

First 10 rows:

,Element,AtimicNumber,AtomicVolume,AtomicWeight,BCCefflatcnt,BCCenergydiff,BCCfermi,BCCmagmom,BCCvolume_pa,BCCvolume_padiff,...,NfUnfilled,NfValence,NpUnfilled,NpValence,NsUnfilled,NsValence,OxidationStates,Polarizability,RowNumber,SpaceGroupNumber
0,-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,-2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,-3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,-4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0
5,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0
6,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0
7,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0