In [29]:
!pip install -U mp-api pymatgen matminer pandas numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mp-api in c:\users\admin\appdata\roaming\python\python313\site-packages (0.46.5)
Requirement already satisfied: pymatgen in c:\users\admin\appdata\roaming\python\python313\site-packages (2026.9.24)
Requirement already satisfied: matminer in c:\users\admin\appdata\roaming\python\python313\site-packages (0.10.1)
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Collecting pandas
  Using cached pandas-3.0.6-cp313-cp313-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy in c:\users\admin\appdata\roaming\python\python313\site-packages (2.5.3)
Requirement already satisfied: typing-extensions>=3.7.4.1 in c:\programdata\anaconda3\lib\site-packages (from mp-api) (4.15.0)
Requirement already satisfied: requests>=2.23.0 in c:\programdata\anaconda3\lib\site-packages (from mp-api) (2.32.5)
Requirement already satisfied: monty>=2024.12.10 in c:\users\admin\appdata\roaming\python\python313\site-packages (from mp-api) (2026.7.16)
Requirement already satisfied: emmet-core>=0.87.1 in c:\users\admin\appdata\roaming\python\python313\site-packages (from mp-api) (0.87.2)
Requirement already satisfied: boto3 in c:\users\admin\appdata\roaming\python\python313\site-packages (from mp-api) (1.43.100)
Requirement already satisfied: orjson<4,>=3.10 in c:\users\admin\appdata\roaming\python\python313\site-packages (from mp-api) (3.12.0)
Requirement already satisfied: pyarrow>=20.0.0 in c:\programdata\anaconda3\lib\site-packages (from mp-api) (21.0.0)
Requirement already satisfied: deltalake<1.6.0,>=1.4.0 in c:\users\admin\appdata\roaming\python\python313\site-packages (from mp-api) (1.5.1)
Requirement already satisfied: arro3-core>=0.5.0 in c:\users\admin\appdata\roaming\python\python313\site-packages (from deltalake<1.6.0,>=1.4.0->mp-api) (0.8.3)
Requirement already satisfied: deprecated>=1.2.18 in c:\users\admin\appdata\roaming\python\python313\site-packages (from deltalake<1.6.0,>=1.4.0->mp-api) (1.3.1)
Requirement already satisfied: pymatgen-core>=2026.9.23 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymatgen) (2026.9.23)
Requirement already satisfied: tqdm~=4.66 in c:\users\admin\appdata\roaming\python\python313\site-packages (from matminer) (4.70.1)
Requirement already satisfied: pymongo~=4.5 in c:\users\admin\appdata\roaming\python\python313\site-packages (from matminer) (4.18.2)
Requirement already satisfied: scikit-learn~=1.3 in c:\programdata\anaconda3\lib\site-packages (from matminer) (1.7.2)
Requirement already satisfied: sympy~=1.11 in c:\programdata\anaconda3\lib\site-packages (from matminer) (1.14.0)
Requirement already satisfied: scipy>=1.17.0 in c:\users\admin\appdata\roaming\python\python313\site-packages (from matminer) (1.18.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: dnspython<3.0.0,>=2.7.0 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymongo~=4.5->matminer) (2.8.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.23.0->mp-api) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.23.0->mp-api) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.23.0->mp-api) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.23.0->mp-api) (2025.11.12)
Requirement already satisfied: joblib>=1.2.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn~=1.3->matminer) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn~=1.3->matminer) (3.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\programdata\anaconda3\lib\site-packages (from sympy~=1.11->matminer) (1.3.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from tqdm~=4.66->matminer) (0.4.6)
Requirement already satisfied: wrapt<3,>=1.10 in c:\programdata\anaconda3\lib\site-packages (from deprecated>=1.2.18->deltalake<1.6.0,>=1.4.0->mp-api) (1.17.0)
Requirement already satisfied: pydantic>=2.12 in c:\programdata\anaconda3\lib\site-packages (from emmet-core>=0.87.1->mp-api) (2.12.4)
Requirement already satisfied: pydantic-settings>=2.0 in c:\programdata\anaconda3\lib\site-packages (from emmet-core>=0.87.1->mp-api) (2.12.0)
Requirement already satisfied: pymatgen-io-validation>=0.1.1 in c:\users\admin\appdata\roaming\python\python313\site-packages (from emmet-core>=0.87.1->mp-api) (0.1.4)
Requirement already satisfied: pybtex~=0.24 in c:\users\admin\appdata\roaming\python\python313\site-packages (from emmet-core>=0.87.1->mp-api) (0.26.1)
Requirement already satisfied: blake3 in c:\users\admin\appdata\roaming\python\python313\site-packages (from emmet-core>=0.87.1->mp-api) (1.0.9)
Requirement already satisfied: inflect in c:\users\admin\appdata\roaming\python\python313\site-packages (from emmet-core>=0.87.1->mp-api) (7.5.0)
Requirement already satisfied: pubchempy in c:\users\admin\appdata\roaming\python\python313\site-packages (from emmet-core>=0.87.1->mp-api) (1.0.5)
Requirement already satisfied: latexcodec>=1.0.4 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pybtex~=0.24->emmet-core>=0.87.1->mp-api) (3.0.1)
Requirement already satisfied: pyyaml>=3.01 in c:\programdata\anaconda3\lib\site-packages (from pybtex~=0.24->emmet-core>=0.87.1->mp-api) (6.0.3)
Requirement already satisfied: ruamel.yaml in c:\programdata\anaconda3\lib\site-packages (from monty>=2024.12.10->mp-api) (0.18.16)
Requirement already satisfied: annotated-types>=0.6.0 in c:\programdata\anaconda3\lib\site-packages (from pydantic>=2.12->emmet-core>=0.87.1->mp-api) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\programdata\anaconda3\lib\site-packages (from pydantic>=2.12->emmet-core>=0.87.1->mp-api) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\programdata\anaconda3\lib\site-packages (from pydantic>=2.12->emmet-core>=0.87.1->mp-api) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in c:\programdata\anaconda3\lib\site-packages (from pydantic-settings>=2.0->emmet-core>=0.87.1->mp-api) (1.1.0)
Requirement already satisfied: bibtexparser<2,>=1 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (1.4.4)
Requirement already satisfied: lxml>=6.1.0 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (6.1.3)
Requirement already satisfied: matplotlib>=3.8 in c:\programdata\anaconda3\lib\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (3.10.6)
Requirement already satisfied: networkx>=2.7 in c:\programdata\anaconda3\lib\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (3.5)
Requirement already satisfied: palettable>=3.3.3 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (3.3.3)
Requirement already satisfied: plotly>=5.0 in c:\programdata\anaconda3\lib\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (6.3.0)
Requirement already satisfied: spglib>=2.5 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (2.7.0)
Requirement already satisfied: tabulate>=0.9.0 in c:\programdata\anaconda3\lib\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (0.9.0)
Requirement already satisfied: uncertainties>=3.1 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (3.2.3)
Requirement already satisfied: pyparsing>=2.0.3 in c:\programdata\anaconda3\lib\site-packages (from bibtexparser<2,>=1->pymatgen-core>=2026.9.23->pymatgen) (3.2.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.8->pymatgen-core>=2026.9.23->pymatgen) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.8->pymatgen-core>=2026.9.23->pymatgen) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.8->pymatgen-core>=2026.9.23->pymatgen) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.8->pymatgen-core>=2026.9.23->pymatgen) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.8->pymatgen-core>=2026.9.23->pymatgen) (25.0)
Requirement already satisfied: pillow>=8 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.8->pymatgen-core>=2026.9.23->pymatgen) (12.0.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\programdata\anaconda3\lib\site-packages (from plotly>=5.0->pymatgen-core>=2026.9.23->pymatgen) (2.7.0)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: botocore<1.44.0,>=1.43.100 in c:\users\admin\appdata\roaming\python\python313\site-packages (from boto3->mp-api) (1.43.100)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\programdata\anaconda3\lib\site-packages (from boto3->mp-api) (1.0.1)
Requirement already satisfied: s3transfer<0.20.0,>=0.19.0 in c:\users\admin\appdata\roaming\python\python313\site-packages (from boto3->mp-api) (0.19.2)
Requirement already satisfied: more_itertools>=8.5.0 in c:\programdata\anaconda3\lib\site-packages (from inflect->emmet-core>=0.87.1->mp-api) (10.8.0)
Requirement already satisfied: typeguard>=4.0.1 in c:\users\admin\appdata\roaming\python\python313\site-packages (from inflect->emmet-core>=0.87.1->mp-api) (4.6.0)
Requirement already satisfied: ruamel.yaml.clib>=0.2.7 in c:\programdata\anaconda3\lib\site-packages (from ruamel.yaml->monty>=2024.12.10->mp-api) (0.2.14)

In [30]:
import os
import pandas as pd
from mp_api.client import MPRester

In [31]:
import getpass

API_KEY = getpass.getpass("ENTER YOUR MATERIAL PROJECT API")

ENTER YOUR MATERIAL PROJECT API ········

In [32]:
from mp_api.client import MPRester

mpr = MPRester(API_KEY)

print("Connected to Materials Project!")

Connected to Materials Project!

In [33]:
with MPRester(API_KEY) as mpr:
    electrodes = mpr.materials.insertion_electrodes.search(
        working_ion=["Li", "Mg", "Ca", "Al", "Zn", "Y"]
    )

print(len(electrodes))

Retrieving InsertionElectrodeDoc documents:   0%|          | 0/6103 [00:00<?, ?it/s]

6103

In [34]:
data = []

for e in electrodes:
    data.append({
        "Material_ID": getattr(e, "material_id", None),
        "Working_Ion": getattr(e, "working_ion", None),
        "Voltage_V": getattr(e, "average_voltage", None),
        "Frac_Charge": getattr(e, "fracA_charge", None),
        "Frac_Discharge": getattr(e, "fracA_discharge", None)
    })

df = pd.DataFrame(data)

print("Records:", len(df))
display(df.head())
display(df.tail())

Records: 6103

  Material_ID Working_Ion  Voltage_V  Frac_Charge  Frac_Discharge
0        None          Al   3.792431          0.0        0.100000
1        None          Al   3.033092          0.0        0.076923
2        None          Al   1.845014          0.0        0.071429
3        None          Al   1.541180          0.0        0.076923
4        None          Al   1.147196          0.0        0.076923

     Material_ID Working_Ion  Voltage_V  Frac_Charge  Frac_Discharge
6098        None          Zn  -0.104729          0.0        0.066667
6099        None          Zn   0.288086          0.0        0.100000
6100        None          Zn   1.252984          0.0        0.100000
6101        None          Zn   0.832624          0.0        0.100000
6102        None          Zn   0.811808          0.0        0.100000

In [35]:
df.to_csv("ML_MiB_3977_API_dataset.csv", index=False)

print("CSV created successfully!")

CSV created successfully!

In [36]:
from mp_api.client import MPRester
import getpass

API_KEY = getpass.getpass("Enter your Materials Project API key: ")

with MPRester(API_KEY) as mpr:
    print("Connected to Materials Project!")

    docs = mpr.materials.insertion_electrodes.search(
        working_ion=["Li"],
        num_chunks=1
    )

    print("API responded!")
    print("Records received:", len(docs))

Enter your Materials Project API key:  ········

Connected to Materials Project!

Retrieving InsertionElectrodeDoc documents:   0%|          | 0/1000 [00:00<?, ?it/s]

API responded!
Records received: 1000

In [37]:
from mp_api.client import MPRester

all_electrodes = []

with MPRester(API_KEY) as mpr:
    for ion in ["Li", "Na","K","Mg", "Ca", "Al", "Zn", "Y"]:
        print(f"\nRetrieving {ion} electrodes...")

        docs = mpr.materials.insertion_electrodes.search(
            working_ion=[ion],
            num_chunks=10,
            chunk_size=1000
        )

        print(f"{ion}: {len(docs)} records")
        all_electrodes.extend(docs)

print("\nTotal retrieved:", len(all_electrodes))

Retrieving Li electrodes...

Retrieving InsertionElectrodeDoc documents:   0%|          | 0/2774 [00:00<?, ?it/s]

Li: 2774 records

Retrieving Na electrodes...

Retrieving InsertionElectrodeDoc documents:   0%|          | 0/416 [00:00<?, ?it/s]

Na: 416 records

Retrieving K electrodes...

Retrieving InsertionElectrodeDoc documents:   0%|          | 0/164 [00:00<?, ?it/s]

K: 164 records

Retrieving Mg electrodes...

Retrieving InsertionElectrodeDoc documents:   0%|          | 0/1968 [00:00<?, ?it/s]

Mg: 1968 records

Retrieving Ca electrodes...

Retrieving InsertionElectrodeDoc documents:   0%|          | 0/625 [00:00<?, ?it/s]

Ca: 625 records

Retrieving Al electrodes...

Retrieving InsertionElectrodeDoc documents:   0%|          | 0/143 [00:00<?, ?it/s]

Al: 143 records

Retrieving Zn electrodes...

Retrieving InsertionElectrodeDoc documents:   0%|          | 0/434 [00:00<?, ?it/s]

Zn: 434 records

Retrieving Y electrodes...

Retrieving InsertionElectrodeDoc documents:   0%|          | 0/159 [00:00<?, ?it/s]

Y: 159 records

Total retrieved: 6683

In [38]:
print("Total:", len(all_electrodes))
print("\nFirst record:")
print(all_electrodes[0])

Total: 6683

First record:
MPDataDoc<InsertionElectrodeDoc>
builder_meta=EmmetMeta(emmet_version='0.86.4rc1.dev71+g64b11f337.d20260323', pymatgen_version='2025.10.7', run_id=None, batch_id=None, database_version='2026.04.13', build_date=datetime.datetime(2026, 3, 26, 21, 56, 19, 265000, tzinfo=datetime.timezone.utc), license=None),
elements=[Element Cs, Element Ac, Element O],
framework_formula='CsAcO3',
formula_anonymous='ABC3',
id_discharge=MPID(mp-1236215),
formula_charge='CsAcO3',
electrode_object=InsertionElectrode with endpoints at CsAcO3 and CsLiAcO3
Avg. volt. = 2.147050163333337 V
Grav. cap. = 64.60606644586682 mAh/g
Vol. cap. = 371.64186647871196,
average_voltage=2.147050163333337,
energy_vol=797.9337301246248,
capacity_grav=64.60606644586682,
stability_charge=0.21955931,
adj_pairs=[InsertionVoltagePairDoc(formula_charge='CsAcO3', formula_discharge='CsLiAcO3', max_delta_volume=0.036626417789054004, average_voltage=2.147050163333337, capacity_grav=64.60606644586682, capacity_vol=371.64186647871196, energy_grav=138.71246551492277, energy_vol=797.9337301246248, fracA_charge=0.0, fracA_discharge=0.16666666666666602, stability_charge=0.21955931, stability_discharge=0.30064717833333005, id_charge=MPID(mp-1183923), id_discharge=MPID(mp-1236215))],
material_ids=[MPID(mp-1183923), MPID(mp-1236215)],
battery_formula='Li0-1CsAcO3',
host_structure=Structure Summary
Lattice
    abc : 4.870277 4.870277 4.870277
 angles : 90.0 90.0 90.0
 volume : 115.52101286493193
      A : 4.870277 0.0 0.0
      B : 0.0 4.870277 0.0
      C : 0.0 0.0 4.870277
    pbc : True True True
PeriodicSite: Cs (0.0, 0.0, 0.0) [0.0, 0.0, 0.0]
PeriodicSite: Ac (2.435, 2.435, 2.435) [0.5, 0.5, 0.5]
PeriodicSite: O (2.435, 2.435, 0.0) [0.5, 0.5, 0.0]
PeriodicSite: O (2.435, 0.0, 2.435) [0.5, 0.0, 0.5]
PeriodicSite: O (0.0, 2.435, 2.435) [0.0, 0.5, 0.5],
fracA_discharge=0.16666666666666602,
chemsys='Ac-Cs-O',
fracA_charge=0.0,
energy_grav=138.71246551492277,
stability_discharge=0.30064717833333005,
nelements=3,
id_charge=MPID(mp-1183923),
battery_type=<BatteryType.insertion: 'insertion'>,
max_delta_volume=0.036626417789054004,
thermo_type=None,
framework=Composition('Cs1 Ac1 O3'),
max_voltage_step=0.0,
working_ion=Element Li,
entries_composition_summary=EntriesCompositionSummary(all_formulas=['CsAcO3', 'CsLiAcO3'], all_chemsys=['Ac-Cs-O', 'Ac-Cs-Li-O'], all_formula_anonymous=['ABCD3', 'ABC3'], all_elements=[Element Cs, Element Li, Element Ac, Element O], all_composition_reduced={'Cs': [1.0], 'Ac': [1.0], 'O': [3.0], 'Li': [1.0]}),
warnings=[],
last_updated=datetime.datetime(2025, 9, 19, 9, 43, 22, 301000, tzinfo=datetime.timezone.utc),
capacity_vol=371.64186647871196,
num_steps=1,
formula_discharge='CsLiAcO3'

Fields not requested:
set()

In [39]:
print("Total:", len(all_electrodes))
print("\nFirst record:")
print(all_electrodes[0])

Total: 6683

First record:
MPDataDoc<InsertionElectrodeDoc>
builder_meta=EmmetMeta(emmet_version='0.86.4rc1.dev71+g64b11f337.d20260323', pymatgen_version='2025.10.7', run_id=None, batch_id=None, database_version='2026.04.13', build_date=datetime.datetime(2026, 3, 26, 21, 56, 19, 265000, tzinfo=datetime.timezone.utc), license=None),
elements=[Element Cs, Element Ac, Element O],
framework_formula='CsAcO3',
formula_anonymous='ABC3',
id_discharge=MPID(mp-1236215),
formula_charge='CsAcO3',
electrode_object=InsertionElectrode with endpoints at CsAcO3 and CsLiAcO3
Avg. volt. = 2.147050163333337 V
Grav. cap. = 64.60606644586682 mAh/g
Vol. cap. = 371.64186647871196,
average_voltage=2.147050163333337,
energy_vol=797.9337301246248,
capacity_grav=64.60606644586682,
stability_charge=0.21955931,
adj_pairs=[InsertionVoltagePairDoc(formula_charge='CsAcO3', formula_discharge='CsLiAcO3', max_delta_volume=0.036626417789054004, average_voltage=2.147050163333337, capacity_grav=64.60606644586682, capacity_vol=371.64186647871196, energy_grav=138.71246551492277, energy_vol=797.9337301246248, fracA_charge=0.0, fracA_discharge=0.16666666666666602, stability_charge=0.21955931, stability_discharge=0.30064717833333005, id_charge=MPID(mp-1183923), id_discharge=MPID(mp-1236215))],
material_ids=[MPID(mp-1183923), MPID(mp-1236215)],
battery_formula='Li0-1CsAcO3',
host_structure=Structure Summary
Lattice
    abc : 4.870277 4.870277 4.870277
 angles : 90.0 90.0 90.0
 volume : 115.52101286493193
      A : 4.870277 0.0 0.0
      B : 0.0 4.870277 0.0
      C : 0.0 0.0 4.870277
    pbc : True True True
PeriodicSite: Cs (0.0, 0.0, 0.0) [0.0, 0.0, 0.0]
PeriodicSite: Ac (2.435, 2.435, 2.435) [0.5, 0.5, 0.5]
PeriodicSite: O (2.435, 2.435, 0.0) [0.5, 0.5, 0.0]
PeriodicSite: O (2.435, 0.0, 2.435) [0.5, 0.0, 0.5]
PeriodicSite: O (0.0, 2.435, 2.435) [0.0, 0.5, 0.5],
fracA_discharge=0.16666666666666602,
chemsys='Ac-Cs-O',
fracA_charge=0.0,
energy_grav=138.71246551492277,
stability_discharge=0.30064717833333005,
nelements=3,
id_charge=MPID(mp-1183923),
battery_type=<BatteryType.insertion: 'insertion'>,
max_delta_volume=0.036626417789054004,
thermo_type=None,
framework=Composition('Cs1 Ac1 O3'),
max_voltage_step=0.0,
working_ion=Element Li,
entries_composition_summary=EntriesCompositionSummary(all_formulas=['CsAcO3', 'CsLiAcO3'], all_chemsys=['Ac-Cs-O', 'Ac-Cs-Li-O'], all_formula_anonymous=['ABCD3', 'ABC3'], all_elements=[Element Cs, Element Li, Element Ac, Element O], all_composition_reduced={'Cs': [1.0], 'Ac': [1.0], 'O': [3.0], 'Li': [1.0]}),
warnings=[],
last_updated=datetime.datetime(2025, 9, 19, 9, 43, 22, 301000, tzinfo=datetime.timezone.utc),
capacity_vol=371.64186647871196,
num_steps=1,
formula_discharge='CsLiAcO3'

Fields not requested:
set()

In [40]:
import pandas as pd

records = []

for e in all_electrodes:
    records.append({
        "Material_ID_Charge": str(e.id_charge),
        "Material_ID_Discharge": str(e.id_discharge),
        "Working_Ion": str(e.working_ion),
        "Electrode_Formula": e.battery_formula,
        "Framework_Formula": e.framework_formula,
        "Voltage_V": e.average_voltage,
        "Frac_Charge": e.fracA_charge,
        "Frac_Discharge": e.fracA_discharge,
        "Ion_Concentration": abs(
            e.fracA_discharge - e.fracA_charge
        ),
        "Crystal_Structure": e.host_structure
    })

base_df = pd.DataFrame(records)

print("Total API records:", len(base_df))
display(base_df.head())

Total API records: 6683

,Material_ID_Charge,Material_ID_Discharge,Working_Ion,Electrode_Formula,Framework_Formula,Voltage_V,Frac_Charge,Frac_Discharge,Ion_Concentration,Crystal_Structure
0,mp-1183923,mp-1236215,Li,Li0-1CsAcO3,CsAcO3,2.147050,0.0,0.166667,0.166667,"[[0. 0. 0.] Cs, [2.43513363 2.43513363 2.43513..."
1,mp-124,mp-865875,Li,Li0-3Ag,Ag,0.210565,0.0,0.750000,0.750000,[[0. 0. 0.] Ag]
2,mp-37153,mp-1111365,Li,Li0-2AgAsF6,AgAsF6,1.689715,0.0,0.200000,0.200000,"[[4.226357 4.226357 4.226357] Ag, [0. 0. 0.] A..."
3,mp-551758,mp-1235767,Li,Li0-1AgClO4,AgClO4,1.545882,0.0,0.142857,0.142857,"[[3.671931 3.671931 3.671931] Ag, [0. 0. 0.] C..."
4,mp-18536,mp-760151,Li,Li0-1AgF3,AgF3,5.103887,0.0,0.200000,0.200000,"[[ 2.92846612 -1.30889582 11.5723575 ] Ag, [ 2..."

In [41]:
base_df = base_df.drop_duplicates(
    subset=[
        "Material_ID_Charge",
        "Material_ID_Discharge",
        "Working_Ion"
    ]
).reset_index(drop=True)

print("After removing duplicates:", len(base_df))

After removing duplicates: 6683

In [42]:
base_df = base_df.sort_values(
    by=[
        "Working_Ion",
        "Material_ID_Charge",
        "Material_ID_Discharge"
    ]
).reset_index(drop=True)

if len(base_df) < 3977:
    raise ValueError(
        f"Only {len(base_df)} unique records available; "
        "cannot create 3977 records."
    )

base_df = base_df.iloc[:3977].copy()

print("FINAL BASE RECORDS:", len(base_df))

FINAL BASE RECORDS: 3977

In [43]:
# Check the composition of our 3977 selected records

print("Rows:", len(base_df))

print("\nExample formulas:")
display(
    base_df[
        ["Electrode_Formula", "Framework_Formula",
         "Working_Ion", "Voltage_V", "Ion_Concentration"]
    ].head(10)
)

Rows: 3977

Example formulas:

,Electrode_Formula,Framework_Formula,Working_Ion,Voltage_V,Ion_Concentration
0,Al1-3Cu,Cu,Al,-0.021586,0.250000
1,Al0-2Sn,Sn,Al,-0.148921,0.666667
2,Al0-1Ti(WO4)2,Ti(WO4)2,Al,1.625225,0.083333
3,Al0-1Mo(WO4)2,Mo(WO4)2,Al,1.560872,0.083333
4,Al0-1Mn(WO4)2,Mn(WO4)2,Al,2.482540,0.083333
5,Al0-1Bi(WO4)2,Bi(WO4)2,Al,2.042725,0.083333
6,Al0-1Sn(WO4)2,Sn(WO4)2,Al,1.558622,0.083333
7,Al0-1Re(WO4)2,Re(WO4)2,Al,1.173328,0.083333
8,Al0-1Fe(WO4)2,Fe(WO4)2,Al,2.457921,0.083333
9,Al0-1Cr(WO4)2,Cr(WO4)2,Al,2.417719,0.083333

In [44]:
# Check that structure information is available

print("Structure missing:",
      base_df["Crystal_Structure"].isna().sum())

print("Voltage missing:",
      base_df["Voltage_V"].isna().sum())

print("Working ion missing:",
      base_df["Working_Ion"].isna().sum())

Structure missing: 0
Voltage missing: 0
Working ion missing: 0

In [45]:
!pip install -U matminer pymatgen

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matminer in c:\users\admin\appdata\roaming\python\python313\site-packages (0.10.1)
Requirement already satisfied: pymatgen in c:\users\admin\appdata\roaming\python\python313\site-packages (2026.9.24)
Requirement already satisfied: numpy>=1.23 in c:\users\admin\appdata\roaming\python\python313\site-packages (from matminer) (2.5.3)
Requirement already satisfied: requests~=2.31 in c:\programdata\anaconda3\lib\site-packages (from matminer) (2.32.5)
Requirement already satisfied: pandas<3,>=1.5 in c:\programdata\anaconda3\lib\site-packages (from matminer) (2.3.3)
Requirement already satisfied: tqdm~=4.66 in c:\users\admin\appdata\roaming\python\python313\site-packages (from matminer) (4.70.1)
Requirement already satisfied: pymongo~=4.5 in c:\users\admin\appdata\roaming\python\python313\site-packages (from matminer) (4.18.2)
Requirement already satisfied: scikit-learn~=1.3 in c:\programdata\anaconda3\lib\site-packages (from matminer) (1.7.2)
Requirement already satisfied: sympy~=1.11 in c:\programdata\anaconda3\lib\site-packages (from matminer) (1.14.0)
Requirement already satisfied: monty>=2023 in c:\users\admin\appdata\roaming\python\python313\site-packages (from matminer) (2026.7.16)
Requirement already satisfied: scipy>=1.17.0 in c:\users\admin\appdata\roaming\python\python313\site-packages (from matminer) (1.18.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas<3,>=1.5->matminer) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas<3,>=1.5->matminer) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas<3,>=1.5->matminer) (2025.2)
Requirement already satisfied: dnspython<3.0.0,>=2.7.0 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymongo~=4.5->matminer) (2.8.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests~=2.31->matminer) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests~=2.31->matminer) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests~=2.31->matminer) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests~=2.31->matminer) (2025.11.12)
Requirement already satisfied: joblib>=1.2.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn~=1.3->matminer) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn~=1.3->matminer) (3.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\programdata\anaconda3\lib\site-packages (from sympy~=1.11->matminer) (1.3.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from tqdm~=4.66->matminer) (0.4.6)
Requirement already satisfied: pymatgen-core>=2026.9.23 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymatgen) (2026.9.23)
Requirement already satisfied: ruamel.yaml in c:\programdata\anaconda3\lib\site-packages (from monty>=2023->matminer) (0.18.16)
Requirement already satisfied: bibtexparser<2,>=1 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (1.4.4)
Requirement already satisfied: lxml>=6.1.0 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (6.1.3)
Requirement already satisfied: matplotlib>=3.8 in c:\programdata\anaconda3\lib\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (3.10.6)
Requirement already satisfied: networkx>=2.7 in c:\programdata\anaconda3\lib\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (3.5)
Requirement already satisfied: orjson<4,>=3.10 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (3.12.0)
Requirement already satisfied: palettable>=3.3.3 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (3.3.3)
Requirement already satisfied: plotly>=5.0 in c:\programdata\anaconda3\lib\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (6.3.0)
Requirement already satisfied: spglib>=2.5 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (2.7.0)
Requirement already satisfied: tabulate>=0.9.0 in c:\programdata\anaconda3\lib\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (0.9.0)
Requirement already satisfied: uncertainties>=3.1 in c:\users\admin\appdata\roaming\python\python313\site-packages (from pymatgen-core>=2026.9.23->pymatgen) (3.2.3)
Requirement already satisfied: pyparsing>=2.0.3 in c:\programdata\anaconda3\lib\site-packages (from bibtexparser<2,>=1->pymatgen-core>=2026.9.23->pymatgen) (3.2.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.8->pymatgen-core>=2026.9.23->pymatgen) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.8->pymatgen-core>=2026.9.23->pymatgen) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.8->pymatgen-core>=2026.9.23->pymatgen) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.8->pymatgen-core>=2026.9.23->pymatgen) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.8->pymatgen-core>=2026.9.23->pymatgen) (25.0)
Requirement already satisfied: pillow>=8 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.8->pymatgen-core>=2026.9.23->pymatgen) (12.0.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\programdata\anaconda3\lib\site-packages (from plotly>=5.0->pymatgen-core>=2026.9.23->pymatgen) (2.7.0)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.5->matminer) (1.17.0)
Requirement already satisfied: ruamel.yaml.clib>=0.2.7 in c:\programdata\anaconda3\lib\site-packages (from ruamel.yaml->monty>=2023->matminer) (0.2.14)

In [46]:
import pandas as pd
import numpy as np

from pymatgen.core import Composition
from matminer.featurizers.composition import ElementProperty

print("Matminer + Pymatgen ready!")

Matminer + Pymatgen ready!

In [47]:
from matminer.utils.data import MagpieData
from matminer.utils.data import PymatgenData

magpie = MagpieData()
pymatgen_data = PymatgenData()

print("========== MAGPIE PROPERTIES ==========")
for p in magpie.all_elemental_props:
    print(p)

print("\n========== PYMatgen PROPERTIES ==========")
for p in pymatgen_data.available_elemental_properties:
    print(p)

========== MAGPIE PROPERTIES ==========
AllenElectronegativity
AtomicRadius
AtomicVolume
AtomicWeight
BoilingT
BulkModulus
Column
CovalentRadius
Density
DipolePolarizability
ElectronAffinity
Electronegativity
FirstIonizationEnergy
FusionEnthalpy
GSbandgap
GSenergy_pa
GSestBCClatcnt
GSestFCClatcnt
GSmagmom
GSvolume_pa
HeatCapacityMass
HeatCapacityMolar
HeatFusion
HeatVaporization
HHIp
HHIr
ICSDVolume
IonizationEnergies
IsAlkali
IsDBlock
IsFBlock
IsMetal
IsMetalloid
IsNonmetal
LogThermalConductivity
MeltingT
MendeleevNumber
MiracleRadius
MolarVolume
NdUnfilled
NdValence
NfUnfilled
NfValence
NpUnfilled
NpValence
NsUnfilled
NsValence
Number
NUnfilled
NValence
n_ws^third
OxidationStates
phi
Polarizability
Row
SecondIonizationEnergy
ShearModulus
SpaceGroupNumber
ThermalConductivity
VdWRadius
ZungerPP-r_d
ZungerPP-r_p
ZungerPP-r_pi
ZungerPP-r_s
ZungerPP-r_sigma

========== PYMatgen PROPERTIES ==========

AttributeError: 'PymatgenData' object has no attribute 'available_elemental_properties'

In [48]:
FEATURES_42 = [
    "Atomic volume",
    "Atomic number",
    "Atomic weight",
    "Covalent radius",
    "Oxidation states",
    "Boiling temperature",
    "Column number",
    "Row number",
    "First ionization energy",
    "Space group number",
    "Density",
    "Is Mendeleev volume",
    "ICSD volume",
    "Polarisability",
    "BCC energy difference",
    "BCC effective lattice constant",
    "BCC Fermi",
    "BCC magnetic moment",
    "BCC volume per atom",
    "Heat capacity mass",
    "Heat capacity molar",
    "GS band gap",
    "GS estimated BCC lattice constant",
    "GS estimated FCC lattice constant",
    "GS magnetic moment",
    "GS volume per atom",
    "Is metal",
    "Is non-metal",
    "Is metalloid",
    "Is alkali",
    "Is d-block",
    "Is f-block",
    "No. of valence",
    "No. of unfilled",
    "No. of s valence",
    "No. of d unfilled",
    "No. of d valence",
    "No. of f unfilled",
    "No. of f valence",
    "No. of p valence",
    "No. of s unfilled",
    "No. of p unfilled"
]

print("Number of requested features:", len(FEATURES_42))

Number of requested features: 42

In [49]:
from matminer.utils.data import MagpieData, PymatgenData

magpie = MagpieData()
pymatgen_data = PymatgenData()

print("Magpie object:")
print(magpie)

print("\nMagpie attributes:")
print([x for x in dir(magpie) if not x.startswith("_")])

print("\nPymatgen attributes:")
print([x for x in dir(pymatgen_data) if not x.startswith("_")])

Magpie object:
<matminer.utils.data.MagpieData object at 0x00000155F8A41950>

Magpie attributes:
['all_elemental_props', 'data_dir', 'get_elemental_properties', 'get_elemental_property', 'get_oxidation_states', 'impute_nan']

Pymatgen attributes:
['get_charge_dependent_property', 'get_charge_dependent_property_from_specie', 'get_elemental_properties', 'get_elemental_property', 'get_oxidation_states', 'impute_nan', 'use_common_oxi_states']

In [50]:
print("Magpie data dictionary:")
print(magpie.__dict__.keys())

Magpie data dictionary:
dict_keys(['all_elemental_props', 'data_dir', 'impute_nan'])

In [51]:
print("Pymatgen data dictionary:")
print(pymatgen_data.__dict__.keys())

Pymatgen data dictionary:
dict_keys(['use_common_oxi_states', 'impute_nan'])

In [52]:
from matminer.utils.data import MagpieData
from matminer.utils.data import PymatgenData

magpie = MagpieData()
pymatgen_data = PymatgenData()

print("========== MAGPIE PROPERTIES ==========")
for p in magpie.all_elemental_props:
    print(p)

print("\n========== PYMatgen PROPERTIES ==========")
for p in pymatgen_data.all_elemental_pr:
    print(p)

========== MAGPIE PROPERTIES ==========
AllenElectronegativity
AtomicRadius
AtomicVolume
AtomicWeight
BoilingT
BulkModulus
Column
CovalentRadius
Density
DipolePolarizability
ElectronAffinity
Electronegativity
FirstIonizationEnergy
FusionEnthalpy
GSbandgap
GSenergy_pa
GSestBCClatcnt
GSestFCClatcnt
GSmagmom
GSvolume_pa
HeatCapacityMass
HeatCapacityMolar
HeatFusion
HeatVaporization
HHIp
HHIr
ICSDVolume
IonizationEnergies
IsAlkali
IsDBlock
IsFBlock
IsMetal
IsMetalloid
IsNonmetal
LogThermalConductivity
MeltingT
MendeleevNumber
MiracleRadius
MolarVolume
NdUnfilled
NdValence
NfUnfilled
NfValence
NpUnfilled
NpValence
NsUnfilled
NsValence
Number
NUnfilled
NValence
n_ws^third
OxidationStates
phi
Polarizability
Row
SecondIonizationEnergy
ShearModulus
SpaceGroupNumber
ThermalConductivity
VdWRadius
ZungerPP-r_d
ZungerPP-r_p
ZungerPP-r_pi
ZungerPP-r_s
ZungerPP-r_sigma

========== PYMatgen PROPERTIES ==========

AttributeError: 'PymatgenData' object has no attribute 'all_elemental_pr'

In [53]:
print("Number of Magpie properties:", len(magpie.all_elemental_props))

print("\nAll Magpie properties:")
for p in magpie.all_elemental_props:
    print(p)

Number of Magpie properties: 65

All Magpie properties:
AllenElectronegativity
AtomicRadius
AtomicVolume
AtomicWeight
BoilingT
BulkModulus
Column
CovalentRadius
Density
DipolePolarizability
ElectronAffinity
Electronegativity
FirstIonizationEnergy
FusionEnthalpy
GSbandgap
GSenergy_pa
GSestBCClatcnt
GSestFCClatcnt
GSmagmom
GSvolume_pa
HeatCapacityMass
HeatCapacityMolar
HeatFusion
HeatVaporization
HHIp
HHIr
ICSDVolume
IonizationEnergies
IsAlkali
IsDBlock
IsFBlock
IsMetal
IsMetalloid
IsNonmetal
LogThermalConductivity
MeltingT
MendeleevNumber
MiracleRadius
MolarVolume
NdUnfilled
NdValence
NfUnfilled
NfValence
NpUnfilled
NpValence
NsUnfilled
NsValence
Number
NUnfilled
NValence
n_ws^third
OxidationStates
phi
Polarizability
Row
SecondIonizationEnergy
ShearModulus
SpaceGroupNumber
ThermalConductivity
VdWRadius
ZungerPP-r_d
ZungerPP-r_p
ZungerPP-r_pi
ZungerPP-r_s
ZungerPP-r_sigma

In [54]:
print("\nSelected-property matches:\n")

keywords = [
    "volume",
    "number",
    "weight",
    "radius",
    "oxidation",
    "boiling",
    "column",
    "row",
    "ionization",
    "density",
    "mendeleev",
    "icsd",
    "polar",
    "bcc",
    "fermi",
    "magnetic",
    "heat",
    "band",
    "lattice",
    "metal",
    "alkali",
    "block",
    "valence",
    "unfilled"
]

for p in magpie.all_elemental_props:
    if any(k in p.lower() for k in keywords):
        print(p)

Selected-property matches:

AtomicRadius
AtomicVolume
AtomicWeight
BoilingT
Column
CovalentRadius
Density
DipolePolarizability
FirstIonizationEnergy
GSbandgap
GSestBCClatcnt
GSvolume_pa
HeatCapacityMass
HeatCapacityMolar
HeatFusion
HeatVaporization
ICSDVolume
IonizationEnergies
IsAlkali
IsDBlock
IsFBlock
IsMetal
IsMetalloid
IsNonmetal
MendeleevNumber
MiracleRadius
MolarVolume
NdUnfilled
NdValence
NfUnfilled
NfValence
NpUnfilled
NpValence
NsUnfilled
NsValence
Number
NUnfilled
NValence
OxidationStates
Polarizability
Row
SecondIonizationEnergy
SpaceGroupNumber
VdWRadius

In [55]:
missing_features = [
    "BCC energy difference",
    "BCC effective lattice constant",
    "BCC Fermi",
    "BCC magnetic moment",
    "BCC volume per atom",
    "GS estimated FCC lattice constant",
    "GS magnetic moment"
]

print("Properties missing from current MagpieData:")
for x in missing_features:
    print("❌", x)

Properties missing from current MagpieData:
❌ BCC energy difference
❌ BCC effective lattice constant
❌ BCC Fermi
❌ BCC magnetic moment
❌ BCC volume per atom
❌ GS estimated FCC lattice constant
❌ GS magnetic moment

In [56]:
print("\nAll available Magpie properties:")
for p in magpie.all_elemental_props:
    print(p)

All available Magpie properties:
AllenElectronegativity
AtomicRadius
AtomicVolume
AtomicWeight
BoilingT
BulkModulus
Column
CovalentRadius
Density
DipolePolarizability
ElectronAffinity
Electronegativity
FirstIonizationEnergy
FusionEnthalpy
GSbandgap
GSenergy_pa
GSestBCClatcnt
GSestFCClatcnt
GSmagmom
GSvolume_pa
HeatCapacityMass
HeatCapacityMolar
HeatFusion
HeatVaporization
HHIp
HHIr
ICSDVolume
IonizationEnergies
IsAlkali
IsDBlock
IsFBlock
IsMetal
IsMetalloid
IsNonmetal
LogThermalConductivity
MeltingT
MendeleevNumber
MiracleRadius
MolarVolume
NdUnfilled
NdValence
NfUnfilled
NfValence
NpUnfilled
NpValence
NsUnfilled
NsValence
Number
NUnfilled
NValence
n_ws^third
OxidationStates
phi
Polarizability
Row
SecondIonizationEnergy
ShearModulus
SpaceGroupNumber
ThermalConductivity
VdWRadius
ZungerPP-r_d
ZungerPP-r_p
ZungerPP-r_pi
ZungerPP-r_s
ZungerPP-r_sigma

In [57]:
magpie.data_dir

'C:\\Users\\ADMIN\\AppData\\Roaming\\Python\\Python313\\site-packages\\matminer\\utils\\data_files\\magpie_elementdata'

In [58]:
print("Magpie data directory:")
print(magpie.data_dir)

Magpie data directory:
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata

In [59]:
import os

print("\nFiles in Magpie data directory:")

for root, dirs, files in os.walk(magpie.data_dir):
    for file in files:
        print(os.path.join(root, file))

Files in Magpie data directory:
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\AllenElectronegativity.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\AtomicRadius.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\AtomicVolume.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\AtomicWeight.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\BoilingT.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\BulkModulus.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\Column.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\CovalentRadius.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\Density.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\DipolePolarizability.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\ElectronAffinity.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\Electronegativity.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\FirstIonizationEnergy.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\FusionEnthalpy.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\GSbandgap.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\GSenergy_pa.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\GSestBCClatcnt.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\GSestFCClatcnt.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\GSmagmom.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\GSvolume_pa.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\HeatCapacityMass.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\HeatCapacityMolar.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\HeatFusion.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\HeatVaporization.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\HHIp.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\HHIr.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\ICSDVolume.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\IonizationEnergies.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\IsAlkali.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\IsDBlock.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\IsFBlock.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\IsMetal.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\IsMetalloid.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\IsNonmetal.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\LogThermalConductivity.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\MeltingT.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\MendeleevNumber.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\MiracleRadius.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\MolarVolume.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\NdUnfilled.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\NdValence.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\NfUnfilled.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\NfValence.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\NpUnfilled.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\NpValence.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\NsUnfilled.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\NsValence.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\Number.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\NUnfilled.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\NValence.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\n_ws^third.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\OxidationStates.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\phi.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\Polarizability.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\README.txt
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\Row.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\SecondIonizationEnergy.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\ShearModulus.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\SpaceGroupNumber.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\ThermalConductivity.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\VdWRadius.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\ZungerPP-r_d.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\ZungerPP-r_p.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\ZungerPP-r_pi.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\ZungerPP-r_s.table
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\matminer\utils\data_files\magpie_elementdata\ZungerPP-r_sigma.table

In [60]:
base_df = base_df.iloc[:3977]

In [61]:
import zipfile
import os

ZIP_PATH = r"C:\Users\ADMIN\Downloads\machine-learning-the-voltage-of-electrode-materials-master.zip"

EXTRACT_DIR = r"C:\Users\ADMIN\Downloads"

with zipfile.ZipFile(ZIP_PATH, "r") as zip_ref:
    zip_ref.extractall(EXTRACT_DIR)

print("Repository extracted successfully!")

Repository extracted successfully!

In [62]:
ELEMENT_DATA_DIR = os.path.join(
    EXTRACT_DIR,
    "machine-learning-the-voltage-of-electrode-materials-master",
    "dataset",
    "element_data"
)

print(ELEMENT_DATA_DIR)

C:\Users\ADMIN\Downloads\machine-learning-the-voltage-of-electrode-materials-master\dataset\element_data

In [63]:
bcc_files = [
    "BCCenergydiff.table",
    "BCCefflatcnt.table",
    "BCCfermi.table",
    "BCCmagmom.table",
    "BCCvolume_pa.table"
]

for file in bcc_files:
    path = os.path.join(ELEMENT_DATA_DIR, file)
    print(file, "->", os.path.exists(path))

BCCenergydiff.table -> True
BCCefflatcnt.table -> True
BCCfermi.table -> True
BCCmagmom.table -> True
BCCvolume_pa.table -> True

In [64]:
path = os.path.join(ELEMENT_DATA_DIR, "BCCenergydiff.table")

with open(path, "r") as f:
    for i, line in enumerate(f):
        print(repr(line))
        if i >= 10:
            break

' 1.195479825 \n'
'-2.00180826 \n'
' 4.35213000000001E-03 \n'
' 9.97667849999999E-02 \n'
' 1.71126689417 \n'
' 4.337951565 \n'
' 4.1542566 \n'
' 2.297040295 \n'
' 0.8701138275 \n'
'-1.135251585 \n'
' 5.75668333000001E-03 \n'

In [65]:
CREATE_FEATURES = os.path.join(
    EXTRACT_DIR,
    "machine-learning-the-voltage-of-electrode-materials-master",
    "preprocess",
    "create_features.py"
)

print(CREATE_FEATURES)
print(os.path.exists(CREATE_FEATURES))

C:\Users\ADMIN\Downloads\machine-learning-the-voltage-of-electrode-materials-master\preprocess\create_features.py
True

In [66]:
bcc_keywords = [
    "BCCenergydiff",
    "BCCefflatcnt",
    "BCCfermi",
    "BCCmagmom",
    "BCCvolume_pa"
]

with open(CREATE_FEATURES, "r", encoding="utf-8") as f:
    lines = f.readlines()

for keyword in bcc_keywords:
    print("\n" + "="*60)
    print("SEARCH:", keyword)

    for i, line in enumerate(lines):
        if keyword.lower() in line.lower():
            start = max(0, i - 5)
            end = min(len(lines), i + 6)

            for j in range(start, end):
                print(f"{j+1}: {lines[j].rstrip()}")

============================================================
SEARCH: BCCenergydiff

============================================================
SEARCH: BCCefflatcnt

============================================================
SEARCH: BCCfermi

============================================================
SEARCH: BCCmagmom

============================================================
SEARCH: BCCvolume_pa

In [67]:
import os

# Your extracted repository location
ELEMENT_DATA_DIR = r"C:\Users\ADMIN\Downloads\machine-learning-the-voltage-of-electrode-materials-master\dataset\element_data"

BCC_PROPERTIES = [
    "BCCenergydiff",
    "BCCefflatcnt",
    "BCCfermi",
    "BCCmagmom",
    "BCCvolume_pa"
]

# Required working ions
REQUIRED_IONS = ["Li", "Na", "K", "Ca", "Mg", "Al", "Y", "Zn"]

# Atomic numbers
atomic_numbers = {
    "Li": 3,
    "Na": 11,
    "K": 19,
    "Ca": 20,
    "Mg": 12,
    "Al": 13,
    "Y": 39,
    "Zn": 30
}

def load_element_table(property_name):
    path = os.path.join(ELEMENT_DATA_DIR, property_name + ".table")

    values = []

    with open(path, "r") as f:
        for line in f:
            line = line.strip()

            if line == "" or line == "Missing":
                values.append(0.0)
            else:
                values.append(float(line))

    return values


# Load all five BCC tables
bcc_data = {}

for prop in BCC_PROPERTIES:
    bcc_data[prop] = load_element_table(prop)

print("BCC tables loaded successfully!\n")

# Check the requested working ions
for ion in REQUIRED_IONS:
    index = atomic_numbers[ion] - 1

    print(f"\n{ion} (Atomic Number {atomic_numbers[ion]})")

    for prop in BCC_PROPERTIES:
        print(f"  {prop}: {bcc_data[prop][index]}")

BCC tables loaded successfully!


Li (Atomic Number 3)
  BCCenergydiff: 0.00435213000000001
  BCCefflatcnt: 6.41636437173361
  BCCfermi: 0.22720863
  BCCmagmom: 0.0
  BCCvolume_pa: 16.51

Na (Atomic Number 11)
  BCCenergydiff: 0.00575668333000001
  BCCefflatcnt: 7.76039534599691
  BCCfermi: 1.31524918
  BCCmagmom: 0.0
  BCCvolume_pa: 29.21

K (Atomic Number 19)
  BCCenergydiff: 0.00102371332999995
  BCCefflatcnt: 10.4878165565084
  BCCfermi: -0.05407911
  BCCmagmom: 0.0
  BCCvolume_pa: 72.1

Ca (Atomic Number 20)
  BCCenergydiff: 0.0210703550000002
  BCCefflatcnt: 8.3830345410422
  BCCfermi: 2.89542357
  BCCmagmom: 0.0
  BCCvolume_pa: 36.82

Mg (Atomic Number 12)
  BCCenergydiff: 0.0286014800000001
  BCCefflatcnt: 7.15361122939302
  BCCfermi: 4.0864554
  BCCmagmom: 0.0
  BCCvolume_pa: 22.88

Al (Atomic Number 13)
  BCCenergydiff: 0.0952359899999999
  BCCefflatcnt: 6.46904413001313
  BCCfermi: 7.76407342
  BCCmagmom: 0.0
  BCCvolume_pa: 16.92

Y (Atomic Number 39)
  BCCenergydiff: 0.124302255
  BCCefflatcnt: 8.04392504902196
  BCCfermi: 3.23208944
  BCCmagmom: 0.0
  BCCvolume_pa: 32.53

Zn (Atomic Number 30)
  BCCenergydiff: 0.0829084150000001
  BCCefflatcnt: 6.09622627827544
  BCCfermi: 3.91507328
  BCCmagmom: 0.0
  BCCvolume_pa: 14.16

In [68]:
# Create lookup dictionaries for all elements

from pymatgen.core import Element

element_symbols = [str(Element.from_Z(z)) for z in range(1, 119)]

bcc_lookup = {}

for prop in BCC_PROPERTIES:
    bcc_lookup[prop] = {}

    for z, symbol in enumerate(element_symbols, start=1):
        index = z - 1
        value = bcc_data[prop][index]

        bcc_lookup[prop][symbol] = value

print("BCC lookup dictionaries created.")

# Check a few elements
for element in ["Li", "Na", "K", "Ca", "Mg", "Al", "Y", "Zn", "O", "Co"]:
    print(
        element,
        {prop: bcc_lookup[prop].get(element) for prop in BCC_PROPERTIES}
    )

IndexError: list index out of range

In [69]:
for prop in BCC_PROPERTIES:
    print(f"{prop}: {len(bcc_data[prop])} entries")

BCCenergydiff: 112 entries
BCCefflatcnt: 112 entries
BCCfermi: 112 entries
BCCmagmom: 112 entries
BCCvolume_pa: 112 entries

In [70]:
from pymatgen.core import Element

bcc_lookup = {}

for prop in BCC_PROPERTIES:
    bcc_lookup[prop] = {}

    table = bcc_data[prop]

    # Only create entries for values actually present in the table
    for index, value in enumerate(table):
        atomic_number = index + 1

        try:
            symbol = Element.from_Z(atomic_number).symbol
            bcc_lookup[prop][symbol] = value
        except Exception:
            # Ignore invalid/unrecognized atomic numbers
            pass

print("BCC lookup dictionaries created successfully.")

BCC lookup dictionaries created successfully.

In [71]:
REQUIRED_IONS = ["Li", "Na", "K", "Ca", "Mg", "Al", "Y", "Zn"]

for element in REQUIRED_IONS:
    print(f"\n{element}")

    for prop in BCC_PROPERTIES:
        print(f"  {prop}: {bcc_lookup[prop].get(element)}")

Li
  BCCenergydiff: 0.00435213000000001
  BCCefflatcnt: 6.41636437173361
  BCCfermi: 0.22720863
  BCCmagmom: 0.0
  BCCvolume_pa: 16.51

Na
  BCCenergydiff: 0.00575668333000001
  BCCefflatcnt: 7.76039534599691
  BCCfermi: 1.31524918
  BCCmagmom: 0.0
  BCCvolume_pa: 29.21

K
  BCCenergydiff: 0.00102371332999995
  BCCefflatcnt: 10.4878165565084
  BCCfermi: -0.05407911
  BCCmagmom: 0.0
  BCCvolume_pa: 72.1

Ca
  BCCenergydiff: 0.0210703550000002
  BCCefflatcnt: 8.3830345410422
  BCCfermi: 2.89542357
  BCCmagmom: 0.0
  BCCvolume_pa: 36.82

Mg
  BCCenergydiff: 0.0286014800000001
  BCCefflatcnt: 7.15361122939302
  BCCfermi: 4.0864554
  BCCmagmom: 0.0
  BCCvolume_pa: 22.88

Al
  BCCenergydiff: 0.0952359899999999
  BCCefflatcnt: 6.46904413001313
  BCCfermi: 7.76407342
  BCCmagmom: 0.0
  BCCvolume_pa: 16.92

Y
  BCCenergydiff: 0.124302255
  BCCefflatcnt: 8.04392504902196
  BCCfermi: 3.23208944
  BCCmagmom: 0.0
  BCCvolume_pa: 32.53

Zn
  BCCenergydiff: 0.0829084150000001
  BCCefflatcnt: 6.09622627827544
  BCCfermi: 3.91507328
  BCCmagmom: 0.0
  BCCvolume_pa: 14.16

In [72]:
# Check the first electrode in your existing base_df

row = base_df.iloc[0]

print("Electrode formula:", row["Electrode_Formula"])
print("Working ion:", row["Working_Ion"])
print("Voltage:", row["Voltage_V"])

structure = row["Crystal_Structure"]

print("\nElements in structure:")
for site in structure:
    print(site.specie, site.frac_coords)

Electrode formula: Al1-3Cu
Working ion: Al
Voltage: -0.021586344999999

Elements in structure:
Cu [0.5 0.5 0.5]

In [73]:
# Get composition fractions

composition = structure.composition

print("Composition:")
print(composition)

print("\nElement fractions:")

for element, fraction in composition.get_el_amt_dict().items():
    print(element, fraction)

Composition:
Cu1

Element fractions:
Cu 1.0

In [74]:
structure.composition

Composition('Cu1')

In [75]:
e.battery_formula
e.framework_formula
e.fracA_charge
e.fracA_discharge
e.host_structure
e.average_voltage
e.working_ion

Element Y

In [76]:
# Look at the first API electrode record

e = all_electrodes[0]

print("Charge ID:", e.id_charge)
print("Discharge ID:", e.id_discharge)
print("Working ion:", e.working_ion)
print("Battery formula:", e.battery_formula)
print("Framework:", e.framework_formula)
print("Voltage:", e.average_voltage)

Charge ID: mp-1183923
Discharge ID: mp-1236215
Working ion: Li
Battery formula: Li0-1CsAcO3
Framework: CsAcO3
Voltage: 2.147050163333337

In [77]:
charge_id = str(e.id_charge)
discharge_id = str(e.id_discharge)

with MPRester(API_KEY) as mpr:
    charge_docs = mpr.materials.summary.search(
        material_ids=[charge_id],
        fields=["material_id", "formula_pretty", "structure"]
    )

    discharge_docs = mpr.materials.summary.search(
        material_ids=[discharge_id],
        fields=["material_id", "formula_pretty", "structure"]
    )

print("Charge records:", len(charge_docs))
print("Discharge records:", len(discharge_docs))

if charge_docs:
    print("\nCharge formula:", charge_docs[0].formula_pretty)

if discharge_docs:
    print("Discharge formula:", discharge_docs[0].formula_pretty)

Retrieving SummaryDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving SummaryDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Charge records: 1
Discharge records: 1

Charge formula: CsAcO3
Discharge formula: CsLiAcO3

In [78]:
from pymatgen.core import Composition

charge_comp = charge_docs[0].structure.composition
discharge_comp = discharge_docs[0].structure.composition

print("Charge composition:")
print(charge_comp)

print("\nDischarge composition:")
print(discharge_comp)

print("\nCharge fractions:")
print(charge_comp.get_el_amt_dict())

print("\nDischarge fractions:")
print(discharge_comp.get_el_amt_dict())

Charge composition:
Cs1 Ac1 O3

Discharge composition:
Cs1 Li1 Ac1 O3

Charge fractions:
{'Cs': 1.0, 'Ac': 1.0, 'O': 3.0}

Discharge fractions:
{'Cs': 1.0, 'Li': 1.0, 'Ac': 1.0, 'O': 3.0}

In [79]:
# ============================================================
# 42 FEATURES WE WANT IN THE FINAL DATASET
# ============================================================

FEATURE_MAP = {
    "Atomic volume": "AtomicVolume",
    "Atomic number": "Number",
    "Atomic weight": "AtomicWeight",
    "Covalent radius": "CovalentRadius",
    "Oxidation states": "OxidationStates",
    "Boiling temperature": "BoilingT",
    "Column number": "Column",
    "Row number": "Row",
    "First ionization energy": "FirstIonizationEnergy",
    "Space group number": "SpaceGroupNumber",
    "Density": "Density",
    "Mendeleev number": "MendeleevNumber",
    "ICSD volume": "ICSDVolume",
    "Polarisability": "Polarizability",

    # GitHub repository BCC properties
    "BCC energy difference": "BCCenergydiff",
    "BCC effective lattice constant": "BCCefflatcnt",
    "BCC Fermi": "BCCfermi",
    "BCC magnetic moment": "BCCmagmom",
    "BCC volume per atom": "BCCvolume_pa",

    "Heat capacity mass": "HeatCapacityMass",
    "Heat capacity molar": "HeatCapacityMolar",
    "GS band gap": "GSbandgap",
    "GS estimated BCC lattice constant": "GSestBCClatcnt",
    "GS estimated FCC lattice constant": "GSestFCClatcnt",
    "GS magnetic moment": "GSmagmom",
    "GS volume per atom": "GSvolume_pa",

    "Is metal": "IsMetal",
    "Is non-metal": "IsNonmetal",
    "Is metalloid": "IsMetalloid",
    "Is alkali": "IsAlkali",
    "Is d-block": "IsDBlock",
    "Is f-block": "IsFBlock",

    "No. of valence": "NValence",
    "No. of unfilled": "NUnfilled",
    "No. of s valence": "NsValence",
    "No. of d unfilled": "NdUnfilled",
    "No. of d valence": "NdValence",
    "No. of f unfilled": "NfUnfilled",
    "No. of f valence": "NfValence",
    "No. of p valence": "NpValence",
    "No. of s unfilled": "NsUnfilled",
    "No. of p unfilled": "NpUnfilled"
}

print("Number of selected features:", len(FEATURE_MAP))

Number of selected features: 42

In [85]:
from matminer.featurizers.composition import ElementProperty

magpie = ElementProperty.from_preset("magpie")

In [86]:
import numpy as np
from pymatgen.core import Element


def weighted_element_property(composition, property_name):
    """
    Calculate composition-weighted mean of a Magpie elemental property.
    """

    amounts = composition.get_el_amt_dict()

    values = []
    weights = []

    for symbol, amount in amounts.items():

        try:
            value = magpie.get_elemental_property(
                Element(symbol),
                property_name
            )

            # Skip unavailable values
            if value is None or not np.isfinite(value):
                continue

            values.append(float(value))
            weights.append(float(amount))

        except Exception:
            continue

    if len(values) == 0:
        return np.nan

    return np.average(values, weights=weights)

In [87]:
charge_comp = charge_docs[0].structure.composition
discharge_comp = discharge_docs[0].structure.composition

print("Charge:", charge_comp)
print("Discharge:", discharge_comp)

print(
    "Charge Atomic Weight:",
    weighted_element_property(charge_comp, "AtomicWeight")
)

print(
    "Discharge Atomic Weight:",
    weighted_element_property(discharge_comp, "AtomicWeight")
)

Charge: Cs1 Ac1 O3
Discharge: Cs1 Li1 Ac1 O3
Charge Atomic Weight: nan
Discharge Atomic Weight: nan

In [95]:
from matminer.utils.data import MagpieData

magpie_data = MagpieData()

print(magpie_data.all_elemental_props[:10])
print("Total properties:", len(magpie_data.all_elemental_props))

KeyError: slice(None, 10, None)

In [96]:
from pymatgen.core import Element

print(
    "Cs Atomic Weight:",
    magpie_data.get_elemental_property(Element("Cs"), "AtomicWeight")
)

print(
    "O Atomic Weight:",
    magpie_data.get_elemental_property(Element("O"), "AtomicWeight")
)

Cs Atomic Weight: 132.9054519
O Atomic Weight: 15.9994

In [97]:
def weighted_element_property(composition, property_name):
    amounts = composition.get_el_amt_dict()

    values = []
    weights = []

    for symbol, amount in amounts.items():
        try:
            value = magpie_data.get_elemental_property(
                Element(symbol),
                property_name
            )

            if value is not None and np.isfinite(value):
                values.append(float(value))
                weights.append(float(amount))

        except Exception as e:
            print("Problem with", symbol, property_name, ":", e)

    if not values:
        return np.nan

    return np.average(values, weights=weights)


print(
    "Charge Atomic Weight:",
    weighted_element_property(charge_comp, "AtomicWeight")
)

print(
    "Discharge Atomic Weight:",
    weighted_element_property(discharge_comp, "AtomicWeight")
)

Charge Atomic Weight: 81.58073038
Discharge Atomic Weight: 69.14077531666668

In [98]:
# ============================================================
# CHECK ALL 42 MAGPIE PROPERTIES
# ============================================================

available_properties = []

for feature_name, magpie_name in FEATURE_MAP.items():

    try:
        value = magpie_data.get_elemental_property(
            Element("Li"),
            magpie_name
        )

        if value is not None:
            available_properties.append(
                (feature_name, magpie_name, value)
            )
        else:
            print("NO VALUE:", feature_name, "->", magpie_name)

    except Exception as e:
        print("ERROR:", feature_name, "->", magpie_name, "|", e)

print("\nAvailable Magpie properties:", len(available_properties))

ERROR: BCC energy difference -> BCCenergydiff | 'BCCenergydiff'
ERROR: BCC effective lattice constant -> BCCefflatcnt | 'BCCefflatcnt'
ERROR: BCC Fermi -> BCCfermi | 'BCCfermi'
ERROR: BCC magnetic moment -> BCCmagmom | 'BCCmagmom'
ERROR: BCC volume per atom -> BCCvolume_pa | 'BCCvolume_pa'

Available Magpie properties: 37

In [99]:
print("Li BCC properties:")

for prop in BCC_PROPERTIES:
    print(
        f"{prop}:",
        bcc_lookup[prop]["Li"]
    )

Li BCC properties:
BCCenergydiff: 0.00435213000000001
BCCefflatcnt: 6.41636437173361
BCCfermi: 0.22720863
BCCmagmom: 0.0
BCCvolume_pa: 16.51

In [100]:
# ============================================================
# COMPLETE 42-FEATURE CALCULATOR
# ============================================================

def calculate_42_features(composition):
    
    result = {}

    # --------------------------------------------------------
    # 37 MAGPIE FEATURES
    # --------------------------------------------------------
    for feature_name, magpie_name in FEATURE_MAP.items():

        # BCC properties are handled separately below
        if magpie_name in BCC_PROPERTIES:
            continue

        try:
            value = weighted_element_property(
                composition,
                magpie_name
            )

            result[feature_name] = value

        except Exception:
            result[feature_name] = np.nan

    # --------------------------------------------------------
    # 5 GITHUB BCC FEATURES
    # --------------------------------------------------------
    amounts = composition.get_el_amt_dict()

    for feature_name, bcc_property in [
        ("BCC energy difference", "BCCenergydiff"),
        ("BCC effective lattice constant", "BCCefflatcnt"),
        ("BCC Fermi", "BCCfermi"),
        ("BCC magnetic moment", "BCCmagmom"),
        ("BCC volume per atom", "BCCvolume_pa")
    ]:

        values = []
        weights = []

        for symbol, amount in amounts.items():

            try:
                value = bcc_lookup[bcc_property][symbol]

                if value is not None and np.isfinite(value):
                    values.append(float(value))
                    weights.append(float(amount))

            except Exception:
                continue

        if values:
            result[feature_name] = np.average(
                values,
                weights=weights
            )
        else:
            result[feature_name] = np.nan

    return result

In [101]:
charge_features = calculate_42_features(charge_comp)
discharge_features = calculate_42_features(discharge_comp)

print("Number of charge features:", len(charge_features))
print("Number of discharge features:", len(discharge_features))

print("\nFirst few charge features:")
for key, value in list(charge_features.items())[:10]:
    print(key, "=", value)

Problem with Cs OxidationStates : float() argument must be a string or a real number, not 'list'
Problem with Ac OxidationStates : float() argument must be a string or a real number, not 'list'
Problem with O OxidationStates : float() argument must be a string or a real number, not 'list'
Problem with Cs OxidationStates : float() argument must be a string or a real number, not 'list'
Problem with Li OxidationStates : float() argument must be a string or a real number, not 'list'
Problem with Ac OxidationStates : float() argument must be a string or a real number, not 'list'
Problem with O OxidationStates : float() argument must be a string or a real number, not 'list'
Number of charge features: 42
Number of discharge features: 42

First few charge features:
Atomic volume = 11186.296120314615
Atomic number = 33.6
Atomic weight = 81.58073038
Covalent radius = 131.4
Oxidation states = nan
Boiling temperature = 937.46
Column number = 10.4
Row number = 3.8
First ionization energy = 9.983611
Space group number = 98.0

In [102]:
# Check exactly what Magpie returns
for symbol in ["Cs", "Ac", "O", "Li"]:
    value = magpie_data.get_elemental_property(
        Element(symbol),
        "OxidationStates"
    )
    
    print(symbol, "->", value, type(value))

Cs -> [1.0] <class 'list'>
Ac -> [3.0] <class 'list'>
O -> [-2.0] <class 'list'>
Li -> [1.0] <class 'list'>

In [103]:
def weighted_element_property(composition, property_name):
    """
    Calculate composition-weighted mean of a Magpie elemental property.
    Handles list-valued properties such as OxidationStates.
    """

    amounts = composition.get_el_amt_dict()

    values = []
    weights = []

    for symbol, amount in amounts.items():

        try:
            value = magpie_data.get_elemental_property(
                Element(symbol),
                property_name
            )

            # Handle list-valued properties
            if isinstance(value, (list, tuple, np.ndarray)):
                if len(value) == 0:
                    continue
                value = value[0]

            if value is not None and np.isfinite(value):
                values.append(float(value))
                weights.append(float(amount))

        except Exception as e:
            print(
                "Problem with",
                symbol,
                property_name,
                ":",
                e
            )

    if not values:
        return np.nan

    return np.average(values, weights=weights)

In [104]:
print(
    "Charge Oxidation States:",
    weighted_element_property(
        charge_comp,
        "OxidationStates"
    )
)

print(
    "Discharge Oxidation States:",
    weighted_element_property(
        discharge_comp,
        "OxidationStates"
    )
)

Charge Oxidation States: -0.4
Discharge Oxidation States: -0.16666666666666666

In [105]:
for symbol in ["Cs", "Ac", "O", "Li"]:
    print(
        symbol,
        "AtomicVolume =",
        magpie_data.get_elemental_property(
            Element(symbol),
            "AtomicVolume"
        )
    )

Cs AtomicVolume = 117.456015807924
Ac AtomicVolume = 37.4330862969509
O AtomicVolume = 18592.1971664894
Li AtomicVolume = 21.5440580798753

In [106]:
# Check the original repository's AtomicVolume data
import os

element_data_path = r"C:\Users\ADMIN\Downloads\machine-learning-the-voltage-of-electrode-materials-master\dataset\element_data"

print(os.listdir(element_data_path))

['AtimicNumber.table', 'AtomicVolume.table', 'AtomicWeight.table', 'BCCefflatcnt.table', 'BCCenergydiff.table', 'BCCfermi.table', 'BCCmagmom.table', 'BCCvolume_pa.table', 'BCCvolume_padiff.table', 'BoilingT.table', 'ColumnNumber.table', 'CovalentRadius.table', 'Density.table', 'FirstIonizationEnergy.table', 'GSbandgap.table', 'GSefflatcnt.table', 'GSestBCClatcnt.table', 'GSestFCClatcnt.table', 'GSmagmom.table', 'GSvolume_pa.table', 'HeatCapacityMass.table', 'HeatCapacityMolar.table', 'ICSDVolume.table', 'IsAlkali.table', 'IsDBlock.table', 'IsFBlock.table', 'IsMetal.table', 'IsMetalloid.table', 'IsNonmetal.table', 'MendeleevNumber.table', 'NdUnfilled.table', 'NdValence.table', 'NfUnfilled.table', 'NfValence.table', 'NpUnfilled.table', 'NpValence.table', 'NsUnfilled.table', 'NsValence.table', 'NUnfilled.table', 'NValance.table', 'OxidationStates.table', 'Polarizability.table', 'RowNumber.table', 'SpaceGroupNumber.table']

In [107]:
# Search repository files for AtomicVolume definition
import os

for root, dirs, files in os.walk(
    r"C:\Users\ADMIN\Downloads\machine-learning-the-voltage-of-electrode-materials-master"
):
    for file in files:
        if file.endswith((".py", ".table", ".csv", ".txt")):
            path = os.path.join(root, file)

            try:
                with open(path, "r", encoding="utf-8", errors="ignore") as f:
                    text = f.read()

                if "AtomicVolume" in text:
                    print("\nFOUND:", path)
                    for line in text.splitlines():
                        if "AtomicVolume" in line:
                            print(line[:300])
            except:
                pass

FOUND: C:\Users\ADMIN\Downloads\machine-learning-the-voltage-of-electrode-materials-master\preprocess\utils.py
    'AtomicVolume',

In [108]:
from pathlib import Path

path = Path(
    r"C:\Users\ADMIN\Downloads\machine-learning-the-voltage-of-electrode-materials-master\preprocess\utils.py"
)

text = path.read_text(encoding="utf-8", errors="ignore")

lines = text.splitlines()

for i, line in enumerate(lines):
    if "AtomicVolume" in line:
        start = max(0, i - 15)
        end = min(len(lines), i + 20)

        print("\n".join(
            f"{j+1}: {lines[j]}"
            for j in range(start, end)
        ))

1: import numpy as np
2: from os import path, linesep
3: from pymatgen.core import Composition, Element
4:
5:
6: NUM_OF_FEATURE = 239
7:
8: COLUMNS = [
9:     'AtimicNumber',
10:     'AtomicVolume',
11:     'AtomicWeight',
12:     'BCCefflatcnt',
13:     'BCCenergydiff',
14:     'BCCfermi',
15:     'BCCmagmom',
16:     'BCCvolume_pa',
17:     'BCCvolume_padiff',
18:     'BoilingT',
19:     'ColumnNumber',
20:     'CovalentRadius',
21:     'Density',
22:     'FirstIonizationEnergy',
23:     'GSbandgap',
24:     'GSefflatcnt',
25:     'GSestBCClatcnt',
26:     'GSestFCClatcnt',
27:     'GSmagmom',
28:     'GSvolume_pa',
29:     'HeatCapacityMass',

In [109]:
for i, line in enumerate(lines):
    if "def " in line or "table" in line.lower() or "element_data" in line.lower():
        print(f"{i+1}: {line}")

58:     _element_data_instance = None
61:     def get_instance(self, element_data_path, columns=COLUMNS):
62:         if not self._element_data_instance:
63:             self._element_data_instance = {}
64:             # store element_data
66:                 element_data = None
67:                 with open(path.join(element_data_path, col + '.table'), 'r') as f:
69:                         element_data = [0 if line.rstrip(linesep) == 'Missing' or line.rstrip(linesep) == ''
72:                 self._element_data_instance[col] = element_data
74:         return self._element_data_instance
77: def create_feature_from_formula(formula, element_data, columns=COLUMNS):
86:                 features[i] = element_data[col][ele.number - 1]
101:                     tmp_mean_feat += element_data[col][ele.number - 1] * comp_ratio
109:                     tmp_deviation_feat += abs(element_data[col][ele.number - 1] - mean_feat) * comp_ratio
125: def create_feature_from_wokring_ion(ion):
151: def create_feature_from_crystal_system(crystal_system):

In [110]:
for i, line in enumerate(lines):
    if "BCC" in line or "AtomicVolume" in line or "get_element" in line:
        print(f"{i+1}: {line}")

10:     'AtomicVolume',
12:     'BCCefflatcnt',
13:     'BCCenergydiff',
14:     'BCCfermi',
15:     'BCCmagmom',
16:     'BCCvolume_pa',
17:     'BCCvolume_padiff',
25:     'GSestBCClatcnt',

In [111]:
import os

element_data_path = r"C:\Users\ADMIN\Downloads\machine-learning-the-voltage-of-electrode-materials-master\dataset\element_data"

atomic_volume_path = os.path.join(element_data_path, "AtomicVolume.table")

print("Exists:", os.path.exists(atomic_volume_path))

with open(atomic_volume_path, "r") as f:
    atomic_volume_data = [
        line.strip()
        for line in f
        if line.strip()
    ]

print("Number of entries:", len(atomic_volume_data))

for symbol in ["Li", "Na", "K", "Ca", "Mg", "Al", "Y", "Zn", "Cs", "Ac", "O"]:
    from pymatgen.core import Element

    Z = Element(symbol).number
    value = atomic_volume_data[Z - 1]

    print(f"{symbol}: {value}")

Exists: True
Number of entries: 112
Li: 21.5440580798753
Na: 39.4383288822527
K: 75.8478646830779
Ca: 42.9371873024716
Mg: 23.2222930956267
Al: 16.5944245175099
Y: 33.0132128825196
Zn: 15.2056837348025
Cs: 117.456015807924
Ac: 37.4330862969509
O: 18592.1971664894

In [123]:
import os
import numpy as np
import pandas as pd
from pymatgen.core import Element, Composition

ELEMENT_DATA_PATH = r"C:\Users\ADMIN\Downloads\machine-learning-the-voltage-of-electrode-materials-master\dataset\element_data"

# Our 42 selected features
FEATURE_TABLES = {
    "Atomic volume": "AtomicVolume",
    "Atomic number": "AtimicNumber",
    "Atomic weight": "AtomicWeight",
    "Covalent radius": "CovalentRadius",
    "Oxidation states": "OxidationStates",
    "Boiling temperature": "BoilingT",
    "Column number": "ColumnNumber",
    "Row number": "RowNumber",
    "First ionization energy": "FirstIonizationEnergy",
    "Density": "Density",
    "Mendeleev number": "MendeleevNumber",
    "ICSD volume": "ICSDVolume",
    "Polarisability": "Polarizability",

    "BCC energy difference": "BCCenergydiff",
    "BCC effective lattice constant": "BCCefflatcnt",
    "BCC Fermi": "BCCfermi",
    "BCC magnetic moment": "BCCmagmom",
    "BCC volume per atom": "BCCvolume_pa",

    "Heat capacity mass": "HeatCapacityMass",
    "Heat capacity molar": "HeatCapacityMolar",

    "GS band gap": "GSbandgap",
    "GS estimated BCC lattice constant": "GSestBCClatcnt",
    "GS estimated FCC lattice constant": "GSestFCClatcnt",
    "GS magnetic moment": "GSmagmom",
    "GS volume per atom": "GSvolume_pa",

    "Is metal": "IsMetal",
    "Is non-metal": "IsNonmetal",
    "Is metalloid": "IsMetalloid",
    "Is alkali": "IsAlkali",
    "Is d-block": "IsDBlock",
    "Is f-block": "IsFBlock",

    "No. of valence": "NValence",
    "No. of unfilled": "NUnfilled",
    "No. of s valence": "NsValence",
    "No. of d unfilled": "NdUnfilled",
    "No. of d valence": "NdValence",
    "No. of f unfilled": "NfUnfilled",
    "No. of f valence": "NfValence",
    "No. of p valence": "NpValence",
    "No. of s unfilled": "NsUnfilled",
    "No. of p unfilled": "NpUnfilled"
}

print("Number of selected features:", len(FEATURE_TABLES))

Number of selected features: 41

In [124]:
missing_tables = []

for feature_name, table_name in FEATURE_TABLES.items():

    file_path = os.path.join(
        ELEMENT_DATA_PATH,
        table_name + ".table"
    )

    if not os.path.exists(file_path):
        missing_tables.append(
            (feature_name, table_name)
        )

print("Missing tables:", missing_tables)

Missing tables: [('No. of valence', 'NValence')]

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ADMIN\\Downloads\\machine-learning-the-voltage-of-electrode-materials-master\\dataset\\element_data\\NValence.table'

In [117]:
import os

ELEMENT_DATA_PATH = r"C:\Users\ADMIN\Downloads\machine-learning-the-voltage-of-electrode-materials-master\dataset\element_data"

table_files = sorted([
    f for f in os.listdir(ELEMENT_DATA_PATH)
    if f.endswith(".table")
])

print("Number of table files:", len(table_files))

for f in table_files:
    print(f)

Number of table files: 44
AtimicNumber.table
AtomicVolume.table
AtomicWeight.table
BCCefflatcnt.table
BCCenergydiff.table
BCCfermi.table
BCCmagmom.table
BCCvolume_pa.table
BCCvolume_padiff.table
BoilingT.table
ColumnNumber.table
CovalentRadius.table
Density.table
FirstIonizationEnergy.table
GSbandgap.table
GSefflatcnt.table
GSestBCClatcnt.table
GSestFCClatcnt.table
GSmagmom.table
GSvolume_pa.table
HeatCapacityMass.table
HeatCapacityMolar.table
ICSDVolume.table
IsAlkali.table
IsDBlock.table
IsFBlock.table
IsMetal.table
IsMetalloid.table
IsNonmetal.table
MendeleevNumber.table
NUnfilled.table
NValance.table
NdUnfilled.table
NdValence.table
NfUnfilled.table
NfValence.table
NpUnfilled.table
NpValence.table
NsUnfilled.table
NsValence.table
OxidationStates.table
Polarizability.table
RowNumber.table
SpaceGroupNumber.table

In [126]:
import os
import numpy as np
import pandas as pd
from pymatgen.core import Element, Composition

ELEMENT_DATA_PATH = r"C:\Users\ADMIN\Downloads\machine-learning-the-voltage-of-electrode-materials-master\dataset\element_data"

# Our 42 selected features


FEATURE_TABLES = {
    "Atomic volume": "AtomicVolume",
    "Atomic number": "AtimicNumber",
    "Atomic weight": "AtomicWeight",
    "Covalent radius": "CovalentRadius",
    "Oxidation states": "OxidationStates",
    "Boiling temperature": "BoilingT",
    "Column number": "ColumnNumber",
    "Row number": "RowNumber",
    "First ionization energy": "FirstIonizationEnergy",

    "Density": "Density",
    "Mendeleev number": "MendeleevNumber",
    "ICSD volume": "ICSDVolume",
    "Polarisability": "Polarizability",

    "BCC energy difference": "BCCenergydiff",
    "BCC effective lattice constant": "BCCefflatcnt",
    "BCC Fermi": "BCCfermi",
    "BCC magnetic moment": "BCCmagmom",
    "BCC volume per atom": "BCCvolume_pa",

    "Heat capacity mass": "HeatCapacityMass",
    "Heat capacity molar": "HeatCapacityMolar",

    "GS band gap": "GSbandgap",
    "GS estimated BCC lattice constant": "GSestBCClatcnt",
    "GS estimated FCC lattice constant": "GSestFCClatcnt",
    "GS magnetic moment": "GSmagmom",
    "GS volume per atom": "GSvolume_pa",

    "Is metal": "IsMetal",
    "Is non-metal": "IsNonmetal",
    "Is metalloid": "IsMetalloid",
    "Is alkali": "IsAlkali",
    "Is d-block": "IsDBlock",
    "Is f-block": "IsFBlock",

    "No. of valence": "NValance",
    "No. of unfilled": "NUnfilled",
    "No. of s valence": "NsValence",
    "No. of d unfilled": "NdUnfilled",
    "No. of d valence": "NdValence",
    "No. of f unfilled": "NfUnfilled",
    "No. of f valence": "NfValence",
    "No. of p valence": "NpValence",
    "No. of s unfilled": "NsUnfilled",
    "No. of p unfilled": "NpUnfilled"
}

print("Selected features:", len(FEATURE_TABLES))

Selected features: 41

In [127]:
missing_tables = []

for feature_name, table_name in FEATURE_TABLES.items():

    file_path = os.path.join(
        ELEMENT_DATA_PATH,
        table_name + ".table"
    )

    if not os.path.exists(file_path):
        missing_tables.append(
            (feature_name, table_name)
        )

print("Missing tables:", missing_tables)

Missing tables: []

In [128]:
FEATURE_42_NAME = "Space group number"

print("Elemental/table features:", len(FEATURE_TABLES))
print("Structural feature:", FEATURE_42_NAME)
print("TOTAL SELECTED FEATURES:", len(FEATURE_TABLES) + 1)

Elemental/table features: 41
Structural feature: Space group number
TOTAL SELECTED FEATURES: 42

In [129]:
repository_data = {}

for feature_name, table_name in FEATURE_TABLES.items():

    file_path = os.path.join(
        ELEMENT_DATA_PATH,
        table_name + ".table"
    )

    values = []

    with open(file_path, "r") as f:
        for line in f:
            line = line.strip()

            if line == "" or line == "Missing":
                values.append(np.nan)
            else:
                try:
                    values.append(float(line))
                except:
                    values.append(np.nan)

    repository_data[feature_name] = values

print("Loaded:", len(repository_data), "feature tables")

Loaded: 41 feature tables

In [130]:
structure = row0["Crystal_Structure"]

print(structure.get_space_group_info())

NameError: name 'row0' is not defined

In [131]:
row0 = base_df.iloc[0]

print("Material ID:", row0["Material_ID_Charge"])
print("Discharge ID:", row0["Material_ID_Discharge"])
print("Electrode formula:", row0["Electrode_Formula"])
print("Framework formula:", row0["Framework_Formula"])
print("Working ion:", row0["Working_Ion"])
print("Voltage:", row0["Voltage_V"])

Material ID: mp-1022721
Discharge ID: mp-1183161
Electrode formula: Al1-3Cu
Framework formula: Cu
Working ion: Al
Voltage: -0.021586344999999

In [132]:
structure = row0["Crystal_Structure"]

print(type(structure))
print(structure.get_space_group_info())

<class 'pymatgen.core.structure.Structure'>
('Pm-3m', 221)

In [133]:
space_group_number = structure.get_space_group_info()[1]

print("Space Group Number:", space_group_number)

Space Group Number: 221

In [134]:
# Calculate the 41 composition-based features
feature_values = {}

formula = row0["Framework_Formula"]

for feature_name in FEATURE_TABLES:
    feature_values[feature_name] = get_weighted_feature(
        formula,
        feature_name
    )

# Add actual crystal-structure space group number
feature_values["Space group number"] = space_group_number

# Put them in the exact order of your 42-feature list
FEATURE_ORDER = [
    "Atomic volume",
    "Atomic number",
    "Atomic weight",
    "Covalent radius",
    "Oxidation states",
    "Boiling temperature",
    "Column number",
    "Row number",
    "First ionization energy",
    "Space group number",
    "Density",
    "Mendeleev number",
    "ICSD volume",
    "Polarisability",
    "BCC energy difference",
    "BCC effective lattice constant",
    "BCC Fermi",
    "BCC magnetic moment",
    "BCC volume per atom",
    "Heat capacity mass",
    "Heat capacity molar",
    "GS band gap",
    "GS estimated BCC lattice constant",
    "GS estimated FCC lattice constant",
    "GS magnetic moment",
    "GS volume per atom",
    "Is metal",
    "Is non-metal",
    "Is metalloid",
    "Is alkali",
    "Is d-block",
    "Is f-block",
    "No. of valence",
    "No. of unfilled",
    "No. of s valence",
    "No. of d unfilled",
    "No. of d valence",
    "No. of f unfilled",
    "No. of f valence",
    "No. of p valence",
    "No. of s unfilled",
    "No. of p unfilled"
]

feature_row = {
    feature: feature_values[feature]
    for feature in FEATURE_ORDER
}

print("Number of features:", len(feature_row))

display(pd.DataFrame([feature_row]).T.rename(columns={0: "Value"}))

NameError: name 'get_weighted_feature' is not defined

In [135]:
def get_weighted_feature(formula, feature_name):
    """
    Calculate the composition-weighted mean of a repository
    elemental property.
    """

    if formula is None or pd.isna(formula):
        return np.nan

    try:
        composition = Composition(str(formula))
    except Exception:
        return np.nan

    amounts = composition.get_el_amt_dict()
    total_atoms = sum(amounts.values())

    if total_atoms == 0:
        return np.nan

    weighted_sum = 0.0
    valid_weight = 0.0

    for symbol, amount in amounts.items():

        try:
            element = Element(symbol)
            Z = element.Z

            value = repository_data[feature_name][Z - 1]

            if pd.isna(value):
                continue

            fraction = amount / total_atoms

            weighted_sum += value * fraction
            valid_weight += fraction

        except Exception:
            continue

    if valid_weight == 0:
        return np.nan

    return weighted_sum / valid_weight

In [136]:
feature_values = {}

formula = row0["Framework_Formula"]

for feature_name in FEATURE_TABLES:
    feature_values[feature_name] = get_weighted_feature(
        formula,
        feature_name
    )

# Space Group Number comes from the actual crystal structure
feature_values["Space group number"] = space_group_number

feature_row = {
    feature: feature_values[feature]
    for feature in FEATURE_ORDER
}

print("Number of features:", len(feature_row))

display(
    pd.DataFrame([feature_row]).T.rename(columns={0: "Value"})
)

NameError: name 'FEATURE_ORDER' is not defined

In [137]:
# Calculate the 41 composition-based features
feature_values = {}

formula = row0["Framework_Formula"]

for feature_name in FEATURE_TABLES:
    feature_values[feature_name] = get_weighted_feature(
        formula,
        feature_name
    )

# Add actual crystal-structure space group number
feature_values["Space group number"] = space_group_number

# Put them in the exact order of your 42-feature list
FEATURE_ORDER = [
    "Atomic volume",
    "Atomic number",
    "Atomic weight",
    "Covalent radius",
    "Oxidation states",
    "Boiling temperature",
    "Column number",
    "Row number",
    "First ionization energy",
    "Space group number",
    "Density",
    "Mendeleev number",
    "ICSD volume",
    "Polarisability",
    "BCC energy difference",
    "BCC effective lattice constant",
    "BCC Fermi",
    "BCC magnetic moment",
    "BCC volume per atom",
    "Heat capacity mass",
    "Heat capacity molar",
    "GS band gap",
    "GS estimated BCC lattice constant",
    "GS estimated FCC lattice constant",
    "GS magnetic moment",
    "GS volume per atom",
    "Is metal",
    "Is non-metal",
    "Is metalloid",
    "Is alkali",
    "Is d-block",
    "Is f-block",
    "No. of valence",
    "No. of unfilled",
    "No. of s valence",
    "No. of d unfilled",
    "No. of d valence",
    "No. of f unfilled",
    "No. of f valence",
    "No. of p valence",
    "No. of s unfilled",
    "No. of p unfilled"
]

feature_row = {
    feature: feature_values[feature]
    for feature in FEATURE_ORDER
}

print("Number of features:", len(feature_row))

display(pd.DataFrame([feature_row]).T.rename(columns={0: "Value"}))

Number of features: 42

                                         Value
Atomic volume                        11.829942
Atomic number                        29.000000
Atomic weight                        63.546000
Covalent radius                     132.000000
Oxidation states                           NaN
Boiling temperature                3200.000000
Column number                        11.000000
Row number                            4.000000
First ionization energy               7.726380
Space group number                  221.000000
Density                            8920.000000
Mendeleev number                     64.000000
ICSD volume                          11.810000
Polarisability                        6.150000
BCC energy difference                 0.037768
BCC effective lattice constant        5.617632
BCC Fermi                             4.378740
BCC magnetic moment                   0.000000
BCC volume per atom                  11.080000
Heat capacity mass                    0.385000
Heat capacity molar                  24.440000
GS band gap                           0.000000
GS estimated BCC lattice constant     2.807970
GS estimated FCC lattice constant     3.537821
GS magnetic moment                    0.000000
GS volume per atom                   11.070000
Is metal                              1.000000
Is non-metal                          0.000000
Is metalloid                          0.000000
Is alkali                             0.000000
Is d-block                            1.000000
Is f-block                            0.000000
No. of valence                       11.000000
No. of unfilled                       1.000000
No. of s valence                      1.000000
No. of d unfilled                     0.000000
No. of d valence                     10.000000
No. of f unfilled                     0.000000
No. of f valence                      0.000000
No. of p valence                      0.000000
No. of s unfilled                     1.000000
No. of p unfilled                     0.000000

In [138]:
oxidation_path = os.path.join(
    ELEMENT_DATA_PATH,
    "OxidationStates.table"
)

with open(oxidation_path, "r") as f:
    oxidation_raw = [line.strip() for line in f]

print("Number of entries:", len(oxidation_raw))

# Show the Cu entry
cu_Z = Element("Cu").Z
print("Cu atomic number:", cu_Z)
print("Cu oxidation-state raw value:", oxidation_raw[cu_Z - 1])

# Show first 20 entries
print("\nFirst 20 entries:")
for i, value in enumerate(oxidation_raw[:20], start=1):
    print(i, value)

Number of entries: 112
Cu atomic number: 29
Cu oxidation-state raw value: 1 2

First 20 entries:
1 -1 1
2
3 1
4 2
5 3
6 -4 2 4
7 -3 -2 -1 1 2 3 4 5
8 -2
9 -1
10
11 1
12 2
13 3
14 -4 2 4
15 -3 3 5
16 -2 4 6
17 -1 1 5 7
18
19 1
20 2

In [140]:
# Show the complete create_feature_from_formula function
path = r"C:\Users\ADMIN\Downloads\machine-learning-the-voltage-of-electrode-materials-master\preprocess\utils.py"

with open(path, "r", encoding="utf-8") as f:
    utils_text = f.read()

lines = utils_text.splitlines()

for i in range(77, 125):
    print(f"{i+1}: {lines[i]}")

78:     comp = Composition(formula)
79:     num_of_base_feat = 44
80:
81:     if len(comp) == 1:
82:         features = np.zeros(num_of_base_feat)
83:         ele = comp.elements[0]
84:         for i, col in enumerate(columns):
85:             if col != 'OxidationStates':
86:                 features[i] = element_data[col][ele.number - 1]
87:             else:
88:                 # FIXME: I don't understand how to treat `OxidationStates` data
89:                 features[i] = 0
90:     else:
91:         weighted_mean_feat = np.zeros(num_of_base_feat)
92:         mean_deviation_feat = np.zeros(num_of_base_feat)
93:         element_dict = comp.to_reduced_dict
94:
95:         tot_ratio = sum(element_dict.values())
96:         for i, col in enumerate(columns):
97:             if col != 'OxidationStates':
98:                 tmp_mean_feat = 0.0
99:                 for element_str, comp_ratio in element_dict.items():
100:                     ele = Element(element_str)
101:                     tmp_mean_feat += element_data[col][ele.number - 1] * comp_ratio
102:
103:                 mean_feat = tmp_mean_feat / tot_ratio
104:                 weighted_mean_feat[i] = mean_feat
105:
106:                 tmp_deviation_feat = 0.0
107:                 for element_str, comp_ratio in element_dict.items():
108:                     ele = Element(element_str)
109:                     tmp_deviation_feat += abs(element_data[col][ele.number - 1] - mean_feat) * comp_ratio
110:
111:                 deviation_feat = tmp_deviation_feat / tot_ratio
112:                 mean_deviation_feat[i] = deviation_feat
113:             else:
114:                 # FIXME: I don't understand how to treat `OxidationStates` data
115:                 mean_feat = 0.0
116:                 deviation_feat = 0.0
117:                 weighted_mean_feat[i] = mean_feat
118:                 mean_deviation_feat[i] = deviation_feat
119:
120:         features = np.concatenate([weighted_mean_feat, mean_deviation_feat])
121:
122:     return features
123:
124:
125: def create_feature_from_wokring_ion(ion):

In [141]:
def get_weighted_feature(formula, feature_name):
    """
    Calculate the feature using the original repository logic.

    OxidationStates is explicitly treated as 0 in the
    original reproduction code.
    """

    if formula is None or pd.isna(formula):
        return np.nan

    try:
        composition = Composition(str(formula))
    except Exception:
        return np.nan

    # Original repository behavior
    if feature_name == "Oxidation states":
        return 0.0

    amounts = composition.get_el_amt_dict()
    total_atoms = sum(amounts.values())

    if total_atoms == 0:
        return np.nan

    weighted_sum = 0.0

    for symbol, amount in amounts.items():

        try:
            element = Element(symbol)
            Z = element.Z

            value = repository_data[feature_name][Z - 1]

            if pd.isna(value):
                return np.nan

            weighted_sum += value * amount

        except Exception:
            return np.nan

    return weighted_sum / total_atoms

In [142]:
feature_values = {}

formula = row0["Framework_Formula"]

for feature_name in FEATURE_TABLES:
    feature_values[feature_name] = get_weighted_feature(
        formula,
        feature_name
    )

feature_values["Space group number"] = space_group_number

feature_row = {
    feature: feature_values[feature]
    for feature in FEATURE_ORDER
}

print("Number of features:", len(feature_row))

display(
    pd.DataFrame([feature_row]).T.rename(columns={0: "Value"})
)

Number of features: 42

                                         Value
Atomic volume                        11.829942
Atomic number                        29.000000
Atomic weight                        63.546000
Covalent radius                     132.000000
Oxidation states                      0.000000
Boiling temperature                3200.000000
Column number                        11.000000
Row number                            4.000000
First ionization energy               7.726380
Space group number                  221.000000
Density                            8920.000000
Mendeleev number                     64.000000
ICSD volume                          11.810000
Polarisability                        6.150000
BCC energy difference                 0.037768
BCC effective lattice constant        5.617632
BCC Fermi                             4.378740
BCC magnetic moment                   0.000000
BCC volume per atom                  11.080000
Heat capacity mass                    0.385000
Heat capacity molar                  24.440000
GS band gap                           0.000000
GS estimated BCC lattice constant     2.807970
GS estimated FCC lattice constant     3.537821
GS magnetic moment                    0.000000
GS volume per atom                   11.070000
Is metal                              1.000000
Is non-metal                          0.000000
Is metalloid                          0.000000
Is alkali                             0.000000
Is d-block                            1.000000
Is f-block                            0.000000
No. of valence                       11.000000
No. of unfilled                       1.000000
No. of s valence                      1.000000
No. of d unfilled                     0.000000
No. of d valence                     10.000000
No. of f unfilled                     0.000000
No. of f valence                      0.000000
No. of p valence                      0.000000
No. of s unfilled                     1.000000
No. of p unfilled                     0.000000

In [143]:
# Find some multielement framework examples

for i in range(len(base_df)):
    formula = str(base_df.iloc[i]["Framework_Formula"])

    try:
        comp = Composition(formula)

        if len(comp) > 1:
            print("Row:", i)
            print("Framework:", formula)
            print("Working ion:", base_df.iloc[i]["Working_Ion"])
            print("Voltage:", base_df.iloc[i]["Voltage_V"])
            print()
            
            if i > 20:
                break
    except:
        pass

Row: 2
Framework: Ti(WO4)2
Working ion: Al
Voltage: 1.625225361666667

Row: 3
Framework: Mo(WO4)2
Working ion: Al
Voltage: 1.560872183333333

Row: 4
Framework: Mn(WO4)2
Working ion: Al
Voltage: 2.482539553333332

Row: 5
Framework: Bi(WO4)2
Working ion: Al
Voltage: 2.042725291666668

Row: 6
Framework: Sn(WO4)2
Working ion: Al
Voltage: 1.558621521666663

Row: 7
Framework: Re(WO4)2
Working ion: Al
Voltage: 1.173327593333333

Row: 8
Framework: Fe(WO4)2
Working ion: Al
Voltage: 2.457920810000002

Row: 9
Framework: Cr(WO4)2
Working ion: Al
Voltage: 2.417719426666671

Row: 10
Framework: Ta(WO4)2
Working ion: Al
Voltage: 1.636686101666666

Row: 11
Framework: V(WO4)2
Working ion: Al
Voltage: 1.5385510633333361

Row: 12
Framework: Te(WO4)2
Working ion: Al
Voltage: 1.3284931216666651

Row: 13
Framework: CoO2
Working ion: Al
Voltage: 3.159547659999999

Row: 14
Framework: NiO2
Working ion: Al
Voltage: 3.542889736666666

Row: 15
Framework: Ba2Sb3O8
Working ion: Al
Voltage: -0.38177403999999804

Row: 16
Framework: Ni(WO4)2
Working ion: Al
Voltage: 3.066423846666668

Row: 17
Framework: W3O8
Working ion: Al
Voltage: 1.662394503333334

Row: 18
Framework: Cu3(SbO3)4
Working ion: Al
Voltage: -0.49258618333333204

Row: 19
Framework: Co4(CuO4)3
Working ion: Al
Voltage: 1.574902103333331

Row: 20
Framework: Cu3(WO3)4
Working ion: Al
Voltage: -0.289463153333332

Row: 21
Framework: Cu3(MoO3)4
Working ion: Al
Voltage: -0.067159586666669

In [144]:
# Test a real multielement electrode

test_index = 2
test_row = base_df.iloc[test_index]

test_formula = test_row["Framework_Formula"]
test_structure = test_row["Crystal_Structure"]

test_space_group = test_structure.get_space_group_info()[1]

test_feature_values = {}

# 41 repository-based features
for feature_name in FEATURE_TABLES:
    test_feature_values[feature_name] = get_weighted_feature(
        test_formula,
        feature_name
    )

# Actual crystal structure feature
test_feature_values["Space group number"] = test_space_group

# Put in exact 42-feature order
test_feature_row = {
    feature: test_feature_values[feature]
    for feature in FEATURE_ORDER
}

test_feature_df = pd.DataFrame([test_feature_row])

print("Framework:", test_formula)
print("Working ion:", test_row["Working_Ion"])
print("Voltage:", test_row["Voltage_V"])
print("Space group:", test_structure.get_space_group_info())
print("Number of features:", len(test_feature_row))
print("NaN values:", test_feature_df.isna().sum().sum())

display(test_feature_df.T.rename(columns={0: "Value"}))

Framework: Ti(WO4)2
Working ion: Al
Voltage: 1.625225361666667
Space group: ('P2/c', 13)
Number of features: 42
NaN values: 0

                                          Value
Atomic volume                      13526.084647
Atomic number                         21.272727
Atomic weight                         49.412927
Covalent radius                       92.000000
Oxidation states                       0.000000
Boiling temperature                 1448.800000
Column number                         13.090909
Row number                             2.909091
First ionization energy               11.954598
Space group number                    13.000000
Density                             3910.766545
Mendeleev number                      76.454545
ICSD volume                           17.113636
Polarisability                         3.928727
BCC energy difference                  1.680935
BCC effective lattice constant         5.302748
BCC Fermi                              3.847579
BCC magnetic moment                    0.000000
BCC volume per atom                    9.780000
Heat capacity mass                     0.739273
Heat capacity molar                   28.056727
GS band gap                            0.000000
GS estimated BCC lattice constant      2.783924
GS estimated FCC lattice constant      3.507524
GS magnetic moment                     0.000002
GS volume per atom                    11.057273
Is metal                               0.272727
Is non-metal                           0.727273
Is metalloid                           0.000000
Is alkali                              0.000000
Is d-block                             0.272727
Is f-block                             0.000000
No. of valence                         8.363636
No. of unfilled                        3.272727
No. of s valence                       2.000000
No. of d unfilled                      1.818182
No. of d valence                       0.909091
No. of f unfilled                      0.000000
No. of f valence                       2.545455
No. of p valence                       2.909091
No. of s unfilled                      0.000000
No. of p unfilled                      1.454545

In [145]:
def calculate_42_features_for_row(row):
    """
    Calculate the 42 selected features for one electrode record.

    41 features come from the original repository element tables.
    Space Group Number comes from the actual MP crystal structure.
    """

    formula = row["Framework_Formula"]
    structure = row["Crystal_Structure"]

    feature_values = {}

    # 41 repository-based features
    for feature_name in FEATURE_TABLES:
        feature_values[feature_name] = get_weighted_feature(
            formula,
            feature_name
        )

    # Feature #10: actual crystal structure space group
    try:
        feature_values["Space group number"] = (
            structure.get_space_group_info()[1]
        )
    except Exception:
        feature_values["Space group number"] = np.nan

    # Exact feature order
    return {
        feature: feature_values[feature]
        for feature in FEATURE_ORDER
    }

In [146]:
test_result = calculate_42_features_for_row(base_df.iloc[2])

print("Number of features:", len(test_result))
print("NaN values:", pd.Series(test_result).isna().sum())

Number of features: 42
NaN values: 0

In [147]:
all_feature_rows = []

for i, row in base_df.iterrows():

    if (i + 1) % 250 == 0:
        print(f"Processing {i + 1}/{len(base_df)}")

    features = calculate_42_features_for_row(row)

    all_feature_rows.append(features)

features_df = pd.DataFrame(all_feature_rows)

print("\nFeature generation completed.")
print("Rows:", len(features_df))
print("Columns:", len(features_df.columns))
print("Total NaN:", features_df.isna().sum().sum())

Processing 250/3977
Processing 500/3977
Processing 750/3977
Processing 1000/3977
Processing 1250/3977
Processing 1500/3977
Processing 1750/3977
Processing 2000/3977
Processing 2250/3977
Processing 2500/3977
Processing 2750/3977
Processing 3000/3977
Processing 3250/3977
Processing 3500/3977
Processing 3750/3977

Feature generation completed.
Rows: 3977
Columns: 42
Total NaN: 8

In [148]:
# Find exactly which columns contain NaN values

nan_summary = features_df.isna().sum()

print("Columns with NaN:")
print(nan_summary[nan_summary > 0])

print("\nTotal NaN:", features_df.isna().sum().sum())

Columns with NaN:
Heat capacity mass     4
Heat capacity molar    4
dtype: int64

Total NaN: 8

In [149]:
# Find the exact rows containing NaN

nan_rows = features_df[features_df.isna().any(axis=1)]

print("Rows containing NaN:", len(nan_rows))

display(nan_rows)

Rows containing NaN: 4

,Atomic volume,Atomic number,Atomic weight,Covalent radius,Oxidation states,Boiling temperature,Column number,Row number,First ionization energy,Space group number,...,No. of valence,No. of unfilled,No. of s valence,No. of d unfilled,No. of d valence,No. of f unfilled,No. of f valence,No. of p valence,No. of s unfilled,No. of p unfilled
137,13.181858,34.0,76.469022,143.000000,0.0,3436.000000,7.000000,4.500000,7.357010,225,...,7.000000,5.0,2.000000,5.0,5.0,0.000000,0.000000,0.000000,0.000000,0.000000
384,33.147549,61.0,145.000000,199.000000,0.0,3273.000000,3.000000,6.000000,5.582000,225,...,7.000000,9.0,2.000000,0.0,0.0,9.000000,5.000000,0.000000,0.000000,0.000000
989,12295.572395,28.0,65.416267,129.666667,0.0,729.004444,11.666667,3.666667,10.387431,12,...,5.555556,2.0,1.777778,0.0,0.0,0.888889,0.666667,3.111111,0.222222,0.888889
1166,11162.464507,23.0,51.681840,97.800000,0.0,1169.660000,13.400000,3.200000,11.425594,62,...,7.400000,2.2,2.000000,1.0,3.0,0.000000,0.000000,2.400000,0.000000,1.200000

In [150]:
# Show which original materials correspond to the NaN rows

nan_indices = nan_rows.index

display(
    base_df.loc[
        nan_indices,
        [
            "Material_ID_Charge",
            "Material_ID_Discharge",
            "Electrode_Formula",
            "Framework_Formula",
            "Working_Ion",
            "Voltage_V"
        ]
    ]
)

,Material_ID_Charge,Material_ID_Discharge,Electrode_Formula,Framework_Formula,Working_Ion,Voltage_V
137,mp-631551,mp-1185976,Al1-2MnTc,MnTc,Al,0.874309
384,mp-1186429,mp-1183509,Ca0-3Pm,Pm,Ca,-0.063195
989,mp-1095062,mp-1235786,Li0-1Rb2Pu(Cl2O)2,Rb2Pu(Cl2O)2,Li,2.770977
1166,mp-1189706,mp-1236280,Li0-0.25CdTcO3,CdTcO3,Li,0.514989

In [151]:
# Reload all 41 feature tables using the ORIGINAL repository behavior:
# Missing/blank entries -> 0

repository_data = {}

for feature_name, table_name in FEATURE_TABLES.items():

    file_path = os.path.join(
        ELEMENT_DATA_PATH,
        table_name + ".table"
    )

    values = []

    with open(file_path, "r") as f:
        for line in f:
            line = line.strip()

            # EXACT behavior of the original repository
            if line == "Missing" or line == "":
                values.append(0.0)
            else:
                try:
                    values.append(float(line))
                except:
                    # OxidationStates contains values like "1 2"
                    # and is handled separately by get_weighted_feature()
                    values.append(0.0)

    repository_data[feature_name] = values

print("Loaded:", len(repository_data), "feature tables")

Loaded: 41 feature tables

In [152]:
all_feature_rows = []

for i, row in base_df.iterrows():

    if (i + 1) % 250 == 0:
        print(f"Processing {i + 1}/{len(base_df)}")

    features = calculate_42_features_for_row(row)

    all_feature_rows.append(features)

features_df = pd.DataFrame(all_feature_rows)

print("\nFeature generation completed.")
print("Rows:", len(features_df))
print("Columns:", len(features_df.columns))
print("Total NaN:", features_df.isna().sum().sum())

Processing 250/3977
Processing 500/3977
Processing 750/3977
Processing 1000/3977
Processing 1250/3977
Processing 1500/3977
Processing 1750/3977
Processing 2000/3977
Processing 2250/3977
Processing 2500/3977
Processing 2750/3977
Processing 3000/3977
Processing 3250/3977
Processing 3500/3977
Processing 3750/3977

Feature generation completed.
Rows: 3977
Columns: 42
Total NaN: 0

In [153]:
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

def get_crystal_lattice_type(structure):
    """
    Get crystal system from the actual crystal structure.
    """

    try:
        analyzer = SpacegroupAnalyzer(structure)
        return analyzer.get_crystal_system()
    except Exception:
        return np.nan

In [154]:
test_structure = base_df.iloc[2]["Crystal_Structure"]

print(
    "Space group:",
    test_structure.get_space_group_info()
)

print(
    "Crystal lattice type:",
    get_crystal_lattice_type(test_structure)
)

Space group: ('P2/c', 13)
Crystal lattice type: monoclinic

In [155]:
lattice_types = []

for i, row in base_df.iterrows():

    lattice = get_crystal_lattice_type(
        row["Crystal_Structure"]
    )

    lattice_types.append(lattice)

    if (i + 1) % 500 == 0:
        print(f"Processed {i + 1}/{len(base_df)}")

lattice_df = pd.DataFrame({
    "Crystal_Lattice_Type": lattice_types
})

print("\nRows:", len(lattice_df))
print("Missing:", lattice_df["Crystal_Lattice_Type"].isna().sum())

Processed 500/3977
Processed 1000/3977
Processed 1500/3977
Processed 2000/3977
Processed 2500/3977
Processed 3000/3977
Processed 3500/3977

Rows: 3977
Missing: 0

In [156]:
metadata_df = pd.DataFrame({
    "Material_ID": base_df["Material_ID_Charge"].values,
    "Electrode_Formula": base_df["Electrode_Formula"].values,
    "Working_Ion": base_df["Working_Ion"].values,
    "Ion_Concentration": base_df["Ion_Concentration"].values,
    "Crystal_Lattice_Type": lattice_df["Crystal_Lattice_Type"].values,
    "Voltage_V": base_df["Voltage_V"].values
})

print("Metadata rows:", len(metadata_df))
print("Metadata columns:", len(metadata_df.columns))

display(metadata_df.head())

Metadata rows: 3977
Metadata columns: 6

,Material_ID,Electrode_Formula,Working_Ion,Ion_Concentration,Crystal_Lattice_Type,Voltage_V
0,mp-1022721,Al1-3Cu,Al,0.250000,cubic,-0.021586
1,mp-1022725,Al0-2Sn,Al,0.666667,cubic,-0.148921
2,mp-1041486,Al0-1Ti(WO4)2,Al,0.083333,monoclinic,1.625225
3,mp-1041534,Al0-1Mo(WO4)2,Al,0.083333,monoclinic,1.560872
4,mp-1041563,Al0-1Mn(WO4)2,Al,0.083333,monoclinic,2.482540

In [157]:
final_df = pd.concat(
    [
        metadata_df.reset_index(drop=True),
        features_df.reset_index(drop=True)
    ],
    axis=1
)

print("FINAL ROWS:", len(final_df))
print("FINAL COLUMNS:", len(final_df.columns))

FINAL ROWS: 3977
FINAL COLUMNS: 48

In [158]:
for i, column in enumerate(final_df.columns, start=1):
    print(i, column)

1 Material_ID
2 Electrode_Formula
3 Working_Ion
4 Ion_Concentration
5 Crystal_Lattice_Type
6 Voltage_V
7 Atomic volume
8 Atomic number
9 Atomic weight
10 Covalent radius
11 Oxidation states
12 Boiling temperature
13 Column number
14 Row number
15 First ionization energy
16 Space group number
17 Density
18 Mendeleev number
19 ICSD volume
20 Polarisability
21 BCC energy difference
22 BCC effective lattice constant
23 BCC Fermi
24 BCC magnetic moment
25 BCC volume per atom
26 Heat capacity mass
27 Heat capacity molar
28 GS band gap
29 GS estimated BCC lattice constant
30 GS estimated FCC lattice constant
31 GS magnetic moment
32 GS volume per atom
33 Is metal
34 Is non-metal
35 Is metalloid
36 Is alkali
37 Is d-block
38 Is f-block
39 No. of valence
40 No. of unfilled
41 No. of s valence
42 No. of d unfilled
43 No. of d valence
44 No. of f unfilled
45 No. of f valence
46 No. of p valence
47 No. of s unfilled
48 No. of p unfilled

In [159]:
FINAL_COLUMNS = [
    "Material_ID",
    "Electrode_Formula"
] + FEATURE_ORDER + [
    "Working_Ion",
    "Ion_Concentration",
    "Crystal_Lattice_Type",
    "Voltage_V"
]

final_df = final_df[FINAL_COLUMNS]

print("Rows:", len(final_df))
print("Columns:", len(final_df.columns))

for i, column in enumerate(final_df.columns, start=1):
    print(i, column)

Rows: 3977
Columns: 48
1 Material_ID
2 Electrode_Formula
3 Atomic volume
4 Atomic number
5 Atomic weight
6 Covalent radius
7 Oxidation states
8 Boiling temperature
9 Column number
10 Row number
11 First ionization energy
12 Space group number
13 Density
14 Mendeleev number
15 ICSD volume
16 Polarisability
17 BCC energy difference
18 BCC effective lattice constant
19 BCC Fermi
20 BCC magnetic moment
21 BCC volume per atom
22 Heat capacity mass
23 Heat capacity molar
24 GS band gap
25 GS estimated BCC lattice constant
26 GS estimated FCC lattice constant
27 GS magnetic moment
28 GS volume per atom
29 Is metal
30 Is non-metal
31 Is metalloid
32 Is alkali
33 Is d-block
34 Is f-block
35 No. of valence
36 No. of unfilled
37 No. of s valence
38 No. of d unfilled
39 No. of d valence
40 No. of f unfilled
41 No. of f valence
42 No. of p valence
43 No. of s unfilled
44 No. of p unfilled
45 Working_Ion
46 Ion_Concentration
47 Crystal_Lattice_Type
48 Voltage_V

In [160]:
print("========== FINAL DATASET VALIDATION ==========")

print("Rows:", len(final_df))
print("Columns:", len(final_df.columns))

print("\nTotal missing values:",
      final_df.isna().sum().sum())

print("Duplicate rows:",
      final_df.duplicated().sum())

print("\nWorking ions:")
print(final_df["Working_Ion"].value_counts())

print("\nUnique working ions:",
      sorted(final_df["Working_Ion"].unique()))

print("\nVoltage missing:",
      final_df["Voltage_V"].isna().sum())

print("Ion concentration missing:",
      final_df["Ion_Concentration"].isna().sum())

print("Crystal lattice missing:",
      final_df["Crystal_Lattice_Type"].isna().sum())

print("\nFeature columns:",
      len(FEATURE_ORDER))

print(
    "Missing feature columns:",
    [x for x in FEATURE_ORDER if x not in final_df.columns]
)

========== FINAL DATASET VALIDATION ==========
Rows: 3977
Columns: 48

Total missing values: 0
Duplicate rows: 0

Working ions:
Working_Ion
Li    2774
Ca     625
Mg     271
K      164
Al     143
Name: count, dtype: int64

Unique working ions: ['Al', 'Ca', 'K', 'Li', 'Mg']

Voltage missing: 0
Ion concentration missing: 0
Crystal lattice missing: 0

Feature columns: 42
Missing feature columns: []

In [161]:
# Check all available electrode records already retrieved
available_ion_counts = pd.Series(
    [str(e.working_ion) for e in all_electrodes]
).value_counts()

print("Available working ions in all_electrodes:")
print(available_ion_counts)

print("\nRequired ions:")
print(["Li", "Na", "K", "Ca", "Mg", "Al", "Y", "Zn"])

Available working ions in all_electrodes:
Li    2774
Mg    1968
Ca     625
Zn     434
Na     416
K      164
Y      159
Al     143
Name: count, dtype: int64

Required ions:
['Li', 'Na', 'K', 'Ca', 'Mg', 'Al', 'Y', 'Zn']

In [162]:
# Required working ions
REQUIRED_IONS = ["Li", "Na", "K", "Ca", "Mg", "Al", "Y", "Zn"]

# Convert all_electrodes to a dataframe with their original positions
all_records = []

for idx, e in enumerate(all_electrodes):
    all_records.append({
        "original_index": idx,
        "Working_Ion": str(e.working_ion),
        "Material_ID_Charge": str(e.id_charge),
        "Material_ID_Discharge": str(e.id_discharge)
    })

all_records_df = pd.DataFrame(all_records)

# Keep only the 8 required ions
all_records_df = all_records_df[
    all_records_df["Working_Ion"].isin(REQUIRED_IONS)
].copy()

print("Available records:", len(all_records_df))

print("\nAvailable by ion:")
print(
    all_records_df["Working_Ion"]
    .value_counts()
    .reindex(REQUIRED_IONS)
    .fillna(0)
    .astype(int)
)

Available records: 6683

Available by ion:
Working_Ion
Li    2774
Na     416
K      164
Ca     625
Mg    1968
Al     143
Y      159
Zn     434
Name: count, dtype: int64

In [163]:
# Calculate proportional target counts
available_counts = (
    all_records_df["Working_Ion"]
    .value_counts()
    .reindex(REQUIRED_IONS)
)

target_counts = (
    available_counts / available_counts.sum() * 3977
).round().astype(int)

# Correct rounding so total is exactly 3977
difference = 3977 - target_counts.sum()

if difference != 0:
    # Add/remove the difference from the largest available group
    largest_ion = available_counts.idxmax()
    target_counts[largest_ion] += difference

print("Target counts:")
print(target_counts)

print("\nTarget total:", target_counts.sum())

Target counts:
Working_Ion
Li    1650
Na     248
K       98
Ca     372
Mg    1171
Al      85
Y       95
Zn     258
Name: count, dtype: int64

Target total: 3977

In [164]:
selected_indices = []

for ion in REQUIRED_IONS:

    ion_records = all_records_df[
        all_records_df["Working_Ion"] == ion
    ]

    n = int(target_counts[ion])

    # Deterministic selection — no random records
    selected_indices.extend(
        ion_records.iloc[:n]["original_index"].tolist()
    )

print("Selected records:", len(selected_indices))

Selected records: 3977

In [165]:
selected_electrodes = [
    all_electrodes[i]
    for i in selected_indices
]

records = []

for e in selected_electrodes:
    records.append({
        "Material_ID_Charge": str(e.id_charge),
        "Material_ID_Discharge": str(e.id_discharge),
        "Working_Ion": str(e.working_ion),
        "Electrode_Formula": e.battery_formula,
        "Framework_Formula": e.framework_formula,
        "Voltage_V": e.average_voltage,
        "Frac_Charge": e.fracA_charge,
        "Frac_Discharge": e.fracA_discharge,
        "Ion_Concentration": abs(
            e.fracA_discharge - e.fracA_charge
        ),
        "Crystal_Structure": e.host_structure
    })

base_df = pd.DataFrame(records)

print("New base rows:", len(base_df))

print("\nWorking ions:")
print(base_df["Working_Ion"].value_counts())

New base rows: 3977

Working ions:
Working_Ion
Li    1650
Mg    1171
Ca     372
Zn     258
Na     248
K       98
Y       95
Al      85
Name: count, dtype: int64

In [166]:
# Generate the 42 selected features for the NEW 3977-row base_df

feature_rows = []

for i, row in base_df.iterrows():
    feature_rows.append(calculate_42_features_for_row(row))

features_df = pd.DataFrame(feature_rows, index=base_df.index)

print("Feature dataframe shape:", features_df.shape)
print("Expected:", (3977, 42))

Feature dataframe shape: (3977, 42)
Expected: (3977, 42)

In [167]:
# Calculate crystal lattice type

base_df["Crystal_Lattice_Type"] = base_df["Crystal_Structure"].apply(
    get_crystal_lattice_type
)

print(base_df["Crystal_Lattice_Type"].value_counts(dropna=False))

Crystal_Lattice_Type
monoclinic      1284
orthorhombic     708
triclinic        684
trigonal         448
cubic            379
tetragonal       364
hexagonal        110
Name: count, dtype: int64

In [168]:
# Create Material_ID from the charge-state Materials Project ID

metadata_df = pd.DataFrame({
    "Material_ID": base_df["Material_ID_Charge"].values,
    "Electrode_Formula": base_df["Electrode_Formula"].values,
    "Working_Ion": base_df["Working_Ion"].values,
    "Ion_Concentration": base_df["Ion_Concentration"].values,
    "Crystal_Lattice_Type": base_df["Crystal_Lattice_Type"].values,
    "Voltage_V": base_df["Voltage_V"].values
})

# Combine metadata + 42 features
final_df = pd.concat(
    [
        metadata_df[["Material_ID", "Electrode_Formula"]],
        features_df,
        metadata_df[
            [
                "Working_Ion",
                "Ion_Concentration",
                "Crystal_Lattice_Type",
                "Voltage_V"
            ]
        ]
    ],
    axis=1
)

print("Final shape:", final_df.shape)

Final shape: (3977, 48)

In [169]:
for i, col in enumerate(final_df.columns, start=1):
    print(i, col)

1 Material_ID
2 Electrode_Formula
3 Atomic volume
4 Atomic number
5 Atomic weight
6 Covalent radius
7 Oxidation states
8 Boiling temperature
9 Column number
10 Row number
11 First ionization energy
12 Space group number
13 Density
14 Mendeleev number
15 ICSD volume
16 Polarisability
17 BCC energy difference
18 BCC effective lattice constant
19 BCC Fermi
20 BCC magnetic moment
21 BCC volume per atom
22 Heat capacity mass
23 Heat capacity molar
24 GS band gap
25 GS estimated BCC lattice constant
26 GS estimated FCC lattice constant
27 GS magnetic moment
28 GS volume per atom
29 Is metal
30 Is non-metal
31 Is metalloid
32 Is alkali
33 Is d-block
34 Is f-block
35 No. of valence
36 No. of unfilled
37 No. of s valence
38 No. of d unfilled
39 No. of d valence
40 No. of f unfilled
41 No. of f valence
42 No. of p valence
43 No. of s unfilled
44 No. of p unfilled
45 Working_Ion
46 Ion_Concentration
47 Crystal_Lattice_Type
48 Voltage_V

In [170]:
print("========== DATASET VALIDATION ==========")

# Shape
print("Shape:", final_df.shape)

# Missing values
print("\nTotal missing values:", final_df.isna().sum().sum())

# Duplicate rows
print("Duplicate rows:", final_df.duplicated().sum())

# Ion distribution
print("\nWorking-ion distribution:")
print(final_df["Working_Ion"].value_counts())

# Unique ions
print("\nUnique working ions:")
print(sorted(final_df["Working_Ion"].unique()))

# Voltage
print("\nVoltage information:")
print(final_df["Voltage_V"].describe())

# Ion concentration
print("\nIon concentration information:")
print(final_df["Ion_Concentration"].describe())

# Number of columns
print("\nNumber of columns:", len(final_df.columns))

# Number of features
print("Number of selected features:", len(FEATURE_ORDER))

print("\n========================================")

========== DATASET VALIDATION ==========
Shape: (3977, 48)

Total missing values: 0
Duplicate rows: 0

Working-ion distribution:
Working_Ion
Li    1650
Mg    1171
Ca     372
Zn     258
Na     248
K       98
Y       95
Al      85
Name: count, dtype: int64

Unique working ions:
['Al', 'Ca', 'K', 'Li', 'Mg', 'Na', 'Y', 'Zn']

Voltage information:
count    3977.000000
mean        2.406358
std         1.734305
min        -2.535565
25%         1.158542
50%         2.644787
75%         3.680661
max        16.123656
Name: Voltage_V, dtype: float64

Ion concentration information:
count    3977.000000
mean        0.115813
std         0.109195
min         0.005291
25%         0.062500
50%         0.090909
75%         0.142857
max         0.993333
Name: Ion_Concentration, dtype: float64

Number of columns: 48
Number of selected features: 42

========================================

In [171]:
# Check numeric columns for NaN and infinity

numeric_cols = final_df.select_dtypes(include=np.number).columns

nan_count = final_df[numeric_cols].isna().sum().sum()
inf_count = np.isinf(final_df[numeric_cols].to_numpy()).sum()

print("Numeric NaN count:", nan_count)
print("Numeric infinity count:", inf_count)

Numeric NaN count: 0
Numeric infinity count: 0

In [172]:
required_ions = ["Li", "Na", "K", "Mg", "Ca", "Al", "Y", "Zn"]

missing_ions = [
    ion for ion in required_ions
    if ion not in final_df["Working_Ion"].unique()
]

print("Missing required ions:", missing_ions)

if not missing_ions:
    print("✅ All 8 required working ions are present.")

Missing required ions: []
✅ All 8 required working ions are present.

In [173]:
duplicate_pairs = base_df.duplicated(
    subset=[
        "Material_ID_Charge",
        "Material_ID_Discharge",
        "Working_Ion"
    ]
).sum()

print("Duplicate charge/discharge/ion records:", duplicate_pairs)

Duplicate charge/discharge/ion records: 0

In [174]:
output_path = r"C:\Users\ADMIN\Downloads\battery_voltage_dataset_3977.csv"

final_df.to_csv(
    output_path,
    index=False
)

print("CSV saved successfully!")
print(output_path)

CSV saved successfully!
C:\Users\ADMIN\Downloads\battery_voltage_dataset_3977.csv

In [175]:
import os

print("File exists:", os.path.exists(output_path))
print("File size:", os.path.getsize(output_path), "bytes")

File exists: True
File size: 2419778 bytes

In [176]:
check_df = pd.read_csv(output_path)

print("CSV shape:", check_df.shape)
print("CSV missing values:", check_df.isna().sum().sum())
print("CSV duplicate rows:", check_df.duplicated().sum())
print("CSV columns:", len(check_df.columns))
print("\nWorking ions:")
print(check_df["Working_Ion"].value_counts())

CSV shape: (3977, 48)
CSV missing values: 0
CSV duplicate rows: 0
CSV columns: 48

Working ions:
Working_Ion
Li    1650
Mg    1171
Ca     372
Zn     258
Na     248
K       98
Y       95
Al      85
Name: count, dtype: int64

In [177]:
import pickle

variables_to_save = {
    "final_df": final_df,
    "features_df": features_df,
    "base_df": base_df,
    "FEATURE_ORDER": FEATURE_ORDER,
    "FEATURE_TABLES": FEATURE_TABLES,
    "repository_data": repository_data
}

with open(r"C:\Users\ADMIN\Downloads\battery_dataset_variables.pkl", "wb") as f:
    pickle.dump(variables_to_save, f)

print("✅ Variables saved successfully!")

✅ Variables saved successfully!